### ISSUE TITLE
Can not start Ipython Clusters  in Jupyter

### ISSUE THREAD

**Issue by dpk011** [jupyter/notebook#1023]
Here are messages, 

[I 16:25:50.237 NotebookApp] Serving notebooks from local directory: /Users/abcdef
[I 16:25:50.238 NotebookApp] 0 active kernels 
[I 16:25:50.238 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 16:25:50.238 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:25:50.958 NotebookApp] 404 GET /clusters?_=1454027150747 (::1) 5.05ms referer=http://localhost:8888/tree

**Comment by minrk** [comment]
@dpk011 this should be fixed by ipython/ipyparallel#95, which should make it easier to enable/disable the clusters tab appropriately.

If you are getting a 404, this means that the notebook server extension probably hasn't been loaded. If you add `ipyparallel.nbextension` to NotebookApp.server_extensions in your config and restart the notebook server, it should load.

**Comment by JamiesHQ** [comment]
We're doing a little housekeeping on our issue log and noticed this thread from 2016. Has this issue been resolved to your satisfaction and can it be closed? thanks!

**Comment by dpk011** [comment]
Yes. Thank you. But I don't remember how. 

Thanks-deepak
 

    On Wednesday, April 26, 2017 5:28 PM, JamieW <notifications@github.com> wrote:
 

 We're doing a little housekeeping on our issue log and noticed this thread from 2016. Has this issue been resolved to your satisfaction and can it be closed? thanks!—

**Comment by JamiesHQ** [comment]
lol. thx!
