### ISSUE TITLE
re-enable CircleCI

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1056]
Circle CI don't respect `circle.yml` test function anymore, which make all PRs fail. 
I've diable the webhook for now.

We can investigate reenabling later.

**Comment by jakirkham** [comment]
Sorry, what's wrong?

**Comment by jakirkham** [comment]
So, I do see an issue trying to build on Circle CI, but it doesn't appear to be limited to there. In fact, I can see the issue when trying to build the docker image locally. Namely, the tests hang after running the test `notebook.auth.tests.test_security.test_passwd_check_unicode`. Not sure why, but it is worth investigating.

**Comment by Carreau** [comment]
Yes, it would be nice to investigate, but we don't know of a lot of people using the Docker Image and the failure was slowing down development. If you submit  PR that can fix the Docker image, I'll be happy to reenable CircleCI.

**Comment by jtyberg** [comment]
It appears that the Docker image is no longer building because [root user is not allowed to start the notebook server by default](https://github.com/jupyter/notebook/commit/3ce8d95ba1b3ab4e881f403929e9d4c4a4d3b234).

```
root@5e9f4e947359:/usr/src/jupyter-notebook# jupyter notebook --no-browser
[I 02:19:50.425 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 02:19:50.440 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 02:19:50.440 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[C 02:19:50.445 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
```

The Docker image build just hangs on the first unit test that attempts to launch the NotebookApp:

```
root@5e9f4e947359:/usr/src/jupyter-notebook# nosetests -vvv notebook.nbconvert
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
...
nose.suite: DEBUG: <nose.suite.ContextSuite context=APITest> setup context <class 'notebook.nbconvert.tests.test_nbconvert_handlers.APITest'>
nose: DEBUG: call fixture <class 'notebook.nbconvert.tests.test_nbconvert_handlers.APITest'>.setup_class
```

It hangs because of a timing issue.  Unfortunately, I don't know enough about tornado and all the goodness going on in [launchnotebook.py](https://github.com/jupyter/notebook/blob/master/notebook/tests/launchnotebook.py#L113) to debug it.

PR #1468 enables the image to be built again.
