### ISSUE TITLE
pip3 matplotlib install issue

### ISSUE THREAD

**Issue by awb99** [jupyter/notebook#1057]
This image is really cool, as Jupyter can start with both Python 2 and Python 3 kernel.
I am trying to extend on that a little bit, as I need pandas and matplotlib.

There is an issue with matplotlib, and I think the root cause is wiht in this docker image, as I found various posts that this has been fixed.

The issue is that this dependencies cannot be found in pi3: freetype, png

In matplotlib tickets, it was mentioned that in matplotlib this 2 libraries are no longer optional
dependencies, but MANDATORY.The ticket was closed, so they say they solved it. This
is why I believe that this docker image contains some of the old code still.

This is the docker image that I am creating:

```
FROM jupyter/notebook

# pandas
RUN pip2 install pandas && \
    pip3 install pandas

# matplotlib
 RUN pip3 install matplotlib && \
     pip2 install matplotlib

```
---

I tried rebuilding from source; but the same errors for pip3 occur:
```
RUN git clone https://github.com/matplotlib/matplotlib && \
    cd matplotlib  && \
    python3 setup.py build && \
    python3 setup.py install

```

Any ideas?

Regards
Andreas

**Comment by takluyver** [comment]
I imagine that freetype and libpng will need to be installed from the system package manager (`apt-get`) before trying to install matplotlib.

There's also a [scipy-notebook dockerfile](https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook) which sets up pandas, matplotlib and many other packages using conda.

**Comment by awb99** [comment]
I tried apt-get but this has the same issue. Also I am not aware of how
apt-get would manage two sets of python.

I did find docker images with conda packet management that work with
matplotlib. Perhaps the pip3 is the culprit?

I guess 90% of Jupiter Python users use matplotlib. Strange that I am the
first to notice this bug.

Am 07.02.2016 15:04 schrieb "Thomas Kluyver" <notifications@github.com>:

**Comment by takluyver** [comment]
In apt, Python 3 packages start with `python3-`, and Python 2 packages with `python-`. However, freetype and libpng are not Python packages (that's why pip won't find them). They are compiled libraries that matplotlib uses. You can find the exact names by searching on [packages.ubuntu.com](http://packages.ubuntu.com/). Note that, as pip will compile matplotlib from source, you'll need to install the `-dev` versions of packages. Alternatively, you can use apt to install matplotlib - you'll get an older version, but apt will handle the necessary dependencies.

So far, I don't think there is actually any bug here. If you're not familiar with this sort of problem, I'd recommend using one of the images built with conda, which avoids this kind of difficulty.

**Comment by awb99** [comment]
Thanks!

Best Regards,
Florian

**Comment by takluyver** [comment]
Closing as it sounds like the issue was resolved.
