### ISSUE TITLE
Refuse to start as root ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1074]
Should we refuse to run the notebook if we are root ? (unless passed an --allow-root flag). 
Should we do the same for IPython itself ?

**Comment by willingc** [comment]
This issue seems to parallel a recent issue on JupyterHub https://github.com/jupyter/jupyterhub/pull/417. From a security vantage point, if allowed, it should warn the user and require positive confirmation by the user.

**Comment by Carreau** [comment]
> if allowed, it should warn the user and require positive confirmation by the user.

Asking confirmation is annoying as the notebook can be ran as a subprocess, in which case it will wait for user input and hang for ever, which is more annoying than failing and giving an error message. 

Also running as root should be something hard instead of "just confirm a message you do not understand".

We can of course ask the user and abort after a few seconds is no answers, but is it worth it ?

**Comment by willingc** [comment]
Fair enough. There's more than one use case. Naive end user of a notebook. Use of notebooks run as subprocesses.

If a naive end user runs the notebook as root, what data or vulnerabilities are they exposing to others?

**Comment by Carreau** [comment]
> There's more than one use case

Yes, but I think in this case, it's pretty straitforward, Notebook is not ment to run as root.

> If a naive end user runs the notebook as root, what data or vulnerabilities are they exposing to others?

Depending on how they run it, from none, to get your bank account number and pwd, SSN, plus get spied on by through camera and microphone. But running as root is typically something you never want to do unless you are confortable enough to know the implications.

 Example of software that do that: brew

```
me@~ $ sudo brew install ruby
Error: Cowardly refusing to 'sudo brew install'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
me@~ $
```

**Comment by minrk** [comment]
I'm fine with an `--allow-root` arg for the notebook server.

**Comment by takluyver** [comment]
Let's not exaggerate the dangers - a naive user running the notebook as root on their local machine is not exposing anything. And if they do expose anything, either because other people can log on to the machine and connect to the server, or because they configure it to serve on the public network interface, it's pretty bad to run the server as their own user anyway (see [relevant xkcd](https://xkcd.com/1200/)).

However, it's never a good idea to run with more privileges than necessary, and I don't think many people really want to run the server as root, so :+1: to adding a confirmation flag.

`flit install` also has a similar check, and requires an environment variable `FLIT_ROOT_INSTALL` to override it.

**Comment by willingc** [comment]
> flit install also has a similar check, and requires an environment variable FLIT_ROOT_INSTALL to override it.

A very reasonable approach.

**Comment by Carreau** [comment]
Great tagging as sprint friendly, to give a chance to a new contributor to get something useful and relatively simple in.
