### ISSUE TITLE
split cell at cursor into new notebook & ipynb file concatenation - feature requests

### ISSUE THREAD

**Issue by nymoorland** [jupyter/notebook#1110]
The split cell at cursor functionality is nice. Is there a way to split it into a new notebook?  Also, is there is a command line tool to concatenate or even split(at a particular line number) two notebooks? It would useful feature in the data scientist work flow.

For the second request, a quick search turned this up which looks nice.
https://gist.github.com/fperez/e2bbc0a208e82e450f69

**Comment by nymoorland** [comment]
@Carreau @fperez  Ping. Especially for the report writing part of the work flow. Cheers.

**Comment by captainsafia** [comment]
I'll try and implement splitting a cell into two notebooks as an extension.

**Comment by captainsafia** [comment]
Hello, @nymoorland! This functionality has been implemented in [this extension](https://github.com/captainsafia/split-cell-to-notebook) if you'd like to try it out. Let me know if this fulfills what you where thinking off.

All the kudos go to @jcb91 for getting this done!

**Comment by nymoorland** [comment]
Thanks. I look forward to trying it out:)

**Comment by nymoorland** [comment]
Hi, the install instructions in link didn't work for me. Created folder at $(jupyter --config-dir)/nbextensions and dropped in the js file. Step 3 failed.

**Comment by captainsafia** [comment]
Try placing it in $(ipython locate)/nbextensions. Feel free to open an issue
in that repository as well so people who experience similar issues will have
an easier time finding the answer!
![](https://link.nylas.com/open/dzqy30d1igqlspctkj1tz54w2/local-6b5c5350-c9e9)

On Apr 21 2016, at 11:54 pm, nymoorland &lt;notifications@github.com&gt;
wrote:  

> Hi, the install instructions in link didn't work for me. Created folder at
$(jupyter --config-dir)/nbextensions and dropped in the js file. Step 3
failed.

>

> —  
You are receiving this because you were assigned.  
Reply to this email directly or [view it on GitHub](https://github.com/jupyter
/notebook/issues/1110#issuecomment-213256215)![](https://github.com/notificati
ons/beacon/ABxZySaGAKrdectjCQVhDQzE6y-cgNZoks5p6FRvgaJpZM4Hd3bd.gif)

**Comment by nymoorland** [comment]
$(ipython locate)/nbextensions did it. This is functionality I had in mind. Thanks to both contributors for implementing it.

**Comment by takluyver** [comment]
`$(ipython locate)/nbextensions` might work for now, but it is deprecated. The new location is `$(jupyter --data-dir)/nbextensions` (N.B. data-dir not config-dir)
