### ISSUE TITLE
Notebook fails to save when the folder containing it is renamed while editing

### ISSUE THREAD

**Issue by Winterflower** [jupyter/notebook#117]
Steps to replicate:

1. Create notebook in folder somefolder
2. While the notebook frontend is open in browser, rename the folder to some_folder (or something else)
3. Continue editing notebook 
4. Try to save notebook and get Errno2: No such file or directory. Fail to save work. 

It would be nice for the notebook to somehow recognize the folder it is in has changed names.

**Comment by Carreau** [comment]
I'm not sure how you could "detect" a folder rename. AFAIK no program does that. You can keep a file handle open on the `.ipynb` to follow it across external renames, or unlink, but this is problemetic for atomic write, and also have issues on windows. I doubt there is anything we can really do about that.

**Comment by damianavila** [comment]
> I doubt there is anything we can really do about that.

Yep... I agree...

**Comment by Winterflower** [comment]
Thanks a lot for responding!
I guess it's just a bit unexpected when all of a sudden you get a "Cannot Autosave" message. Luckily this happens quite soon after the folder renaming, so there wasn't much work lost.

**Comment by takluyver** [comment]
It might make sense for the server to catch the error and save it to a temporary directory (or walk up the parent directories until one exists), just so that in a situation like that, your work is preserved somewhere. But then we'd need to communicate to the user somehow where it had gone.

I think it would also be technically possible for the server to use inotify (/equivalents on other platforms) to track directory renames and update the sessions to the correct locations. But that sounds complex, and it still wouldn't work if you moved a directory outside the folder the server is running in.
