### ISSUE TITLE
bad usability for "shutdown notebook"

### ISSUE THREAD

**Issue by janschulz** [jupyter/notebook#1188]
I'm currently running a notebook server on a folder with 35 notebooks. I usually have more than one notebook open and running and usually these notebooks are not next to each other.

This leads to some bad things when I want to shutdown some notebooks:
- When I mark notebooks and shutdown the notebooks, the notebooks are still marked. Sometimes it happens that I shutdown notebooks which were selected further down (not visible in the currently visible screen)
- When I want to shutdown a notebook further down in the list, I first have to scroll up to deselect all, then scroll down to mark the notebook, then up again to shutdown.

I remember that the notebook had buttons next to the names, where I could shutdown a single notebook. I would really like to get these buttons back.

**Comment by takluyver** [comment]
Have you tried the 'Running' tab in the dashboard?

**Comment by JanSchulz** [comment]
Yes, that's better. It's still a lot to scroll (first up to the tab, then shutdown the  notebook, then back to the filetree and there scroll down to the open another notebook :-/), but most of it is gone... I would still find a dropdown or button in the file based view more usefull.

Fun, I never even realized that tab was there, probably because I once explored these tabs and they were useless for me on windows (terminal) and without a cluster. I never realized the open notebooks were moved there as well.

**Comment by Carreau** [comment]
Thanks for the feedback. 

Ping @ellisonbg that care about design. 

At think the plan is to add filtering and have the top bad with action static so that it does not scroll up.

**Comment by janschulz** [comment]
I'm used to the new method now, so I'm closing this
