### ISSUE TITLE
Mathjax incorrectly exported to html

### ISSUE THREAD

**Issue by Twangist** [jupyter/notebook#1189]
I'm working on a document that's mainly markdown + MathJax. When I "download to html", various cells get truncated part-way through the mathjax inline expression. I reduced it to the following simple case shown in the attached files.

[jupyter-mathjax-bug.zip](https://github.com/jupyter/notebook/files/164099/jupyter-mathjax-bug.zip)

**Comment by minrk** [comment]
This is an issue of your math being interpreted as HTML. Your `<k` is being interpreted as opening a `<k>` HTML tag, which then includes the rest of the document, hence the apparent truncation. There are subtle differences (not intentional ones) in how we handle math in markdown between the browser and nbconvert. In this particular case, you can avoid the issue by putting space around `<`: use `j < k` instead of `j<k` and it should be happy.

**Comment by Twangist** [comment]
Aha. Subtle but simple. Surrounding `<` with spaces did the trick. Thank you very much.
