### ISSUE TITLE
Maintainable Themes

### ISSUE THREAD

**Issue by AFJay** [jupyter/notebook#119]
I was part of the discussion found here: https://groups.google.com/forum/#!topic/jupyter/sMXF3kPmvXg
As part of a project I'm working on, Malti(https://hackaday.io/project/5081-malti), I need to write a custom theme for notebook. In the discussion above I learned that people generally go about this the wrong way. I'd like a little feedback from people about the best way to implement maintainable themes.
What I propose is:
~~1) Setting up a separate theme repo so we don't clutter the notebook repo.
2) Adding a theme menu to the notebook homepage
3) Adding a theme directory to the install files
4) Submitting themes as .less files~~

~~To implement the theme menu we could have it display the contents of the theme folder. Once the user selects a theme we run gulp automatically to regenerate the css. If the user has LiveReloading running in their browser it should automatically update.~~

1)Adding documentation on how to make themes with koala
2)Submitting themes to the repo as .less files with the compiled css files
3)Adding a theme directory to the install files
4)Implementing theme/css switching

You can find more info about Koala here: http://koala-app.com/ .

**Comment by Carreau** [comment]
> Adding a theme menu to the notebook homepage

See my 2 first blog posts on that : http://carreau.github.io/2013/index.html 
Home page might not be necessary, and configuring the theme might be configuring  a variable in a config file, it's ok for the time being. 

> To implement the theme menu we could have it display the contents of the theme folder. Once the user selects a theme we run gulp automatically to regenerate the css. If the user has LiveReloading running in their browser it should automatically update.

Gulp is only a developer dependency, so themes can be supposed to be already built. 

The submitting theme to this or another repo is not really first priority, the thing that is missing is **a tool to build a theme given a less file**.

The problem with https://github.com/nsonnad/base16-ipython-notebook is that [their files](https://github.com/nsonnad/base16-ipython-notebook/blob/master/ipython-3/templates/-dark.css.erb#L48-L50) are by design a copy and past of [ours](https://github.com/jupyter/notebook/blob/b536da10d871f87729d3c9a6269a13bf61779213/notebook/static/notebook/less/cell.less#L1-L17). As ours get changed, theirs are out of sync automatically. And frankly you don't build css with a templating engine.

Once you get the tool to build css-theme **using IPython less files** and the **themes `variable.less`** the rest a is a detail.

**Comment by AFJay** [comment]
I read through your links and I understand what's going on a little better. I need a few days to play around with this. I'll rewrite the proposal once I get a better feel for things.

**Comment by jasongrout** [comment]
I've played around with theming a bit too.  One approach is to set the theme as a class name on the body element, and make the new theme and the IPython theme both specialized to the body class name.  This lets you easily customize styling based on the body class.  I can imagine that you may want each theme to at least declare itself as a light or a dark theme (via a body class, for example), to give arbitrary 3rd party widgets a chance to change default theming depending on the background.

**Comment by Carreau** [comment]
> I've played around with theming a bit too. One approach is to set the theme as a class name on the body element, and make the new theme and the IPython theme both specialized to the body class name. This lets you easily customize styling based on the body class.

This is irrelevant to the discussion, and you are deciding of the color of the car before realizing you are building a submarine.

How do you even get the theme css on the page before switching the class ? I don't want to send everything at once if there is 50+ themes. Though the body class allow some [nice things (wait for it)](http://evil-icons.io/).

.less have some conditional base on luminosity. So you might not need to declare yourself as dark or light.

**Comment by AFJay** [comment]
So after playing with this a little here's what I came up with. We can use and outside program to compile the .less files. So in this case I'm using koala to compile a clone of the /static/base directory (iPython). This way people that just want to do themes don't have to install the whole build environment. Also, koala will watch the .less files for changes and automatically compile the css when changes are made. From there I'm dumping the output into the custom css directory (/users/xxxxx/.ipython/). It's works pretty well.

**Comment by jasongrout** [comment]
@Carreau, my comments about setting a class on the body are complementing the points on this PR, not replacing them.  I think we definitely should have some way to dynamically load themes.

A use-case I'm considering is a 3rd party widget that provides its own styling, and doesn't know if it will be run in a dark or a light-themed notebook.  Using less to have conditionals based on luminosity works if the less is dynamically compiled, but won't if the less is precompiled in the plugin, right?

**Comment by Carreau** [comment]
@AFJay I don't know what koala is, but if you have a nice way to create theme that inherit from IPtyhon .less that would be great. If an example script could be part of IPython and explain how to do themeing easily, that would be great. 

@jasongrout Sure, I just don't want people to start planning too far in advance, dynamically loading theme is not to hard with requirejs. The tricky bit is as usual to put the themes in the right location and having a way to list them. 

Good point about custom widgets that ship their own css, though I already unsure on how widget would ship css. the `.light` or `.dark` class on body would then make sens.

**Comment by AFJay** [comment]
K I'll start working on doing the documentation. I'm still figuring out how to do live reload as you update the css but that shouldn't be too hard. For theme switching I'll adopt

**Comment by Carreau** [comment]
One step at a time, the code on my blog is old and proof of concept. 
Live-reload might be hard the way this work now, but we can try gulp-livereload. Don't worry on that. 
I found [koala](http://koala-app.com/), I would much prefer not have a gui tool, so that we can test css-generation on things like travis-ci, so that you are sure themes are up to date. And I would like to avoid yet another tool. 

Don't wait to be done before opening a PR, it's easier to open a PR early and iterate on it. We don't want people to go completely the wrong way immediately.

**Comment by Carreau** [comment]
So roughly, I looked a gulp a bit, I acchieve something like [this](https://github.com/jupyter/notebook/compare/master...Carreau:theme) which allow you to build IPython theme in a normal way: 
```
gulp css
```

though if you have a `red.less` file and a `blue.less` file in current working directory, you can do a 
```
gulp css --theme blue.less
```
or 
```
gulp css --theme red.less
```
And it will compile a blue (or red) theme.

It stays far from perfect as it probably don't catch errors of un exiting theme, do not allow you to decide of a destination folder. Does not infer the theme filename from the `<xxx>.less` file. 
It should also most likely be updated to get as a parameter the name of the codemirror theme and concatenate its css with the theme.

Also as I concat the files as a hack the sourcemaps are probably wrong.
Though that the kind a way of building themes that I thing we should aim for.

**Comment by AFJay** [comment]
I feel that this is the easiest way to get people developing themes the right way. In koala you can set it to use an external compiler so we can still use less/lessc (if there's a compatibility issue). For the purposes of building the themes from the developer environment we could just have gulp compile the .less files like it's done now. As long as people are using the original .less files as a reference I see no trouble with making the corresponding themes maintainable. However, the problem with using gulp as the tool to compile .less files from a theme designer stand point is that you need to have the whole iPython build environment. Where as using koala or another self contained option is just a matter of installing it setting it up and using the files that are already present in a default notebook install. 

I'm pretty new to gulp but I found this on stack exchange. http://stackoverflow.com/questions/30218442/how-to-detect-css-theme-and-work-only-with-this-theme . I was thinking we could do something like that.

**Comment by Carreau** [comment]
Fair point for people that develop themes without wanting the full IPython dev env. Though they would still need to get the sources of IPython, and lessc to build the themes. So it's just a matter of wether then n+1 software need to build themes is gulp or koala. 

The SO link seem useful.

**Comment by AFJay** [comment]
The .less files are included in the install files. So you don't need the ipython sources to develop a theme if you use an outside compiler. Which is good because I suspect that a lot of people who want to develop themes don't necessarily want to install the latest build. They'd probably want to install iPython using their package manager or whatever. The downside is that people will submit themes to the repo based on older versions of iPython but so long as they include the .less files along with what version they came from it shouldn't take too much to update them if something is broken.

**Comment by Carreau** [comment]
> The .less files are included in the install files

In the wheel too ? I thought they were included only in sdist.

**Comment by AFJay** [comment]
I found them here: /usr/share/ipython/notebook/static/notebook/less/ . I'm not sure if this has changed with latter releases but it wouldn't be a bad idea to include them.

**Comment by Carreau** [comment]
Most people that will use wheel won't really care about these file. It's like distributing `.c` file with a binary. It's also relatively  difficult to know what distribution like Debian will do with less file. So it is hard to make assumptions on wether the file will be present when you install IPython with package manager X.

**Comment by stbinan** [comment]
I create my own Jupyter notebook theme by Stylish add-on, which is available from Firefox and Chrome. I also add syntax customizing options, though you need to customize every syntax by yourself.

In my opinion, white theme is really harmful to eye and sight. Wish some people also benefit from this work.
URL: https://userstyles.org/styles/98208/jupyter-notebook-dark-originally-from-ipython

Screenshot:
![Uploading Screenshot_2015-06-12_09-39-11.png…]()

**Comment by nsonnad** [comment]
The reason I use a templating engine for [my themes](https://github.com/nsonnad/base16-ipython-notebook) is that [base16-builder](https://github.com/chriskempson/base16-builder) already has a ton of really great color schemes defined as YAML. I agree that copy Jupyter/IPython CSS and applying these colors is kind of silly. However, we are doing a lot of extra work if we throw out those base16 color schemes; they are very diverse and well done.

The issue is that with less and most CSS preprocessors there is not a way to dynamically set variables from outside. Hence we need to pass them through a templating engine. Perhaps it would be best to pass only a [`variables.less`](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/less/variables.less) through the template, creating one for each theme? Otherwise we will have to modify less so that it is able to have variables overridden from outside.

**Comment by AFJay** [comment]
I'm not sure that will work. I can't come up with a solution I'm happy with. The problem is that all of the tools being used to manage jupyter's css are designed for a web server environment. However, the process now is to build the css when the package is built. We might want to just create a way to manage css version compatibility and leave the maintenance up to the community.

**Comment by nsonnad** [comment]
I've added a PR demonstrating my approach. It's not finalized but I think this could be a good first step https://github.com/jupyter/notebook/pull/179

**Comment by watsonix** [comment]
The theme linked to by @stbinan above is great, except it doesn't handle matplotlib so well ... can't read the axes of my plots!

**Comment by Carreau** [comment]
you can set img.background to white in css. should help

**Comment by JamiesHQ** [comment]
@AFJay : We're doing some housekeeping here in our issue log and I see this one has been open for a couple years now. I thought I'd circle back with you to see if your issue was resolved (which means we can close it) or if there is more we need to do on it. Thanks!

**Comment by AFJay** [comment]
I'm not sure if it ever was resolved.

**Comment by gnestor** [comment]
Since 2015, [jupyter-themes](https://github.com/dunovank/jupyter-themes) has emerged and it has proven to be a maintainable way to develop and share themes for the classic notebook. JupyterLab has its own solution of [theme extensions](https://github.com/jupyterlab/jupyterlab/blob/master/docs/extensions_dev.md#themes).
