### ISSUE TITLE
Centralize Notebook "Development Installation" docs?

### ISSUE THREAD

**Issue by mgeier** [jupyter/notebook#1193]
There was already some related activity (#590, #1039, #1134, #754), but I personally still had a hard time to find the right information about how to make a development installation of the Jupyter notebook.

I found (partial) documentation in three different places, with partly divergent instructions:

https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.md
https://github.com/jupyter/notebook/blob/master/README.md#development-installation-quickstart
https://jupyter-notebook.readthedocs.org/en/latest/development_js.html

The last link (which I also found last), actually helped me to successfully create a development installation on my computer, the others did more harm than good.

I'd suggest to collect all the information in a single place (e.g. `CONTRIBUTING.rst`).
This could then be linked to in the `README.md` and it could be included (with the `.. include::` directive) into the online docs (replacing what's there now).

Would this be a good idea?
Or am I way off?

If there is some interest, I'd be willing to make a PR with my suggested changes, but I'd need some help determining which of the instructions are actually still accurate and which aren't.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @mgeier!

I think the best approach would be to move [the information](https://jupyter-notebook.readthedocs.org/en/latest/development_js.html) about the development set up for the JavaScript components into the the steps in the [code contribution guide](http://jupyter.readthedocs.org/en/latest/contrib_guide_code.html). The information in the ReadTheDocs page is probably the most relevant but should be updated to include some new changes we made via the introduction of Webpack. See #1047.

Calling in @willingc, who is our fairy godmother of documentation, for her thoughts.

**Comment by willingc** [comment]
@mgeier Welcome! Nice to see the friendly face of  the ``nbsphinx`` project here. I'm sorry for the development installation goosechase. You are absolutely correct that we need to simplify and centralize the development installation. Thanks for your offer to help with a PR, and we will take you up on your offer.

@captainsafia Thanks for giving me the heads up. Since you are more familiar with the Javascript process and plans, would you mind guiding @mgeier on any questions and/or insights for upcoming changes?

Here's my current thinking (though I am open to other suggestions) about what would be helpful.
First, as an aside, @mgeier, there are two repos that we'll be working with jupyter/jupyter and jupyter/notebook. Safia, I would like to view the jupyter/jupyter repo as a general umbrella for all Project Jupyter development, and jupyter/notebook repo as docs specific to the Notebook.

I'm leaning toward keeping general code contribution info in the guide that Safia mentions in jupyter/jupyter. We can add general JS tips for setting up a dev environment there (my assumption here is that these tips would be helpful whether working on the notebook, widgets, extensions, or future projects. 

In the jupyter/notebook repo, let's put notebook development installation specifics to get up and running. This document would be the definitive "how to install a dev environment for the notebook". After this is done, we can link the CONTRIBUTORS doc and README, as well as the code contribution guide in jupyter/jupyter, to it.

As a work plan,  we can divide and conquer:

*Changes for jupyter/notebook repo*
- [ ] Rename Development Documentation to Contributor Documentation
- [ ] Clean up the [Development Intro Index](https://github.com/jupyter/notebook/blob/master/docs/source/development_intro.rst) which leads to a confusing repetition of topics in the sidebar
- [ ] Expand and edit the [Installing JS machinery](https://github.com/jupyter/notebook/blob/master/docs/source/development_js.rst) so it has the detailed instructions of setting up a development environment for the Notebook.
- [ ] Update CONTRIBUTOR and README

*Changes for jupyter/jupyter repo*
- [ ] Add tips on general JS development
- [ ] We're probably at the point where we can begin linking to the Contributor Documentation in individual repos. Perhaps a one page doc that links out to the Contributor Documentation sections of each project's docs.

Thoughts? Comments? :cookie: :cookie:

**Comment by mgeier** [comment]
Thanks for the positive response!

I agree with the work items but I'll only be working on the jupyter/notebook repo.

I'll come back to you with some questions in the next few days ...

**Comment by willingc** [comment]
@mgeier Great!

> I agree with the work items but I'll only be working on the jupyter/notebook repo.

Sounds good. I would appreciate your help, as someone who recently did this, with:

> - [ ] Expand and edit the Installing JS machinery so it has the detailed instructions of setting up a development environment for the Notebook.

Feel free to ask questions as they come up. @captainsafia is a great resource for JS and the notebook.

**Comment by mgeier** [comment]
OK, here comes a first bunch of questions. I've numbered them for easier answering ...

1. In the current docs I found 3 links about general guidelines for contributing. Which of the following should I use?

   * https://github.com/ipython/ipython/blob/master/CONTRIBUTING.md
   * http://jupyter.readthedocs.org/en/latest/contrib_guide_code.html
   * http://jupyter.readthedocs.org/#contributor-documentation

1. Is `python setup.py js css` necessary *initially* when running `pip install -e .`?
   If yes, before or after?

1. Is the Debian/Ubuntu package `python-dev`/`python3-dev` necessary?
    IOW, does anything have to be compiled?
    BTW, should we suggest to install `python3-tornado` and `python3-jinja2` with the package manager (instead of implicitly with pip)?

1. The FreeBSD instructions seem outdated (using Python 2.7 and `requirements.txt` which doesn't seem to exist anymore.
   Also, the instructions mostly just show how to use a virtualenv, which doesn't seem FreeBSD-specific to me.
   I don't know anything about FreeBSD, who can update the instructions?
   Or shall we just drop them?

1. Should `python setup.py jsdeps` be documented?
   AFAICT, this is always called automatically, right?
   What about the `-f` flag? Shall we document that?
   Apart from that, the command raises an error if I try to use it:

   ```
   $ python3 setup.py jsdeps
   Traceback (most recent call last):
     File "setup.py", line 199, in <module>
       main()
     File "setup.py", line 196, in main
       setup(**setup_args)
     File "/usr/lib/python3.5/distutils/core.py", line 134, in setup
       ok = dist.parse_command_line()
     File "/usr/lib/python3.5/distutils/dist.py", line 472, in parse_command_line
       args = self._parse_command_opts(parser, args)
     File "/usr/lib/python3.5/distutils/dist.py", line 544, in _parse_command_opts
       raise DistutilsClassError(msg % cmd_class)
   distutils.errors.DistutilsClassError: command class <class 'setupbase.JavascriptDependencies'> must provide 'user_options' attribute (a list of tuples)
   ```

1. Is building the docs documented somewhere?

1. How is `make.bat` supposed to be used?
   Wouldn't it be better to use a platform-independent `python setup.py build_sphinx`?
   This is probably worth a separate issue ...

**Comment by takluyver** [comment]
1. I don't think those are mutually exclusive. The first is supposed to have a short summary, the third is a more detailed set of contribution docs, and the second is part of the third.

2. I believe that `pip install -e .` should run the css & js builds automatically, so `python setup.py css js` is only needed later on when you've updated master or changed the code yourself.

3. The -dev packages are needed if installing pyzmq from pip, which will have to build it from source. In general, I probably wouldn't recommend people get deps from apt, because they may be out of date (especially for users on Ubuntu 14.04), and the instructions have to change slightly between Python 3 and Legacy Python.

4. The FreeBSD instructions probably are out of date. I think a FreeBSD user stopped by at one point during the big refactoring and added them. I'd prefer to try to make as much of the instructions as possible platform-neutral.

5. I think that command should be automatically called when necessary, so let's leave it undocumented for now.

6. Not sure. @willingc , any description of how to build the docs?

7. When you set up Sphinx docs, it creates `Makefile` for Unix platforms and `make.bat` for Windows platforms. We ~always build the docs from Unix, so I've never looked into `make.bat`, but I assume Windows users who are familiar with Sphinx will know what to do, so we leave it in place. Sphinx does already provide a cross-platform `sphinx-build` command, but I don't know what options it needs off the top of my head. I don't think we should start trying to build custom solutions here - if you want to improve that infrastructure, that's something to do in Sphinx.

**Comment by willingc** [comment]
@mgeier Here are a few more points. Thanks @takluyver for the responses :smile:

1. I think all of the links that you mentioned could be used. It would depend on the context of how you are using them. The first is the IPython Contributor guidelines which are still used by IPython and in many cases the culture for Jupyter as well. The second is the general information about contributing source code to a Jupyter project; while the third gives information on the many ways that individuals may contribute to the projects.

2. I believe @takluyver is correct that you do not technically have to run ``python setup.py js css`` after the initial installation. It is required to be used when the JS/CSS/LESS files are changed.

3. Agree with @takluyver here. In general I would recommend pip (or conda) over using the OS package managers since many of the OS package managers use dated versions. Please use pip for tornado and jinja2.

4. I think the FreeBSD should be removed from the README. I'm ok with it being in the developer documentation though I wonder if it is really necessary.

5. Let's not mention or if you feeling strongly that there is a reason to mention, I'm cool with a sentence on it that mentions it is automatically called.

6. The general contribution guide has a section that explains [how to contribute to the docs](https://jupyter.readthedocs.org/en/latest/contrib_guide_docs.html). For now, I would just refer people to there.

7. I would prefer to keep it simple on this. For now, let's just refer to the general contribution guide for docs for most cases (people adding content) that will be sufficient. 

Thanks for all the thoughtful questions. Feel free when you are ready to open a WIP PR. I imagine that there will be more specific questions :smile:

**Comment by mgeier** [comment]
@takluyver, @willingc Thanks for your responses!

I've created a PR: #1208.

1. I used only http://jupyter.readthedocs.org/#contributor-documentation, because even if it doesn't contain all the relevant information from the other two yet, it definitely should. And I'm trying to simplify things here ...
Also, [Jupyter on your system](http://jupyter.readthedocs.org/en/latest/system.html) should not be part of the "contributor documentation". I don't have the energy right now to create issues for that, let alone PRs.

2. OK, that's good to know. I moved it from the initial build steps to another section.

3. I followed your suggestion to use pip to install the dependencies, but I mentioned the OS packages for people like me who prefer to install OS packages for those.

4. I removed the FreeBSD stuff

5. I removed the "jsdeps" stuff

6. I added step-by-step instructions and linked to the Project Jupyter docs

7. I just clumsily mentioned `make.bat`, since I'm not a Windows user either

@takluyver said about `python setup.py build_sphinx`:

> I don't think we should start trying to build custom solutions here - if you want to improve that infrastructure, that's something to do in Sphinx.

I'm not at all suggesting a custom solution, on the contrary!  That command should run out-of-the-box with `setuptools` if Sphinx is installed. This would automatically make everything cross platform and would actually be much simpler than handling the bulky `Makefile`. But since you are a `setuptools` hater I guess this will never happen, right?
Or shall I make an Issue for that?

Just as a side note: I think it was a ridiculous choice of the Sphinx people to force the ugly `Makefile` and `make.bat` onto its users instead of providing reasonable command line options to `sphinx-build`. Actually `sphinx-build` can nowadays be quite easily used, see http://nbsphinx.readthedocs.org/en/latest/usage.html#Running-Sphinx.
But `setuptools` would make this even easier!

**Comment by takluyver** [comment]
I don't want to involve the packaging machinery in building docs.

**Comment by willingc** [comment]
@takluyver I agree.

**Comment by mgeier** [comment]
Coming back to a point made by @takluyver:

> In general, I probably wouldn't recommend people get deps from apt, because they may be out of date (especially for users on Ubuntu 14.04),

I just installed Ubuntu 14.04.4 on VirtualBox and installed Python3 *without* installing the `python3-dev` package.
Then I did

    sudo apt-get install python3-zmq python3-tornado python3-jinja2
    sudo apt-get install nodejs-legacy npm

... and afterwards:

```
pip install setuptools pip --upgrade --user
git clone https://github.com/jupyter/notebook
cd notebook
pip install -e . --user
```

It worked perfectly without errors, I could start and successfully use the notebook with IPython3.

I ran the `nosetests`, which produced a lot of garbage-y looking output but in the end said:

```
Ran 194 tests in 18.767s

OK (SKIP=7)
```

So I guess there are no problems after all?

> and the instructions have to change slightly between Python 3 and Legacy Python.

You mean that the packages are called `python3-tornado` instead of `python-tornado`?

I think we should stop advertising Python 2.
Sure, Python 2 should still be *supported*, just not documented.
I'm sure people who *have* to use Python 2 will know that they'll have to use `python-tornado`.

In the documentation (and this regards all things that I write documentation for, not only the Jupyter Notebook), I try as best as I can to follow best practices for each of the mentioned OSs.
And in case of Debian-based systems I highly recommend to install PyZMQ and Tornado from their `deb` packages instead compiling them with `pip`.
In case of Jinja2 it doesn't matter, because nothing seems to be compiled there.

**Comment by takluyver** [comment]
> Ubuntu 14.04 ... It worked perfectly without errors

I'm pleased it does currently, but that may not always be the case, and we may want to use dependencies that are not packaged in Ubuntu. So I think it's easiest to install dependencies with pip/conda where possible.

> You mean that the packages are called python3-tornado instead of python-tornado?
> I think we should stop advertising Python 2.

Yep, that's what I mean. I'm fine with the development instructions pointing people to Python 3, but note that on Ubuntu (and many Linux distros) you may need to use `pip3` rather than `pip` to install the notebook itself.

**Comment by mgeier** [comment]
@takluyver Most of this isn't urgent anymore, see https://github.com/jupyter/notebook/pull/1208#issuecomment-196850314

I still would like to explain my view of things ... probably this can be changed at some point in the "normal" installation instructions ...

> I'm pleased it does currently, but that may not always be the case

Don't be so pessimistic!

> we may want to use dependencies that are not packaged in Ubuntu

Sure, not a problem.
Hasn't been a problem now, won't be in the future.

Actually, as far as I've learned until now, the only packages I would suggest to install with the package manager are `python3-zmq` and `python3-tornado`.
That's because those have to be compiled locally otherwise.

> I think it's easiest to install dependencies with pip/conda where possible

Sure, except for `python3-zmq` and `python3-tornado`.

And I'm talking (and have talked) only about a plain old Debian/Ubuntu system using the OS's Python packages.

Conda might a different story, I don't know if those packages have to be compiled there (I tried if for Windows, where I didn't see any compilation and I didn't have to install any development stuff, which is good).

**Comment by mgeier** [comment]
Oh, and I forgot:

> note that on Ubuntu (and many Linux distros) you may need to use `pip3` rather than `pip` to install the notebook itself

I know, and that's unfortunate.

It would be nice if all systems had `python3` and `pip3` executables, does Anaconda/Python3.x have them?
A Python3 `venv` does have them (in addition to `python` and `pip`), so there it would work if all instructions would only use the 3-annotated binaries.

On the long run it would probably be better to use `python3` and `pip3` exclusively in the documentation, right?

**Comment by willingc** [comment]
@mgeier Thanks for your enthusiasm and recent changes. I want to be cautious about focusing on the balance between simplification and respect for developer uses cases that may not be Python 3 centric and/or Linux centric.

I would like to make sure we keep the distinction between end user documentation and contributor documentation clear since, in my experience on the project, users and contributors have different needs and goals.

@takluyver, after working on this project for years, has a unique perspective for the breadth of ways the notebook and other Project Jupyter projects work together. I know that I, personally, take pause when he comments on things. We don't always entirely agree but I respect his viewpoint. More often than not, Jupyter benefits since merging our ideas together usually improves the end result.

So, let's keep iterating here :smiley:

As an FYI re: pip3, the recent versions of pip eliminate the need for using pip3.

**Comment by takluyver** [comment]
> It would be nice if all systems had python3 and pip3 executables, does Anaconda/Python3.x have them?

In my installation, it has a `python3` symlink but not `pip3`. 

> As an FYI re: pip3, the recent versions of pip eliminate the need for using pip3.

Do you mean using `python3 -m pip`? I'm pretty sure that the `pip` command in Debian-based distros (Ubuntu, Mint, etc.) will continue to be Python 2 pip for some time yet.

**Comment by mgeier** [comment]
I'm trying to summarize the options mentioned above:

1. `pip install ...`: should work on all Python3-only systems (including `venv`s), but will likely install the wrong thing on mixed Python2/3 systems.

1. `pip3 install ...`: should work on many systems, but not on Anaconda. Python2 users just have to drop the "3".

1. `python3 -m pip install ...`: should work on all systems. Python2 users just have to drop the "3".

Did I miss anything?

The more I think about it, the more I like the last option. It looks a bit awkward at first, but I think I can get over that.

It has several advantages:

* It is a clear statement that Python 3 should be used
* It is easy to experiment with different Python version, e.g. `python3.4` vs `python3.5`
* Many commands in the docs will look more consistent when using `python3 -m pip ...` and `python3 setup.py ...`

The same thing could also be used for `python3 -m venv`, but this'll have to be changed to `python -m virtualenv` for Python 2.

**Comment by minrk** [comment]
`python3 -m pip` is the least ambiguous, and what I use when I have a bunch of Pythons lying around (more generally `/path/to/python -m pip`). It's not clear to me what's best for newcomers, though. My personal preference is probably for using `pip install` everywhere, and including a note at the top, explaining that in some cases `pip` may not point to the Python you want, in which case `/path/to/python -m pip` can be used to ensure packages are installed with a particular Python. I'm not sure if that's too verbose for people, though.

Re: FreeBSD instructions, I do think they should be removed, and I also think that we shouldn't include instructions for setting up a virtualenv.

**Comment by mgeier** [comment]
For future reference: in this issue a few interesting points were discussed which were not part of #1208 (which closed this issue). I'm trying to summarize them here:

@willingc mentioned a few things in https://github.com/jupyter/notebook/issues/1193#issuecomment-195887000:

> *Changes for jupyter/notebook repo*
>
> * [ ] Update [...] README
>
> *Changes for jupyter/jupyter repo*
>
> * [ ] Add tips on general JS development
> * [ ] We're probably at the point where we can begin linking to the Contributor Documentation in individual repos. Perhaps a one page doc that links out to the Contributor Documentation sections of each project's docs.

In https://github.com/jupyter/notebook/issues/1193#issuecomment-196488491, I mentioned that http://jupyter.readthedocs.org/#contributor-documentation should include the information from https://github.com/ipython/ipython/blob/master/CONTRIBUTING.md (if it doesn't already).
There should probably also be a link from the latter to the former.

I also mentioned that [Jupyter on your system](http://jupyter.readthedocs.org/en/latest/system.html) should not be part of the "contributor documentation".

In https://github.com/jupyter/notebook/issues/1193#issuecomment-196857596, I suggested to suggest this in the general Notebook installation docs (or even in the general Jupyter installation docs?):

    sudo apt-get install python3-zmq python3-tornado

Then there was a very interesting discussion about making the `pip` commands more consistent, e.g.: https://github.com/jupyter/notebook/issues/1193#issuecomment-198765187

I think using `python3 -m pip install` everywhere would be good.
In which context/form should this be discussed further?

Finally, I'd like to continue the discussion about `python3 setup.py build_sphinx`:

I said in https://github.com/jupyter/notebook/issues/1193#issuecomment-196488491:

> I'm not at all suggesting a custom solution, on the contrary!  That command should run out-of-the-box with `setuptools` if Sphinx is installed. This would automatically make everything cross platform and would actually be much simpler than handling the bulky `Makefile`. But since you are a `setuptools` hater I guess this will never happen, right?

@takluyver said:

> I don't want to involve the packaging machinery in building docs.

@willingc said:

> I agree.

But why?
Are there any practical disadvantages?

BTW, in the meantime I found out that this can even be done without using `setuptools` using [sphinx.setup_command.BuildDoc](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/setup_command.py). `setuptools` would just do this automatically.
