### ISSUE TITLE
Make "toggle line number" more visible.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1244]
An important feature that people are missing from the notebook is having line numbers in cells.

Said during jupyter Days Boston education panel, with audible approval from the room.

Shouting "Press Esc and then L" was then followed by the speaker trying and a round of applause. 

This make me believe that a button to toggle that would be (highly ?) appreciated. 

Ping @ellisonbg

**Comment by ellisonbg** [comment]
For now, I think the toolbar would be the appropriate place for this in the
current notebook.

Beyond that, I am going to start having @cameronoelsen start to work on
some new UI ideas for cells that address better output collapse/scroll,
input hiding/show, etc. I think per cell actions like this should be more
closely associated with cells - rather than up on the toolbar. The main
question is how to represent that UI without putting the same UI on every
cell - that would be too much repetition. I have some ideas, but will need
to work with Cameron on them from the visual/interaction perspective. But
the line numbers would go well with these other actions.



On Tue, Mar 22, 2016 at 12:00 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> An important feature that people are missing from the notebook is having
> line numbers in cells.
>
> Said during jupyter Days Boston education panel, with audible approval
> from the room.
>
> Shouting "Press Esc and then L" was then followed by the speaker trying
> and a round of applause.
>
> This make me believe that a button to toggle that would be (highly ?)
> appreciated.
>
> Ping @ellisonbg <https://github.com/ellisonbg>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1244>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
Now that we have the frontend config, a lot of these options can be set and saved via UI. The text editor includes a basic experiment of persisting CodeMirror config, and options in the menus. The two basics it already includes are CodeMirror keybindings and line numbers.

**Comment by Carreau** [comment]
If we persist, we then **likely** want to have the switch affect all cells.

**Comment by minrk** [comment]
I imagine that's what ~everyone would want, anyway.

**Comment by Carreau** [comment]
@secant, we can try to have a look at this one if you want to give it a shot and learn some javascript.

**Comment by juhasch** [comment]
You can take a look at this [toggle_all_line_numbers](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/toggle_all_line_numbers) extension, which basically does what you want. You can also assign a hotkey that is stored in the frontend config.

It should not be very hard to add another config parameter to make the line number display persistent.

**Comment by Carreau** [comment]
Thanks @juhasch I was planning on searching in IPython-contrib, but you beat me to it !
We'll strat from that on update to use newer APIs thanks !.

**Comment by DSLituiev** [comment]
I did not exactly get the story in the first post, but I have hard time trying myself to toggle the line numbers. On MacOSX10.10.5, GoogleChrome,It works with some infinitesimal probability 99% it does not. 
Esc followed by Cmd + capital L, Enter(where in the cell one is supposed to hit it, so that it does not mess the code?) followed by Cmd + capital L, the same with small l, do not work. Some of these combinations lead to the address line (maybe it is Chrome specific). 

Definitely would appreciate some more transparent way to switch it on.

**Comment by Carreau** [comment]
> Esc

No, you do not need to press Esc everytime. `Esc` is just to go to command mode.

> Cmd

You do not need to press command either. 

> capital L,

The shortcut is lower case L. Not upper case. It would be upper case you would explicitly see `Shift-L` as the shortcut. 

So go to command mode, like when the border of the cells are blue, and just press `l` just once, no modifiers. 

I'm not sure where you had the idea to Press Esc, and Cmd, and Shift, the shortcut list seem pretty explicit to me as is does explicitly show what key you need to press. 
![screen shot 2016-05-23 at 14 47 37](https://cloud.githubusercontent.com/assets/335567/15485656/63f53fdc-20f5-11e6-9cf1-98e9e68f4437.png)

**Comment by DSLituiev** [comment]
thank you @Carreau, it works. I just followed instruction, which reads a bit ambiguous. It says: `Command Mode (press Esc to enable) Edit Mode (press Enter to enable)`. The short cut I need looks to be in continuation of the `Edit Mode (press Enter to enable)` paragraph, this is why I was confused. Shift is because it shows a capital `L`. I see there is no Cmd (it belonged to the upper 'save and checkpoint').

**Comment by takluyver** [comment]
It seems to be a recurring problem with our keyboard shortcuts help - people assume that the modifier keys from one shortcut also apply to the shortcuts below. I know it's unusual to use unmodified letter keys as shortcuts (except for games), but I wonder if we can redesign the list to make that clearer - maybe by putting all of the modified shortcuts at the end of the section?

**Comment by Carreau** [comment]
> It seems to be a recurring problem with our keyboard shortcuts help - people assume that the modifier keys from one shortcut also apply to the shortcuts below. I know it's unusual to use unmodified letter keys as shortcuts (except for games), but I wonder if we can redesign the list to make that clearer - maybe by putting all of the modified shortcuts at the end of the section?

I think that would be solved once the shortcuts are on the right side of the menu.

**Comment by gnestor** [comment]
This was implemented by https://github.com/jupyter/notebook/pull/1676.

**Comment by jzf2101** [comment]
Why is this still opened if it was merged in #1676 ?

**Comment by gnestor** [comment]
> I think that would be solved once the shortcuts are on the right side of the menus.

Closing this in favor of https://github.com/jupyter/notebook/issues/2759
