### ISSUE TITLE
I meet a question on Emmbeding the notebook in my website!

### ISSUE THREAD

**Issue by bwangel23** [jupyter/notebook#1256]
My website is 127.0.0.1:8000,  the jupyter port is 8888. I put the ipython notebook `http://127.0.0.1:8888/notebooks/2/2.ipynb` in the page `http://127.0.0.1:8000/data_exploration/2/` by using iframe.

I changed my jupyter settings follow this doc (embedding-the-notebook-in-another-website)[https://github.com/jupyter/notebook/blob/master/docs/source/public_server.rst#embedding-the-notebook-in-another-website].

But on the chrome and firefox.I still cann't see the ipython notebook in my website.

And this is my jupyter settings:
```python
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'http://localhost:8888' 'http://localhost:8000';",
    }
}
```

This is the error page screenshot:
My website is 127.0.0.1:8000,  the jupyter port is 8888. I put the ipython notebook `http://127.0.0.1:8888/notebooks/2/2.ipynb` in the page `http://127.0.0.1:8000/data_exploration/2/` by using iframe.

I changed my jupyter settings follow this doc (embedding-the-notebook-in-another-website)[https://github.com/jupyter/notebook/blob/master/docs/source/public_server.rst#embedding-the-notebook-in-another-website].

But on the chrome and firefox.I still cann't see the ipython notebook in my website.

And this is my jupyter settings:
```python
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'http://localhost:8888' 'http://localhost:8000';",
    }
}
```

This is the error page screenshot:

![chrome error page](https://cloud.githubusercontent.com/assets/11701497/14008949/df2a6dfc-f1c1-11e5-8ffa-e74204e03820.jpg)
![firefox error page](https://cloud.githubusercontent.com/assets/11701497/14008954/f1e7c80e-f1c1-11e5-82b9-68997f310d42.jpg)

**Comment by captainsafia** [comment]
What happens when you change the configuration to the one below?

```
c.NotebookApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors 'http://localhost:8000' 'self'",
    }
}
```

**Comment by dvigneshwer** [comment]
@captainsafia  I tried the above configuration and followed the changes in https://github.com/jupyter/notebook/blob/master/docs/source/public_server.rst#embedding-the-notebook-in-another-website

**Inspect element output :**
![image](https://cloud.githubusercontent.com/assets/5075497/18266339/d79f590a-7437-11e6-9cc4-0973de4dfa64.png)

**Rendered index.html page**
![image](https://cloud.githubusercontent.com/assets/5075497/18266078/7da0aff4-7436-11e6-89b4-182ac3bc0c68.png)

**Changes in jupyter_notebook_config.py** 
![image](https://cloud.githubusercontent.com/assets/5075497/18266121/b3bf4fbe-7436-11e6-860b-5f6f6e53aa4e.png)

Notebook server  is on 8888 and my local server is on 8000

There is a ~/.jupyter/custom/custom.js file which needs to made some changes but I did not find this file in the location mentioned in the documentation.

**Code change :**
![image](https://cloud.githubusercontent.com/assets/5075497/18266174/0550c3a8-7437-11e6-8443-c43fe590d395.png)

**Folder path:**
![image](https://cloud.githubusercontent.com/assets/5075497/18266188/1c63fad8-7437-11e6-8bd0-dac26818f1f7.png)

![image](https://cloud.githubusercontent.com/assets/5075497/18266201/362efdfa-7437-11e6-8dc6-07afeb9c7860.png)

I made the above js script changes in the location /usr/local/lib/python2.7/dist-packages/notebook/static/custom/custom.js which I got from locate custom.js

Is it not working because of the js changes not made properly or refused to disply error ??

**Comment by dvigneshwer** [comment]
My complete code implementation I have uploaded in https://github.com/dvigneshwer/Spawning_jupyter_notebook_webapp and also have mentioned all the problems I am facing.

**Comment by dvigneshwer** [comment]
I tried without http:// also it does not work.

**Comment by dvigneshwer** [comment]
Solved the problem with this configuration.

@captainsafia @bwangel23 check https://github.com/jupyter/notebook/issues/1745#issuecomment-246564901
