### ISSUE TITLE
Side by side cells

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#1283]
Hi,

I did not find any open issue on this topic, but perhaps I missed it. What about offering the ability to split a cell (_à la_ `screen` / `vim` / `emacs` / whichever tiled program), at least two cells side by side?

My typical use case, for which I looked at this issue, is to compare outcomes from two different modules. Having a side by side view in a Jupyter notebook would be easier and more user friendly than having to deal with two different notebooks and rely on my window manager to put them side by side (and scroll synchronously manually).

Though, this may be tricky to implement in the UI, and it may be better suited for an extension.

Thanks

**Comment by Carreau** [comment]
This will **likely** not be in core and will require an extension. 
Unless we allow to extract cell in a separate view in Jupyterlab. Which I'm unsure of. 
Marking as 5.0, but without much hope.

**Comment by noleto** [comment]
for folks interested with side-by-side view, there is an extension (Split Cell) providing this features https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/splitcell/readme.html

**Comment by dsblank** [comment]
There is also Calysto Cell Tools that can do tabbed input/output or
side-by-side input/output:

https://github.com/Calysto/notebook-extensions/blob/master/calysto/cell-tools/cell-tools.png

Install notes here:

https://github.com/Calysto/notebook-extensions

-Doug

**Comment by flacle** [comment]
> Hi,
> 
> I did not find any open issue on this topic, but perhaps I missed it. What about offering the ability to split a cell (_à la_ `screen` / `vim` / `emacs` / whichever tiled program), at least two cells side by side?
> 
> My typical use case, for which I looked at this issue, is to compare outcomes from two different modules. Having a side by side view in a Jupyter notebook would be easier and more user friendly than having to deal with two different notebooks and rely on my window manager to put them side by side (and scroll synchronously manually).
> 
> Though, this may be tricky to implement in the UI, and it may be better suited for an extension.
> 
> Thanks

Hi, chiming in. Something like a side-by-side split where markdown cells are linked/anchored to lines within a code cell. Imagine markdown cells on the left in a view and code cells on the right in another view. When scrolling in the markdown cells, it also scrolls the code cell view to ensure that the lines of code that are anchored remain visible. Similarly, when scrolling within the code cells, it also scrolls the markdown view to ensure that the relevant text that is anchored to the code remains visible. Like the OP, I often find myself scrolling up and down, searching for a reference to something somewhere else in the document that is related to the current code block. The UI idea is similar to this comparison view of Bitbucket for code revisions, see: https://youtu.be/9K7L0QgcrO0?t=53. The split view would be an optional feature, with the anchors being optional as well.

**Comment by jtpio** [comment]
Thanks all.

Something similar to this is currently possible in JupyterLab and will be possible in the coming Notebook 7 (which inherits from JupyterLab's components). Which is also included in the latest Notebook 7 pre-release:

![image](https://user-images.githubusercontent.com/591645/195178576-af61c394-d81d-4e8c-a82b-d374fc9661cd.png)
 
Adding to the 7.0 milestone for consideration.

**Comment by torwag** [comment]
I think the proposed solution is different then what was asked for
If I understood the OP correct, he wants to get two code cells side-by-side.
Don't get me wrong I love the new side-by-side arrangement of cell and output. Much better use of the screen estate and in many cases a much cleaner look.

As for two code cells side by side, I would love to do that to have an alternative execution path. During teaching, I might want to show students what happens if you do 'a' or 'b'. Basically, the famous.... "But what would happen if we...." questions. 

Now I use two code cells underneath creating two alternative code cells. Here I need to be careful, which to execute and for the students it is difficult to see, that only one of two blocks get executed.   
Here, two code blocks side-by-side would give a much cleaner presentation. There could be more eye candy to it, like gray out the code block which was not executed, etc. 

Another use case would be a markdown and a code block side by side, which would use more screen estate particular if the code block contains small and simple code like for teaching. Notebooks tends to get very long with a lot of gap and spaces, which could be filled more elegantly, being more compact, having a feature to arrange two cells side-by-side.

**Comment by cohml** [comment]
+1 to @torwag's comment.

Rendering the entire notebook in side-to-side is one thing. But for a completely different set of use cases, it would be helpful to place just two cells side-by-side while leaving the remaining cells in the default arrangement.

**Comment by flacle** [comment]
> Another use case would be a markdown and a code block side by side, which would use more screen estate particular if the code block contains small and simple code like for teaching. Notebooks tends to get very long with a lot of gap and spaces, which could be filled more elegantly, being more compact, having a feature to arrange two cells side-by-side.

As this issue is becoming convoluted, I've created a new issue to pull out my previous suggestion into its own space #7276.
