### ISSUE TITLE
Fuzzy search in command palette

### ISSUE THREAD

**Issue by rkpatel33** [jupyter/notebook#1295]
It would be really nice to make the search/filter in the command palette fuzzy instead of normal:

![image](https://cloud.githubusercontent.com/assets/3799489/14216743/70402d0c-f818-11e5-99b2-f8ee5690def5.png)

**Comment by gnestor** [comment]
This is already implemented in JupyterLab and it's unlikely that it will be reimplemented in the classic notebook because most dev resources are devoted to JupyterLab now. Try out JupyterLab, it's almost in beta!

![image](https://user-images.githubusercontent.com/512354/34498139-1f663764-efb5-11e7-9d34-12896bd1215a.png)
