### ISSUE TITLE
Copy / paste disabled in dialogs

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/notebook#1341]
Since the introduction of copy/paste behavior for notebook cells, the `embed interactive widgets` command does not work because the 'copy' command copies the content of the current cell instead of the content of the dialog's textarea.

It would probably work if the event listeners for 'copy' and 'paste' events were added to `#notebook` instead of the global `document`.

cc @Carreau @takluyver

**Comment by SylvainCorlay** [comment]
cc @jdfreder

**Comment by jdfreder** [comment]
@SylvainCorlay you should be able to call keyboard manager "register_events" on the dialog's root element to avoid Jupyter event processing while the user has it focused.

**Comment by SylvainCorlay** [comment]
@jdfreder do you think we need to do this now in ipywidgets?

**Comment by SylvainCorlay** [comment]
It is weird that we would need to do that. Is there a reason why the notebook would register events at the global document model rather than the notebook container?

**Comment by jdfreder** [comment]
@SylvainCorlay we already do in in ipywidgets for widget areas.

Regarding the global event listener, I don't remember why it evolved to that, but there was a reason at the time.  Changing it to non-document level would likely break many edge cases.

**Comment by SylvainCorlay** [comment]
It broke between 4.2.0b1 and 5dev so something has changed.

**Comment by jdfreder** [comment]
The only reason it appears to have broke is because the event wasn't being used yet.  Now that it's being used, other users will have to go through the register_events mechanism.

**Comment by jdfreder** [comment]
Looks like the clipboard module is not entirely respecting the register_events (enable/disable state) of the keyboard manager.  I'm not sure why it still works for internal dialogs, but I think it has something to do with edit mode remaining enabled.

**Comment by ellisonbg** [comment]
Also, if I am understanding this correctly, all of this type of mess goes
away in JupyterLab with the CSS scoped keyboard shortcuts. Also putting the
keyboard events on the document, rather than just the notebook div is
required because of some subtle points about how browsers manage these
things. I think one of the issues is what happens to focus (and the
resulting keyboard events) when DOM elements are removed. We tried to get
by without doing it at the top level but were unable in both the notebook
and JupyterLab

On Tue, Apr 12, 2016 at 10:44 AM, Jonathan Frederic <
notifications@github.com> wrote:

> Reopened #1341 <https://github.com/jupyter/notebook/issues/1341>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1341#event-624534210>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
