### ISSUE TITLE
Notebook kernel not honored

### ISSUE THREAD

**Issue by BruceSherwood** [jupyter/notebook#1354]
Execute http://mybinder.org/repo/BruceSherwood/vpython-jupyter and choose a demo program. You get "Kernel not found" and "I couldn't find a kernel matching VPython. Please select a kernel:" The pull-down menu in fact lists VPython, and after choosing "VPython" the program can run. Though I first saw this problem in the Binder context, later I've seen it on some machines running locally. Presumably the notebook contains the information that the VPython kernel is needed, and it's clear that this notebook is indeed available (installing vpython also installs vpnotebook).

**Comment by Carreau** [comment]
Your notebook require a kernel named `vpythonkernel`:

```
"kernelspec": {
    "display_name": "VPython",
    "name": "vpythonkernel",
    "language": "python"
  },
```

Though your kernelspec install on binder is `vpython`:
```
"kernelspec": {
    "display_name": "VPython",
    "name": "vpython",
    "language": "python"
  },
```

Thus it is normal for the notebook to not find the kernel. Thus we pop-up the dialog, and make a "best guess" based on the language.

Make sure the kernel names match and all  should be allright. This is likely due to your local install of the kernel having a different name, so uninstalling the kernelspec and reinstalling it should work.

**Comment by BruceSherwood** [comment]
Many thanks for finding this error on my part!

**Comment by Carreau** [comment]
> Many thanks for finding this error on my part!

No problem, tell us if it works, so that we can close the issue !

**Comment by BruceSherwood** [comment]
It indeed does work. Thanks.
