### ISSUE TITLE
Change kernel without restart?

### ISSUE THREAD

**Issue by napjon** [jupyter/notebook#1365]
Hi,

As a data scientist, I sometimes switch back and forth between Python and R.
In Jupyter, every time I change to the other, It always starts a new kernel.

For example, I switch R back to Python, the kernel restart again and the Python session is lost, including all the variable that have been defined. I have to re-execute everything again from start to the point I change the kernel. Switching back to R, R session is lost, and re-execute everything again.

It's immensely useful to change simultaneously without losing kernel sessions. Is it possible to do this? Thank you.

**Comment by minrk** [comment]
A notebook has only one language associated with it, so it is generally assumed that setting the language of a notebook should only happen once or twice, not continuously. If you keep switching back and forth, that means that at any given time, much of your notebook is invalid, since the notebook itself is associated with a single language. I know there are people who would like multi-language notebooks, where the notebook can associated different cells with different languages ([Beaker](http://beakernotebook.com), which is based on Jupyter, adds this feature), but this is not the model Jupyter has at the moment. We have been discussing if/how/when we should be adding it, though.

Right now, your best bet is probably to use rpy2 and its `%%R` magic to use Python and R at the same time, or to keep separate R and Python notebooks. The nice thing about `%%R` is that it lets you easily move data back and forth between the two interpreters.

**Comment by napjon** [comment]
I see, thank you for giving me a clear direction! I've heard about Beaker but have no idea until now that they have multi-language feature. I've been using `%%R`and it's great, but a lack of autocompletion making my work less productive.

I'm going to close this issue now.

**Comment by dsblank** [comment]
I agree with @minrk that using the `%%R` is probably what you want to use.

But, to be a bit more precise on what Min said: A notebook only has one "kernel" associated with it. One could create a hybrid kernel that has two (or more) languages that the kernel could route instructions to, and keep the context. It isn't that difficult to create a custom kernel, even with IPython-inspired "magics". For example, see https://github.com/Calysto/metakernel

A Beaker-like metakernel would probably be fairly easy to implement. Can't wait for summer!

**Comment by napjon** [comment]
Thank you @dsblank, I'll try to explore that as well in more detail.

**Comment by takluyver** [comment]
And from yet another angle: we do hope to enable tab completions in cell magics at some point, but refactoring the completion machinery is a pretty big job, and once we've made it possible to provide completions for magics, magic authors will still need to actually provide them.

**Comment by napjon** [comment]
IMHO, changing the kernel on the fly is more intuitive.  I'm very excited when Jupyter added it and has spread the news to my colleagues. This means I can investigate without facing tools limitation.

If we still do it within cell magics, I see that Jupyter R kernel already has tab completion. Is it possible that we use `%load_ext` to open a new R kernel as an alternative, and get tab completion in R everytime there is an R magic?

**Comment by RoyiAvital** [comment]
Is there a way to, at least, use Python in different Kernel?
For instance, having a notebook with MATLAB Kernel yet also run Python in one cell.

I would assume running Python at any time is easy as the whole back end of the system is Python based.

**Comment by xappppp** [comment]
Is there a way even to just run two Python kernels in JN? I have a simulation need to run for hours in once cell. But I want meanwhile do my editing and calculation in other sections of my work.
