### ISSUE TITLE
Should start by default as `%matplotlib notebook`

### ISSUE THREAD

**Issue by wernight** [jupyter/notebook#1393]
`/home/jovyan/.jupyter/jupyter_notebook_config.py` could set something like `c.InteractiveShellApp.matplotlib = 'notebook'` so that by default plots in matplotlib are displayed.

Could also be set to `inline`, both are much more sane defaults than showing an error.

For some reason it seems that it's not working and may be this needs to go in another configuration.

**Comment by takluyver** [comment]
We know, see e.g. ipython/ipykernel#82. The difficulty is that setting it causes matplotlib to be loaded on startup, which we don't want to do. We were trying to work out a way to do it when matplotlib is loaded by the user, but that's fiddly, and the effort stalled.

Closing since it's an IPython kernel issue, not a notebook issue.
