### ISSUE TITLE
How to set latex version?

### ISSUE THREAD

**Issue by felipenoris** [jupyter/notebook#1422]
Hello! I'm unable to export notebooks to pdf files because nbconvert uses an outdated version of pdflatex on my system. I have another version of latex on another folder. How can I set which latex version Jupyter uses?

**Comment by takluyver** [comment]
There's a config option `PDFExporter.latex_command`. The default is `['pdflatex', '{filename}']`, but you can set it to `['path/to/any/latex', '{filename}']`. This goes in `jupyter_nbconvert_config.py` if you're using nbconvert directly, or `jupyter_notebook_config.py` if you're exporting it from the file menu in the notebook.

* [Config overview](http://jupyter.readthedocs.io/en/latest/config.html)
* [nbconvert config options](http://nbconvert.readthedocs.io/en/latest/config_options.html)

Alternatively, change the `PATH` environment variable so that the `pdflatex` it finds first is the one you want it to use.
