### ISSUE TITLE
Can't click to select tab completion option

### ISSUE THREAD

**Issue by natalieperna** [jupyter/notebook#1512]
Does the tab completion feature of Jupyter use CodeMirror's Autocomplete? If so, why doesn't clicking on an option in the Jupyter tab completion dropdown work as it does in the [CodeMirror demo](https://codemirror.net/demo/xmlcomplete.html)?

**Comment by takluyver** [comment]
I think we implemented that UI ourselves rather than using CodeMirror's autocomplete functionality, though I'm not entirely sure why. Maybe it's been added to CodeMirror since we did it. I think it's a sensible enhancement to allow clicking on options, though - I just tested and was surprised that it doesn't work. I guess I usually select them with the keyboard.

**Comment by minrk** [comment]
When we started, CodeMirror didn't have a mechanism for extending its completions that could work with our completion protocol. I don't recall specifically, but I think it might have had to do with the async-ness of it all. I believe CM 4 added enough for this to work, but we [haven't managed](https://github.com/ipython/ipython/issues/6031) to get around to integrating it.

**Comment by Carreau** [comment]
We can get inspired by nteract. [here](https://github.com/nteract/nteract/pull/318/files) and [here](https://github.com/nteract/nteract/pull/267/files).

**Comment by Carreau** [comment]
And yes, we did it ourself, because codemirror didn't had enough hooks at the time.
