### ISSUE TITLE
syntax highlighting of the new @ operator in python 3.5 broken

### ISSUE THREAD

**Issue by brunobeltran** [jupyter/notebook#1543]
It's all in the title. Not sure if this should be reported here or upstream, since I don't know what service is used for syntax highlighting. Let me know if I should bother somebody else. 

Thanks!

**Comment by takluyver** [comment]
The editor component is called Codemirror - it's [been fixed](https://github.com/codemirror/CodeMirror/commit/db62891c78fb9240ad9e4020020e7ed81a03ef6a) there, but I don't know what version of Codemirror or what version of the notebook has the fix. If you're not already using the latest release of the notebook, try upgrading. :-)

**Comment by brunobeltran** [comment]
Thanks Thomas! Still broken on the latest pip version and on master. Should I drop the latest codemirror into notebook/static/components/codemirror and PR?

**Comment by takluyver** [comment]
We don't check the JS dependendencies into the repo, they're specified in [bower.json](https://github.com/jupyter/notebook/blob/master/bower.json).

You're welcome to do a PR updating that, but it already has 5.14, and the release notes say that should have the fix for `@` : https://github.com/codemirror/CodeMirror/releases/tag/5.14.0

If you've just switched over to master, your browser might be caching some JS. An easy way to avoid that is to run the notebook server on another port, with `jupyter notebook --port 8889`.

**Comment by brunobeltran** [comment]
Works. Thanks for the pointers. Was a caching problem.
