### ISSUE TITLE
Logging configuration is reverted

### ISSUE THREAD

**Issue by duststorm** [jupyter/notebook#1551]
Is it possible to add handlers to the logging framework when the notebook server starts?
I tried something like:
`import logging

log_file = '/var/log/jupyter.log'

fh = logging.FileHandler(log_file)

logger.addHandler(fh)
# logger = logging.getLogger()  # This doesn't work, it's reset by Jupyter kernel

import traitlets.log

logger = traitlets.log.get_logger()  # ... but so is this
`
I added the above to the notebook config file, but it appears that its changes are undone by the jupyter kernel at some point.
My intention is to log to a file since I'm running jupyter as a service.

Is there a better way of doing this?

**Comment by takluyver** [comment]
Do you mean the notebook server, or the kernels? There was a fix recently for logging in IPython kernels, which should be released with ipykernel 4.4: https://github.com/ipython/ipykernel/pull/127

If it's the notebook server you want, I don't think the log destination is configurable at the moment, although you could redirect stderr at a pinch.

**Comment by duststorm** [comment]
The goal is to configure jupyter notebook to log to a file instead of only to stdout, since I'm running it as a daemon. As far as I could tell, it only allows configuration of a few logging properties, such as log_format.
I tried working around this by setting up the python logging framework from the jupyter conf file, to no avail.

Standard out redirection could be a hack to get around this, but if possible I'd rather find a hack that allows me to work with python logging directly.

**Comment by minrk** [comment]
I think stdout/err redirection is generally preferable, as it's more robust to outputs that might be written directly to stdout/stderr in exceptional circumstances (crashes, etc.) or by subprocesses, which logging doesn't capture. All daemon tools I'm familiar with support redirecting stdout/stderr to log files, and I would generally recommend using this instead of modifying Python logging destinations, as it works not just for Jupyter, but all programs.

**Comment by yuvipanda** [comment]
I agree re redirecting stdout / stderr rather than changing this via Python's logging. https://12factor.net/logs has more rationale that I very much agree with. When I run notebook daemonized (with systemd) it captures output logs automatically. What do you use to daemonize your notebook? Ideally that should support capturing stdout / stderr.

I'm going to close this issue since it's been inactive for a while. Do re-open if needed. Thanks.
