### ISSUE TITLE
Sending display_data after execute_reply

### ISSUE THREAD

**Issue by gibiansky** [jupyter/notebook#1575]
The messaging spec is not quite clear on this fine detail – can I send a display_data or execute_result message after sending an execute_reply?

It seems like the answer should, in all similar cases, be "no". As soon as a reply is sent to a request message, no future messages may that request as a "parent" -- so no more replies, no more display_data or execute_result, etc. Is this the case?

If so, it would be nice to make that explicit in the messaging spec.

**Comment by takluyver** [comment]
Because they're sent over different channels, they can arrive out of sync. It's actually the kernel status idle message that we take as the marker of the end of output, because it's sent over the iopub channel. Some frontends may still show output arriving later, though - I don't think we've really defined that.

**Comment by gibiansky** [comment]
Fair enough.

The thought came up because in my client, I am storing callbacks for each executed cell, based on the parent header; if a message comes in from the kernel with a "parent" indicating a given cell, it will be handled with the appropriate callback. Unless it's defined when more messages cannot be sent, though, the callbacks can never be freed and the client is guaranteed to use up progressively more resources, since it never knows that it will not receive any more messages.

If that is the intended / expected behavior for clients for the time being, go ahead and close this :)

**Comment by takluyver** [comment]
I totally agree on this and your other issue that it's something the spec should be more explicit about - I'm passing on the best answers I have at the moment, not saying there's no need to clarify them.

**Comment by gibiansky** [comment]
Yup, totally understand!

**Comment by minrk** [comment]
Due to the separate channels, it is not possible to enforce that shell messages arrive after iopub messages. If kernels comply with the spec, `status: idle` message will be sent at the end of handling every request. This should be used to indicate that output is complete for a given parent. We can leave this open as a docs issue until we add that note to the spec.

**Comment by minrk** [comment]
I opened jupyter/jupyter_client#164, aiming to clarify both this and #1576. @gibiansky can you check that content and see if it clarifies these things?
