### ISSUE TITLE
Functionality to import from other notebooks or child notebooks

### ISSUE THREAD

**Issue by g92pratik** [jupyter/notebook#1588]
We can import functions from one python file to another. We should be able to do the same for notebooks. 
I have very long notebook and it becomes tough to scroll through it. Ideally I would like to create small notebooks each having separate and independent functionality and then I should be able to import these child notebooks in master notebook.

**Comment by takluyver** [comment]
We recommend that things like function and class definitions that you want to reuse should be stored in regular Python files rather than in notebooks. We have some code somewhere that makes it possible to import a notebook, but the notebook environment is not great for writing the sort of code that you import.

Code often starts in interactive notebooks and later moves to modules, and we know that that refactoring process is not very smooth at the moment. We're interested in ways to make that more pleasant.

**Comment by g92pratik** [comment]
You have mentioned that there is 

> some code somewhere that makes it possible to import a notebook.

Can I get details or link to this code. I can have a look and take it up for improvement.

**Comment by takluyver** [comment]
@minrk knows where it exists

**Comment by khughitt** [comment]
One advantage to importing child notebooks vs. python classes/functions is that the notebook can encapsulate other things like Markdown. This way you can build modular pipelines which render to HTML/PDF, with each child document maintaining both the code logic, but also any relevant text/references/etc.

**Comment by minrk** [comment]
The importing notebooks in IPython example [is here](https://github.com/ipython/ipython/blob/4.x/examples/IPython%20Kernel/Importing%20Notebooks.ipynb).

**Comment by gnestor** [comment]
There is a library for this!

https://github.com/ipython/ipynb
