### ISSUE TITLE
Revise  markdown"attachment" spec.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#1655]
It seem we made a few unfortunate decision with the way we use attachments. 
- It does not follow markdown spec: `![alt](/url "title")` imply that we :
  - need to use `attachment://` for the link to be an url
  - escape the filename as `)]` should **not** be present. 

Have to check if the attachment thing was released to know if we can fix it without backward compat. .

**Comment by Carreau** [comment]
@julienr I guess this one will be of interest to you :-) 

> Have to check if the attachment thing was released to know if we can fix it without backward compat.

Attachments are only on master, so it should be safe to make think markdown compliant again !

**Comment by minrk** [comment]
> Have to check if the attachment thing was released to know if we can fix it without backward compat.

It hasn't been, but it's part of why I [pinged people](https://github.com/jupyter/nbformat/issues/40) about releasing nbformat, as well as brought it up at the last two dev meetings.

However, the about-to-be-released nbformat spec in 4.1 *only* defines how attachments are included in the notebook data structure, not how markdown references to them should be made. That bit is in this repo, and only in master, so we are free to fix it if there's something wrong.

**Comment by julienr** [comment]
@Carreau Ooops, that was an oversight on my part, sorry about that. Seems like your patch fixes it though or is there anything else that require changes ?

**Comment by mgeier** [comment]
Sorry if I missed this in previous discussions, but why exactly is the double slash `//` necessary for URLs?

I think this looks quite ugly.
And since no host specification is following, it might not even be a valid URL?
If anything, shouldn't it be *three* slashes (which is even more ridiculous)?

I didn't find anything about this in the Markdown spec (https://daringfireball.net/projects/markdown/syntax).

The current CommonMark spec (http://spec.commonmark.org/0.27/#link-destination) doesn't require it.

RFC 3986, if I understand it correctly, doesn't require the double slash: https://tools.ietf.org/html/rfc3986#section-4.2

**Comment by minrk** [comment]
`://` is not strictly required to be a valid URL, but it is conventional and clear. I don't have a strong preference between `attachment:name.ext` and `attachment://name.ext`, though I think the latter is clearer. I think you are correct that there wasn't a correctness issue, as `attachment:name.ext` is valid, according to markdown in particular and URLs in general.

> And since no host specification is following, it might not even be a valid URL?

I don't believe there is any requirement that hosts come after `://` (see `file://`)

> If anything, shouldn't it be three slashes (which is even more ridiculous)?
 
I wouldn't say so, no. The third slash denotes absolute file paths, not resources that don't live on a filesystem. For `file://`, the delimiter is still `://`.

**Comment by mgeier** [comment]
Thanks for the quick answer. Since it wasn't quite the answer I was hoping for, I had another look at RFC 3986.

Is this the relevant source?

If yes, I'm now quite sure that the current form `attachment://myfile.png` is **invalid**!

A double slash can only appear together with a (possibly empty) host name, but in this case, the path has to be absolute or empty (see https://tools.ietf.org/html/rfc3986#section-3).

Using three slashes `attachment:///myfile.png` would be syntactically possible, but I guess in our case an absolute path doesn't make sense. And three slashes look ridiculous. But this is actually the not so uncommon case of `file:///my/absolute/file.txt`.

Here's the syntax definition of RFC 3986 (https://tools.ietf.org/html/rfc3986#appendix-A):

```
URI           = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

hier-part     = "//" authority path-abempty
              / path-absolute
              / path-rootless
              / path-empty

URI-reference = URI / relative-ref

absolute-URI  = scheme ":" hier-part [ "?" query ]

relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

relative-part = "//" authority path-abempty
              / path-absolute
              / path-noscheme
              / path-empty

scheme        = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )

authority     = [ userinfo "@" ] host [ ":" port ]

...

path-rootless = segment-nz *( "/" segment )

...

segment-nz    = 1*pchar

...
```

I initially thought the `relative-ref` is what we need, but this doesn't have a `scheme`!

I guess what we want is plain old `URI`. The `scheme` part and the colon should be obvious, and for the `hier-part` there is only one option that fits in our case, namely `path-rootless`.

So if I'm not mistaken and if RFC 3986 is indeed the relevant source, the double slash is not allowed and the correct way to spell it would be

    attachment:myfile.png

... which IMHO is much less confusing and simply looks better.

**Comment by mgeier** [comment]
I've provided https://github.com/jupyter/nbformat/pull/77 and #1965.
Does this need to be changed anywhere else?

**Comment by minrk** [comment]
Should be just those two.
