### ISSUE TITLE
pd.read_clipboard in Jupyter makes python 3.5 crash on windows

### ISSUE THREAD

**Issue by jmarrec** [jupyter/notebook#1667]
Linked issue: https://github.com/pydata/pandas/issues/13946

Disclaimer: I'm not quite sure if the problem is really on pandas' side or on jupyter's, but it seems that this command works everywhere **but in a Jupyter notebook**
#### Problem

Given the following code:

```
import pandas as pd
pd.read_clipboard()
```

If I use it in a python file, it works fine.

If I use ipython in cmd.exe, it works fine.

Now if I use it in a Jupyter notebook, it consistently makes my kernel die.
## INSTALLED VERSIONS

commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 25.1.6
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.0
statsmodels: 0.6.1
xarray: None
IPython: 5.0.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.2
lxml: 3.6.1
bs4: 4.4.1
html5lib: 0.9999999
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.40.0
pandas_datareader: 0.2.1
##### Jupyter info:

jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.1.0                    py35_0
ipython                   5.0.0                    py35_0
ipython-notebook          4.0.4                    py35_3
ipython-qtconsole         4.0.1                    py35_4
ipython_genutils          0.1.0                    py35_0

**Comment by takluyver** [comment]
Sorry to turf you back, but I'm pretty sure this is something to do with pandas in the first instance: it's using [ctypes code](https://github.com/pydata/pandas/blob/b7abef4949fb1ba7fd1004feba4f47ace7004282/pandas/util/clipboard.py#L62) to access the Windows clipboard, and ctypes is the top suspect whenever a Python process dies without an exception.

How are you starting Jupyter? I wonder if there's some difference in the environment if it's running without a console window.

Ping @jreback

**Comment by jmarrec** [comment]
to launch it I open cmd.exe, type `jupyter notebook <PathToFolder>`.

(I'll let you guys decide if it's a pandas or a jupyter...)

**Comment by takluyver** [comment]
If you run this code directly in a notebook, does the kernel die? And if you split it up line by line, which line is it that makes the kernel die?

```python
CF_UNICODETEXT = 13
d = ctypes.windll
d.user32.OpenClipboard(0)
handle = d.user32.GetClipboardData(CF_UNICODETEXT)
data = ctypes.c_wchar_p(handle).value
d.user32.CloseClipboard()
```

(This is part of the code that I believe pandas is running when you call `read_clipboard()`.

**Comment by jmarrec** [comment]
It does die, on line `data = ctypes.c_wchar_p(handle).value`

**Comment by jmarrec** [comment]
This works fine though:

```
import win32clipboard
win32clipboard.OpenClipboard()
data = win32clipboard.GetClipboardData(win32clipboard.CF_UNICODETEXT)
win32clipboard.CloseClipboard()
```

so yeah, ctypes is seems to be the problem

**Comment by takluyver** [comment]
We do have some code to access the clipboard in IPython, but it isn't run unless you run `%paste`. I still think we're causing pandas' clipboard to hit some corner case that's exposing a bug there. 'access violation' sounds like a Windows equivalent of 'segmentation fault'.

**Comment by aravindsd** [comment]
See Pandas documentation to use **read_clipboard** (Anaconda Package)
It seems pandas read_clipboard need optional dependencies which are not yet compatible with **python 3.5**. I guess that's hindrance for _**read_clipboard**_ 

http://pandas.pydata.org/pandas-docs/stable/install.html#optional-dependencies

![image](https://cloud.githubusercontent.com/assets/19371042/20247366/58a93212-a9f0-11e6-8a5b-a22eb8ba036d.png)

Doesn't have any issue in Python 3.4 (Anaconda Package)

**Comment by takluyver** [comment]
Looking at the code, I don't think it needs any of those on Windows, which is the case for this bug report. In any case, `xclip` and `xsel` are external commands, so they shouldn't depend on the Python version.

**Comment by ayhanfuat** [comment]
This seems to be resolved in one of the updates of pandas. After upgrading to 0.20.3 I got it working in both Jupyter Notebook and Jupyter QtConsole.

**Comment by takluyver** [comment]
Thanks @ayhanfuat

**Comment by mechalr8** [comment]
When I write the below code in Anaconda 3.7

"nfl_frame = pd.read_clipboard()
 nfl_frame"

I get the following error.

---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-13-fca6289041f5> in <module>
----> 1 nfl_frame = pd.read_clipboard()
      2 nfl_frame

~\Anaconda3\lib\site-packages\pandas\io\clipboards.py in read_clipboard(sep, **kwargs)
     83         text = text.encode('utf-8')
     84 
---> 85     return read_csv(StringIO(text), sep=sep, **kwargs)
     86 
     87 

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    700                     skip_blank_lines=skip_blank_lines)
    701 
--> 702         return _read(filepath_or_buffer, kwds)
    703 
    704     parser_f.__name__ = name

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    433 
    434     try:
--> 435         data = parser.read(nrows)
    436     finally:
    437         parser.close()

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
   1137     def read(self, nrows=None):
   1138         nrows = _validate_integer('nrows', nrows)
-> 1139         ret = self._engine.read(nrows)
   1140 
   1141         # May alter columns / col_dict

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in read(self, rows)
   2413             content = content[1:]
   2414 
-> 2415         alldata = self._rows_to_cols(content)
   2416         data = self._exclude_implicit_index(alldata)
   2417 

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in _rows_to_cols(self, content)
   3064                     msg += '. ' + reason
   3065 
-> 3066                 self._alert_malformed(msg, row_num + 1)
   3067 
   3068         # see gh-13320

~\Anaconda3\lib\site-packages\pandas\io\parsers.py in _alert_malformed(self, msg, row_num)
   2833 
   2834         if self.error_bad_lines:
-> 2835             raise ParserError(msg)
   2836         elif self.warn_bad_lines:
   2837             base = 'Skipping line {row_num}: '.format(row_num=row_num)

ParserError: Expected 11 fields in line 5, saw 12. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

Please help
