### ISSUE TITLE
Feature Request: seeing arguments of function

### ISSUE THREAD

**Issue by startakovsky** [jupyter/notebook#167]
In IPython, when I would begin to enter a function such as `foo` with argument `bar` and keyword argument `baz` defaulted to `None`, I would type in `foo(` and immediately see `bar, baz = None` in a little caption (tooltip) which popped up, displaying the docstring in an expandable format. Super helpful!

I would like to see this in Jupyter. I would take a screenshot of this but the tooltip disappears when I initiate the keyboard shortcut for screenshots.

**Comment by minrk** [comment]
Seeing the signature is triggered by hitting shift-tab. This is the same in Jupyter and IPython, since Jupyter is just a renaming of the project.

**Comment by Carreau** [comment]
Shift tab has been here since 1.0, and tab was deprecated back then as it conflicts with other functionality. You'll need to remap you habits.

**Comment by jasongrout** [comment]
@startakovsky didn't say he used tab.  He said the signature popped up automatically.  I thought I remember that too, and I thought it was extremely cool.

**Comment by rgbkrk** [comment]
> He said the signature popped up automatically. I thought I remember that too, and I thought it was extremely cool.

It was cool!

The old tab functionality was my preference too, but I wasn't present for that discussion (or don't remember it).

1.0:

![screenshot 2015-06-23 12 46 57](https://cloud.githubusercontent.com/assets/836375/8313031/da20d9a8-19a5-11e5-8728-23add89e247c.png)

Hitting tab on the current 3.x series:

![screenshot 2015-06-23 12 47 36](https://cloud.githubusercontent.com/assets/836375/8313042/e62548a6-19a5-11e5-89b5-b2fdcb020e9d.png)

Muscle memory is hard and I find myself doing this as well.

**Comment by ellisonbg** [comment]
Will is going to be working on this stuff during the summer and I think we
do want to address some of these UI/UX issues. I would prefer to have a
single UI that does everything well, rather than two partial UIs as we have
now.

On Tue, Jun 23, 2015 at 10:47 AM, Kyle Kelley <notifications@github.com>
wrote:

> He said the signature popped up automatically. I thought I remember that
> too, and I thought it was extremely cool.
>
> It was cool!
>
> The old tab functionality was my preference too, but I wasn't present for
> that discussion (or don't remember it).
>
> 1.0:
>
> [image: screenshot 2015-06-23 12 46 57]
> <https://cloud.githubusercontent.com/assets/836375/8313031/da20d9a8-19a5-11e5-8728-23add89e247c.png>
>
> Hitting tab on the current 3.x series:
>
> [image: screenshot 2015-06-23 12 47 36]
> <https://cloud.githubusercontent.com/assets/836375/8313042/e62548a6-19a5-11e5-89b5-b2fdcb020e9d.png>
>
> Muscle memory is hard and I find myself doing this as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/167#issuecomment-114587195>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Sorry for being imprecise in response. `(` and `tab` where deprecated. 

@startakovsky sorry this response is long, nothing against you, just historical explanation that I'm tired in repeting in many places, so here it will be.

The behavior of tab was inconsistent and difficult to understand in many case. 

- `(` after 3sec  not doing anything would trigger tooltip. 
   - which was inconsistent for haskell and other language.
   - confusing user wondering what they were doing. 
   - wondering why it wouldn't work sometimes (kernel busy)
- tooltip on tab after `(` in some unambiguous cases.
  - Sometime leading to completion.
  - nothing sometimes if kernel busy, even worse would indent. 
  - make user that actually complete on user_ns be pissed of
- complete on `([space]<tab>`.
  - sometimes
  - kernel busy problem again.
- Add kwarg, comma, space into the mix. 
  - Coma -> tooltip,
  - Comma space -> complete.
  - what if arg or kwarg subexpr?
  - what if several open parens ?
- Add regex into the mix. 
- Add other kernels into the mix. (so want to config regex,)
- People that want to completer/tooltip on 
  - space 
  - dollars
  - dot
  - backspace
  - not 3000 ms, but 2250, and only i when not looking at code and actually want tooltip cause it hides code. 
- Should you dismiss the same if auto-popped on `(` than if user press tab/shift tab explicitly ?

(shake the thing and optimize) 

Shift tab was since long before 1.0 bound to the Always do tooltip, and was alway the way to do it. Despite people saying otherwise on the internet (even our own tuto). It was the obvious non-ambiguous choice that simplified the code and the question about what tab does (@fperez said "we've weaponized the tab key"). The problem on that is there is no simple answer to `how do I complete`, `how do i get tooltip` and `what does tab do`.
Hence Tab was : 
  - made optional default true
  - made optional default false
  - removed.

The last 2 might have been in same release cycle. Not sure anymore for `(<wait>`

> Will is going to be working on this stuff during the summer and I think we
do want to address some of these UI/UX issues. I would prefer to have a
single UI that does everything well, rather than two partial UIs as we have
now.

I did propose a tooltippleter, and proposed that the message spec be changed for completion/inspection request to be merged in ; plus a UI type:

```
  completion 1 | This is the help for the current selection (arrow)
  completion 2 | on the left of this text, it is the great 
> completion 3 | unified tooltipleter. It is particularly 
  completion 4 | useful for julia as methods have same name
  completion 5 | multiple dispatch and not same docstring
  completion 6 | 
```

For which I was welcome with roughly what **I** (emphased I, don't render great on gh) remember as : We don't see the point, it is useless, the completer completes and tooltips tooltips. These are not the same actions it is perfectly natural to have 2 shortcuts.

So, sorry if it was better before, sorry if we don't communicate enough, sorry if people don't read [release notes](http://ipython.org/ipython-doc/2/whatsnew/version2.0.html#other-changes), sorry if I can seem annoyed, but I answered this question around 5 times in the last 2 weeks in 4 differents way of communication with people asking the same question on 3 different channel without acknowledging responses, or ignoring responses and reasking somewhere else.

This is (as we discussed in meeting) reason why gitter and RT chat should be banned from first help channel in which we asked to go (not you @startakovsky) so that they could get information like that in a way that can be googled, and editted. (which is 1 point for not ML first) 

Please feel free to link to this explanation, edit, add links, tags or anything that make it easier to find. 

Thanks for reading.

**Comment by startakovsky** [comment]
@Carreau Thank you so much for your response. I hear your frustration, you are doing great & please please please keep up the good work.

**Comment by jbwhit** [comment]
I'm not seeing `shift-tab` work to bring up the tooltip in 5.0 -- if I hold shift and hit tab a number of times I can still get the bottom help screen to come up. 

```
The version of the notebook server is 5.0.0 and is running on:
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]

Current Kernel Information:

Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.```

**Comment by sorin-postelnicu** [comment]
For me also, shift-tab is not working.

The version of the notebook server is 5.0.0 and is running on:
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Current Kernel Information:
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
IPython 5.3.0 -- An enhanced Interactive Python.
