### ISSUE TITLE
Not getting proper pdf format using Latex

### ISSUE THREAD

**Issue by shubhjain26** [jupyter/notebook#1693]
Hi,

When I am exporting a notebook into PDF format using Latex, then the generated PDF does not have proper format. I can see the html code and also alignment is not proper. Is there any formatting plugin available which renders proper alignment with images ?
I tried using template but was no luck. Any suggestions would be a great help.

**Comment by takluyver** [comment]
Sorry, can you be a bit more specific about what you did and what you see?

**Comment by shubhjain26** [comment]
I am trying to export my jupyter notebook in pdf format using nbconvert. I have installed Latex packages required for exporting in PDF. After package installation, I am able to get the pdf but it is not in proper format. The html format is being depicted as html code and also it is not properly aligned which means if I have some long lines which is horizontally scroll-able then in pdf format I am not getting it complete. Not sure how we can format it.

**Comment by takluyver** [comment]
I guess I should have been more specific about being more specific ;-)

What commands are you typing in? Or if you're converting by click things, what things do you click? Can you either upload an example file, or at least show us a screenshot of the problem?

**Comment by dvigneshwer** [comment]
I am also facing the same problems like @shubhjain26

**Comment by michaelpacer** [comment]
@shubhjain26 @dvigneshwer 

Are you running off of the master branch or are you working off of the stable version. If you are working off of the stable version, could you check that it works using the nbconvert master?

Additionally, could you see if this occurs if you use a more limited set of html markup? I.e., if it is a problem with a particular feature that is causing the entire conversion pipeline to burst rather than something general, it will save a lot of time to know which feature is causing that.

**Comment by michaelpacer** [comment]
Closing this in favor of addressing in https://github.com/jupyter/nbconvert/issues/388. @shubhjain26 If you want to post examples of your problem, please do so in this other issue.
