### ISSUE TITLE
Safari can't connect to kernel

### ISSUE THREAD

**Issue by tibaes** [jupyter/notebook#1744]
I was testing a jupyter notebook inside a docker container on MacOS.
Neither installing jupyter via conda or pip worked for safari; the home of jupyter is served flawless, but when a notebook is opened, it get stuck with the "Connecting Kernel".
The same server works with firefox.

**Comment by minrk** [comment]
Are you using a self-signed SSL certificate? It is a known issue that Safari does not allow websocket connections on https if the certificate is 'untrusted' (e.g. self-signed or otherwise results in the "Are you sure..." prompt on connect). This is the most common cause for kernel connection failing only on Safari.

**Comment by tibaes** [comment]
Indeed it is a self-signed certificate. I believed that after the "Are you sure.." prompt, this would not be the problem. So, the only way to work with Safari is using a 'trusted' certificate? I will stick with firefox then... Thanks and closing the issue.

**Comment by jtpio** [comment]
Closing as this should now be fixed with the latest Jupyter Notebook 7 release.

Please don't hesitate to re-open or open a new issue otherwise, thanks!
