### ISSUE TITLE
Add a Search Box for Folder/File List

### ISSUE THREAD

**Issue by emptymalei** [jupyter/notebook#1747]
I have tonnes of folders/files in my working path, e.g.,
![image](https://cloud.githubusercontent.com/assets/663798/18282110/dbe1b078-741c-11e6-82ff-d3a00df1731a.png)

Each time I need to find something I have to <kbd>⌘</kbd>+<kbd>F</kbd> and using the browser built in search. It's not so convenient actually.

Meanwhile, I noticed [`fontawesome.io`](http://fontawesome.io/icons/) has a very nice search box to filter the icons. Would it be cool to implement something like that?

**Comment by gnestor** [comment]
I believe this is what you are looking for: https://github.com/jdfreder/jupyter-tree-filter

To install, I suggest installing [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) which is an extension manager for the Jupyter Notebook. Otherwise, follow the [nbextension installation instructions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions#installation
).

**Comment by emptymalei** [comment]
@gnestor Exactly what I was looking for. Thanks.

**Comment by ggrrll** [comment]
@gnestor - thanks for the suggestion

however, it doesn't look for the file in sub-directories... maybe that's something to be implemented too...

**Comment by gnestor** [comment]
@ggrrll I suggest that you create a feature request issue on the https://github.com/jdfreder/jupyter-tree-filter repo.
