### ISSUE TITLE
Unable to connect to the web application of Jupyter notebook from docker container

### ISSUE THREAD

**Issue by vasantivmahajan** [jupyter/notebook#1843]
I am running a docker container and I need to connect to Jupyter notebook from my container. I have installed the Jupyter notebooks and on executing the command "jupyter notebook" for running the notebook, the following message is displayed:
![image](https://cloud.githubusercontent.com/assets/17990840/19484404/7e7e1992-9525-11e6-813e-8feb23852305.png)
On opening the web application in Chrome using "http://192.168.99.101:8888/", an error is displayed stating the site cannot be reached. Could someone help me in connecting the Jupyter notebook web application.

Any help is appreciated.

**Comment by Jagmills** [comment]
Not sure if this is any help for you, but try (on the host machine):
docker ps

And inspect the "ports" column. It should say "0.0.0.0:8888->8888/tcp". If not, Docker is not forwarding the ports correctly, likely due to the way that you started the container. Using -p 8888:8888 as a parameter when running the container could fix it.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
