### ISSUE TITLE
Jupyter Notebook on Windows 10, uses the default conda root instead of environment

### ISSUE THREAD

**Issue by albertnanda** [jupyter/notebook#1926]
I installed the latest version of anaconda 4.2.0_x86_X64 on my windows 10 machine.
I then created a new environment,
conda create -n ker python=3.4
activate ker
jupyter notebook
However, it still uses the root conda:
import sys
print(sys.executable)
C:\Users\cm\Anaconda3\python.exe
![conda_environments](https://cloud.githubusercontent.com/assets/20819507/20679406/b5dce2ae-b5c0-11e6-85c5-e211ea8097c4.JPG)
![list of kernels](https://cloud.githubusercontent.com/assets/20819507/20679405/b5db5696-b5c0-11e6-89a8-b29a4a1a588d.JPG)

**Comment by takluyver** [comment]
I think you need to install at least `ipykernel` inside the environment for it to be found. @damianavila and @bollwyvl might know more.

**Comment by damianavila** [comment]
Yep, that's correct, you need ipykernel on your ker environment... nb_conda_kernels will detect it and create the proper kernelspec.

**Comment by albertnanda** [comment]
Thanks @takluyver @damianavila , works like a charm :)

**Comment by ryancourtney** [comment]
I am having the same issue as above on Windows 10. Within a jupyter notebook `sys.executable` prints `'C:\Users\username\AppData\Local\Continuum\anaconda3\python.exe` while from the command prompt if I start `python` and run the same command it will properly print `'C:\Users\username\AppData\Local\Continuum\anaconda3\envs\environment-name\python.exe'. I followed the same steps as the original poster and even performed an additional `pip install ipykernel` inside the environment as @damianavila and @takluyver suggested.

Are there any additional steps that I need to take so that my jupyter notebook will recognize the environment and not just the default conda root?
