### ISSUE TITLE
trust from menu not working for readonly ipy notebook

### ISSUE THREAD

**Issue by cailiang9** [jupyter/notebook#195]
I use jupyter hub for multi user and open another notebook server for readonly sharing.
there are js code in output cell that isn't executing. I click trust menuitem but not working. 
however, running `ipython trust xyz.ipynb` works.

**Comment by minrk** [comment]
This is because the trust action is actually part of a save, which you don't have permission to do if it's read-only. I'm not sure if we can find a way to trigger trust without re-saving the notebook.

**Comment by cailiang9** [comment]
As I wrote in the comment: running `ipython trust xyz.ipynb` can work. Why trust should be part of a save? It just adds a signature to .ipython folder.

**Comment by minrk** [comment]
Until recently, the signature was stored in the notebook requiring a save. Now that it's moved to a separate database, the impediment is that there's no REST API for triggering signature other than the save API on the contents service. With how it works now, though, we could add an explicit trust endpoint that doesn't need write access to the notebook.

**Comment by cailiang9** [comment]
what about a simple js `IPython.notebook.kernel.execute('!ipython trust ' + sharedpath[sharedpath.length-1])`

**Comment by Carreau** [comment]
> what about a simple js IPython.notebook.kernel.execute('!ipython trust ' + sharedpath[sharedpath.length-1])

The kernel is not on the same machine that the notebook. 
The kernel might not be IPython kernel.
The kernel might not be python at all. 
The user of the kernel might not be the user of the notebook. 
The notebook might not be stored on disk, but in a DB on server.

**Comment by cailiang9** [comment]
ok ok, you win

**Comment by Carreau** [comment]
I know it's might not be always easy to see the all architecture at once, we don't ask user to understand everything, but the `IPython.notebook.kernel.execute('!ipython trust ' + sharedpath[sharedpath.length-1])` was a nice try :-)

**Comment by minrk** [comment]
There is a Python API for it, we would just need to expose an endpoint for it on the web server, if we decide to go that way.

**Comment by Madhu94** [comment]
@JamiesHQ Are you working on this? I'd like to give it a shot.

**Comment by JamiesHQ** [comment]
@Madhu94 - nope! go for it.

**Comment by Madhu94** [comment]
Thanks! @JamiesHQ

**Comment by Madhu94** [comment]
@minrk Do we still want trust to trigger a save ?

**Comment by minrk** [comment]
In order to trust read-only notebooks, we have to *not* trigger a save, which will fail due to permission issues. The trust action would have to be triggered explicitly server-side, rather than what we currently do, which is save a trusted notebook.

**Comment by Madhu94** [comment]
@minrk  Thanks. Since trust will no longer trigger a save, updating all the cells' metadata with "Trusted: True/False" and then computing the signature can be confusing.

For instance, say UserA creates NotebookA.  UserB has read only access to NotebookA but wants to trust it, so he doesn't have to re-run all code cells again which may not even be feasible.

In this case, when the notebook is first read by UserB, the output cells' metdata data is empty. While creating the model, we mark all cells' metadata with "trusted: False" and _then_  call [trust_notebook](https://github.com/jupyter/notebook/blob/5192d72c63369d7167c5472d06f87072d68ecc53/notebook/services/contents/manager.py#L417), which marks all cells as trusted and computes the signature. 

These changes to the cells' metadata do not get persisted. So the next time, when signature is computed on load (over [here](https://github.com/jupyter/notebook/blob/5192d72c63369d7167c5472d06f87072d68ecc53/notebook/services/contents/manager.py#L448)), the notebooks' cells' metadata is empty ``{}`` again.  

**I propose that we leave out this key ``trusted:True`` or ``trusted:False`` from the cells**, while computing the signature for the model (Maybe this could be achieved using a context manager).

What do you think ?

**Comment by minrk** [comment]
> I propose that we leave out this key trusted:True or trusted:False from the cells while computing the signature for the model.

We already do this. trust is only present in metadata when sending notebooks over the REST API, and consumed by `.check_cells` prior to signing in `.check_and_sign`.

We used to store signatures in notebooks themselves, which I believe is why we trigger `.save` in `.trust_notebook()`. Now that the notary stores signatures itself, we actually don't need to call save there, we can just call `self.notary.sign(nb)` directly instead of `mark_cells(nb, True)` followed by `.save(nb)`.

So I think we only need these changes:

1. call `self.notary.sign(nb)` instead of `notary.mark_cells` and `self.save` in `.trust_notebook`
2. make sure that save is not triggered prior to trust in the javascript for trust_notebook when the notebook is read-only.

**Comment by Madhu94** [comment]
> call self.notary.sign(nb) instead of notary.mark_cells and self.save in .trust_notebook  
This is what I did. Guess I should make a PR now with a "WIP" attached to it, because its easier to reason when you have code.
>make sure that save is not triggered prior to trust in the javascript for trust_notebook when the notebook is read-only.  
Sure.

>We already do this. trust is only present in metadata when sending notebooks over the REST API, and consumed by .check_cells prior to signing in .check_and_sign  
Oh, let me check again then. (I could have sworn that the ``mark_trusted_cells`` called as part of ``get`` leads to confusing results )

**Comment by Madhu94** [comment]
@minrk, I checked the codebase and logged an [issue](https://github.com/jupyter/nbformat/issues/98) with nbformat about this.
