### ISSUE TITLE
Spacing in text cells on Safari 10

### ISSUE THREAD

**Issue by ivirshup** [jupyter/notebook#1967]
I've been encountering some formatting strangeness in any text block (code and markdown) on Safari v10.0.1 using jupyter notebook v4.3.0.

Spaces in text are not being show. Once characters are placed the formatting looks correct. I've included an example below:

![jupytercode_spacing](https://cloud.githubusercontent.com/assets/8238804/21085541/7f410ade-c067-11e6-8dc1-f2c6660b1f47.gif)

If there are characters on the line after the cursor, there don't seem to be any issues. I haven't been able to replicate the issue in Chrome. 

Possibly related to #1943. Thanks for any help!

**Comment by gnestor** [comment]
Related: https://github.com/jupyterlab/jupyterlab/issues/522

**Comment by minrk** [comment]
I've definitely seen this, but can't seem to make it happen now (also Safari v10.0.1). @ivirshup does this happen with any text (i.e. cursor doesn't move across whitespace, only when characters are entered), or only in specific circumstances?

**Comment by gnestor** [comment]
@minrk I'm only observing it when on single spaces. Double spaces and characters after single spaces update correctly. I'm testing against notebook at master on Safari 10.0.2.

**Comment by ivirshup** [comment]
@minrk 

I'm haven't done very thorough testing, but I just spent about ten minutes in a fresh notebook and this is what I'm seeing:

## In code cells

Strange space formatting:

* Will occur immediately after any delimiter
  * e.g. `=`, `,`, `.`, `(`, `)`, `[`, `]`, `{`, `}`, `"`, `'`, etc.
* Will not occurs within closed delimiters
* Will not occur within compound statement if closed by `:`
  * e.g. it will occur here `if x =={cursor}`, but not here`if x =={cursor}:`

## In markdown cells

Strange space formatting occurs:

* Unless cursor is at start of a new line
* Unless cursor is placed immediately after closed markup delimiter (e.g. `*text*{cursor}`)
* Unless within markup delimiters (e.g. `*text{cursor}*`)

Hope this helps!

**Comment by fonnesbeck** [comment]
I'm seeing it now on 10.0.2 also with notebook 4.3.0. Where I see it most prominently is when I type a space, but the cursor does not move, yet when I type a letter afterwards, it is properly spaced. So the space registered, but was not displayed until additional text was added.

**Comment by minrk** [comment]
Thanks for the detailed circumstances. I know I've seen this in the past, but can't make it happen today. Since @gnestor seems to be able to, I'll let him try to tack it down. If it's a regression in 4.3, it's most likely related to the bump in codemirror version. Can anyone here who sees this in 4.3 tell if the behavior is different in 4.2?

**Comment by fonnesbeck** [comment]
I only noticed it starting in 4.3, and its the sort of thing that would jump out at me.

**Comment by gnestor** [comment]
I did some testing and it appears that this behavior appears in [CodeMirror 5.17](https://github.com/codemirror/CodeMirror/releases/tag/5.17.0)...

**Comment by gnestor** [comment]
@flying-sheep @oxinabox Pinging you because upgrading to CodeMirror 5.21 introduced a regression for Safari 10 users. I'm trying to track down the cause. I've found that it was introduced after 5.16. I created an issue on codemirror: https://github.com/codemirror/CodeMirror/issues/4454

**Comment by gnestor** [comment]
This is temporarily fixed by downgrading CodeMirror to 5.16. 

@flying-sheep @oxinabox I understand that you have contributions that have been merged since 5.16, so we intend to upgrade to the latest version as soon as we can resolve the source of this issue. 

Let's move conversation to https://github.com/codemirror/CodeMirror/issues/4454 and we can re-open this issue if we find that the source of this is in fact in notebook.
