### ISSUE TITLE
Password required after update

### ISSUE THREAD

**Issue by peter-ch** [jupyter/notebook#1987]
After I updated to 4.3 with pip, it started to ask me for password that doesn't exist, so it never lets me in.

**Comment by takluyver** [comment]
We had to enable authentication by default because of a security issue. More info in [this comment](https://github.com/jupyter/notebook/issues/1944#issuecomment-266434362).

If you let it open a browser when you start the notebook server, it should authenticate automatically, bypassing the login page. Otherwise, there should be a URL in the log to connect with a token, or you can run `jupyter notebook list` in a terminal to find it. In 4.3.1, which we're trying to release quickly, the login page will explain this.

Sorry, we know this is disruptive, but we haven't yet come up with a good alternative.

**Comment by takluyver** [comment]
See also [the updated security docs](http://jupyter-notebook.readthedocs.io/en/latest/security.html).

**Comment by Carreau** [comment]
please see #1980 as well.
