### ISSUE TITLE
Ability to move line up in editor with ctrl+up

### ISSUE THREAD

**Issue by lincolnfrias** [jupyter/notebook#2036]
As someone moving from R to python/Jupyter, I miss the option to move the line (or selected lines) up/down with something like ctrl-up/down (as in Atom Editor) or alt-up/down as in RStudio.
 Is there a way to do this in the jupyter notebook?

**Comment by gnestor** [comment]
Hi @lincolnfrias! This is possible because the notebook uses CodeMirror and CM supports "swapLineUp" and "swapLineDown" commands as apart of its Sublime Text keymap bindings. The following tutorial will explain how you can [edit your custom.js file](http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/JavaScript%20Notebook%20Extensions.html#custom.js) and add [something like this] to enable this: http://blog.rtwilson.com/how-to-get-sublime-text-style-editing-in-the-ipythonjupyter-notebook/

**Comment by gnestor** [comment]
I'm going to close this as [we don't plan on supporting this out-of-the-box](http://blog.rtwilson.com/how-to-get-sublime-text-style-editing-in-the-ipythonjupyter-notebook/).

**Comment by lincolnfrias** [comment]
Ok, thanks for the tips.

**Comment by kenahoo** [comment]
@lincolnfrias did you discover a way to do this without enabling all of the other Sublime-style keyboard commands?  I'd like to be able to pick and choose which ones I enable, and how they're bound to the keyboard, because I routinely also use RStudio and IntelliJ (but not Sublime), and I'd like to get as many things as possible to be in agreement.

**Comment by lincolnfrias** [comment]
Hi @kenahoo, I had the same motivation as yours but I did not find a way to pick and choose.
