### ISSUE TITLE
latex formula is not displaying correctly viewed online

### ISSUE THREAD

**Issue by chakpongchung** [jupyter/notebook#2045]
This .ipynb is displayed correctly in local, but not correctly displayed online. Are there any encodings problem in notebook?

http://nbviewer.jupyter.org/github/chakpongchung/spherical-harmonics-expansion/blob/master/Master-Project.ipynb

**Comment by takluyver** [comment]
If I make the block maths (`$$` delimited blocks) start at the beginning of a line, without leading spaces, it renders correctly. At present, nbconvert only handles block math correctly if it's at the start of the line.

@michaelpacer this is a discrepancy between our processing of math blocks in the live notebook and in nbconvert. I don't have a particular feeling about which behaviour is better.

**Comment by chakpongchung** [comment]
Thank you for looking at it!

"make the block maths ($$ delimited blocks) start at the beginning of a line, without leading spaces"

I have modified this part:
$$ \vec{R} = \begin{bmatrix} R{x} \ R{y} \ R_{z}

     \end{bmatrix}
    =
     \begin{bmatrix}
       i L_{x} \\
       i L_{y} \\
       i L_{z}
     \end{bmatrix}
              =
     \begin{bmatrix}
       \frac{i}{2}(L_{+}+L_{-} ) \\
       \frac{1}{2}(L_{+}-L_{-} )  \\
       i L_{z}
     \end{bmatrix}
    $$

But it is still not displaying correctly. Did I misunderstand anything?

**Comment by takluyver** [comment]
That sounds right. Here's a copy where the rendering works for me:

http://nbviewer.jupyter.org/gist/takluyver/ed0c6030eb07ab2d76f74d3e295e7b75

**Comment by chakpongchung** [comment]
Thanks!

It seems like you are using python 3?

**Comment by takluyver** [comment]
Yep, though it shouldn't affect the Markdown.

**Comment by chakpongchung** [comment]
Anyway thank you for the help!

**Comment by jtorcasso** [comment]
I have a similar problem with latex math in my markdown. I have the following markdown cell:

`The variance is a little more tricky, 
$$
Var[X] = E[(X - E[X])'(X - E[X])] = E[X'X - X'E[X] - E[X]'X + E[X]'E[X]]
$$
$$
= E[X'X] - E[X]'E[X] = 
E\left[
\begin{pmatrix}
X_1 & X_2
\end{pmatrix}
\begin{pmatrix}
X_1 \\ X_2
\end{pmatrix}
- 
\begin{pmatrix}
E[X_1] & E[X_2]
\end{pmatrix}
\begin{pmatrix}
E[X_1] \\ E[X_2]
\end{pmatrix}
\right]
$$
$$
=
\begin{pmatrix}
E[X_1^2] - E[X_1]^2 & E[X_1X_2] - E[X_1]E[X_2] \\
E[X_2X_1] - E[X_2]E[X_1] & E[X_2^2] - E[X_2]^2
\end{pmatrix}
= 
\begin{pmatrix}
Var[X_1] & Cov[X_1,X_2] \\
Cov[X_1,X_2] & Var[X_2].
\end{pmatrix}
$$

so that $Var[X]$ is $2\times 2$, symmetric, variance matrix.`

But it displays as...

![var](https://user-images.githubusercontent.com/3222444/31248955-333bcada-a9db-11e7-8c98-a2754c4dc8fc.png)

Is there a certain way I should be writing the markdown so it renders correctly on github? It works just fine when I output a pdf via LateX or viewing the notebook itself. The location of the whole notebook is [here](https://github.com/jtorcasso/teaching/blob/master/econ210_fall2017/lectures/Lesson_3_Summarizing_Distributions_Estimators_Asymptotics.ipynb).

**Comment by mpacer** [comment]
Yes, don't put `=` or `-` on their own on a line. 

For some reason they're being interpreted by our markdown parser as headers. 

The following works: 

```LaTeX
$$
Var[X] = E[(X - E[X])'(X - E[X])] = E[X'X - X'E[X] - E[X]'X + E[X]'E[X]]
$$
$$
= E[X'X] - E[X]'E[X] = 
E\left[
\begin{pmatrix}
X_1 & X_2
\end{pmatrix}
\begin{pmatrix}
X_1 \\ X_2
\end{pmatrix} -
\begin{pmatrix}
E[X_1] & E[X_2]
\end{pmatrix}
\begin{pmatrix}
E[X_1] \\ E[X_2]
\end{pmatrix}
\right]
$$
$$
= \begin{pmatrix}
E[X_1^2] - E[X_1]^2 & E[X_1X_2] - E[X_1]E[X_2] \\
E[X_2X_1] - E[X_2]E[X_1] & E[X_2^2] - E[X_2]^2
\end{pmatrix}
= \begin{pmatrix}
Var[X_1] & Cov[X_1,X_2] \\
Cov[X_1,X_2] & Var[X_2].
\end{pmatrix}
$$
```

I'm not sure why this is happening though. @takluyver @gnestor @ian-r-rose any thoughts?

I think I've seen similar issues with regards to interpreting some things as lists if you prefix them with a `-` or a `+`… but I figured I'd wait until a user actually ran into this before diving into the order of operations for our mathjax parsing and markdown rendering again.

@jtorcasso, could you open a new report specifically about this bug?

**Comment by jtorcasso** [comment]
Added new report [here](https://github.com/jupyter/notebook/issues/2905).
