### ISSUE TITLE
jupyter --version is incorrect

### ISSUE THREAD

**Issue by MatthewKleinsmith** [jupyter/notebook#2059]
### From the terminal:

![jupyter_version_false](https://cloud.githubusercontent.com/assets/8968171/22186194/8d6d4032-e0a6-11e6-8f03-901f97cd850a.png)

### From the notebook:

![jupyter_version_true](https://cloud.githubusercontent.com/assets/8968171/22186193/8d6bf86c-e0a6-11e6-9e67-0d00bf21ffd1.png)

**Comment by SylvainCorlay** [comment]
Hi Matthew,

jupyter is not the notebook. It is a meta package having a dependency on
notebook, and therefore it can have a different version number.

Sylvain

**Comment by takluyver** [comment]
To check the version number of the notebook at the command line, you can run `jupyter notebook --version`

The version number you get with `jupyter --version` is actually that of [jupyter_core](https://pypi.python.org/pypi/jupyter_core), a common base piece which all Jupyter applications depend on, rather than than the jupyter metapackage.
