### ISSUE TITLE
Add parenthesis in auto-completion

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#2079]
Hi all,

what about having an autocompletion that adds _also the parenthesis_ , when I select the completion, with 'tab' + 'return' ? 

(for instance, for pandas dataframe (df): shape stays as `df.shape`, but for _head_  I would like to get `df.head()`, instead of just `df.head`).

It would be quite helpful to skip fingers 'acrobatics' each time you have that kind of functions...

Thanks for your support.

**Comment by minrk** [comment]
Interesting idea! This is probably a job for IPython's completions, and may be addressed by the upcoming switch to jedi in IPython 6.

**Comment by Carreau** [comment]
> Interesting idea! This is probably a job for IPython's completions, and may be addressed by the upcoming switch to jedi in IPython 6.

I had this enabled on jedi in terminal for some time.
That's actually annoying in many case, because assigning a method/function is a valid operation in python. As is passing a callback, like in filter, map, or many other case.
So you end up being annoyed by the extra parens even if it's 1 backspace away.
Adding the closing parens would be annoying to, an you would have to press left arrow once. The current completion API does not allow to reposition the cursor.

I'm happy to (re)give it a try though.

**Comment by takluyver** [comment]
PyCharm also adds parentheses - it does occasionally cause me to write code that does something different from what I expect, because I'm using the result of a function instead of the function itself. Mostly, though, I've got used to deleting the extra parentheses when I want to pass a function or method.

**Comment by ggrrll** [comment]
indeed...I think it's still easier to click backspace key ( delete one parenthesis ), instead of opening parenthesis ... - considering that some times you don't have too

**Comment by ggrrll** [comment]
it's ok for me... up to the devs to set their priorities :) -- I guess this is not very high :)

**Comment by Jas-kirat** [comment]
Hi if you can please work on adding parentheses it would be great as the parentheses key in my laptop does not work anymore which makes it very difficult for me to write the code. I can't afford to repair my keyboard right now so if anyone can help me with this that would be great.
