### ISSUE TITLE
Link with token from UI

### ISSUE THREAD

**Issue by minrk** [jupyter/notebook#2094]
It would probably be convenient for users who switch browsers / toggle private browsing to be able to get a link with the auth token in the URL that can be copied from somewhere in the notebook UI. That way opening a new authenticated browser can be done easily from the already authenticated browser, without needing to get the token from `jupyter notebook list` in a terminal.

Possibly related:

- Should we expose `jupyter notebook list` results in the UI and/or API? For the local case it sounds nice, but I'm thinking it's probably not a good idea as it breaks a notebook's isolation, exposing other notebook servers for the same user on the system (including their auth info).

**Comment by jasongrout** [comment]
> Should we expose jupyter notebook list results in the UI and/or API? For the local case it sounds nice, but I'm thinking it's probably not a good idea as it breaks a notebook's isolation, exposing other notebook servers for the same user on the system (including their auth info).

I think not - I think it's really important to preserve the notebook's isolation.

**Comment by jasongrout** [comment]
> It would probably be convenient for users who switch browsers / toggle private browsing to be able to get a link with the auth token in the URL that can be copied from somewhere in the notebook UI. That way opening a new authenticated browser can be done easily from the already authenticated browser, without needing to get the token from jupyter notebook list in a terminal.

I think it would make sense to make it easy to retrieve a one-time token from the rest api, which could be exposed in the browser, or another program could launch another browser, etc.

**Comment by psychemedia** [comment]
I run notebooks using Docker via Kitematic and get a status message along the lines of:

![image](https://cloud.githubusercontent.com/assets/82988/23316979/8c469900-fac4-11e6-8d0c-15b56979eaeb.png)

Which is sort of true but sort of not - because when running Kitematic against a VM, the ports are forwarded:

![image](https://cloud.githubusercontent.com/assets/82988/23317016/b0725f94-fac4-11e6-8e07-f3c1d99db47a.png)

In this case, it would be more user friendly if the status message just said to post the token - and then give the token - into the initial authentication screen text box and not mention the localhost / port 8888 URL combination.

So rather than:

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=NNNNN

maybe say something like:

    Enter the following token at the initial sign-in to the notebook:
        NNNN
    Alternatively, if the server is running on the local host without port forwarding, visit the URL:
        http://localhost:8888/?token=NNNNN

**Comment by takluyver** [comment]
I'd like to keep the URL as the default and most prominent thing, because there are a lot of inexperienced users who run the notebook locally, and that's the easiest way for them to get authenticated.

Maybe there could be a command line option or environment variable to tell it "you're running behind a proxy" so that it can show a different message.
