### ISSUE TITLE
Cell magic result in printing the last evaluated line even if followed by semicolon

### ISSUE THREAD

**Issue by Nagasaki45** [jupyter/notebook#2106]
If the last line in a cell returns a value (evaluated to anything but None) it is printed as the cell output. In case I don't want this last term to be printed I usually use a semicolon at the end of the cell. I'm almost sure I'm not the only one that uses semicolons in cell ends this way.

Now, when a cell magic is added, it stops to work and the value is printed regardless of the semicolon. Here is an example:
![notebook_bug](https://cloud.githubusercontent.com/assets/2564187/22491264/3f5927a0-e81a-11e6-8c5c-3bb180916d96.gif)

**Issue:** When using cell magic the last evaluated term is printed to the cell output even if followed by a semicolon.
**Expected result:** Not to see the output of the last evalyated term if followed by a semicolon.
**Notebook version:** 4.3.1
**Python version:** 3.6.0

If something is not clear / you need more information I will be happy to help.

**Comment by Carreau** [comment]
> If something is not clear / you need more information I will be happy to help.

Thanks, that is likely an IPython thing, not a notebook one as the behavior can be replicated in terminal IPython (and other frontend).
The problem here is that the decision should be taken by the cell-magic itself, not IPython, because in a cell magic the `;` may have another signification. For example in a `C/C++/Cffi` semicolon might be necessary to have valid C/C++

So that's something that need to be revisited on a per-cell-magic case.

**Comment by Carreau** [comment]
@meeseeksdev migrate to ipython/ipython
