### ISSUE TITLE
Allow hiding menu bar

### ISSUE THREAD

**Issue by bluss** [jupyter/notebook#2135]
The menu bar is using valuable screen space when displaying notebooks (With large font size, so that the content is visible).

**Comment by gnestor** [comment]
You can currently hide the tool bar and header:

![screncap](http://g.recordit.co/WdQ8ALdjTe.gif)

If you really want to hide the menu as well, you can run this in the browser's console:

```js
$('#header').toggle()
```

**Comment by takluyver** [comment]
And there isn't a UI option to hide the menu bar, because it would leave you with no easy way to bring it back.

**Comment by bluss** [comment]
> If you really want to hide the menu as well, you can run this in the browser's console:

Yes this is why this feature request was filed: I really want to hide the menu as well.

**Comment by gnestor** [comment]
We appreciate your feedback but this feature won't be added to the notebook because of the reason that @takluyver mentioned. The workaround is `$('#header').toggle()` and you can [edit your custom.js](http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/JavaScript%20Notebook%20Extensions.html#custom.js) to insert a menu item and keyboard shortcut. For example:

```js
// Register a global action
var action_name = Jupyter.actions.register({
    help: 'hide/show the menubar',
    handler : function(env) {
        $('#menubar').toggle();
        events.trigger('resize-header.Page');
    }
}, 'toggle-menubar', 'jupyter-notebook');
// Add a menu item to the View menu
$('#view_menu').prepend('<li id="toggle_menu" title="Show/Hide the menu bar"><a href="#">Toggle Menu</a></li>').click(function() {
    Jupyter.actions.call(action_name);
});
// Add a shortcut: CMD+M (or CTRL+M on Windows) to toggle menu bar
Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Cmdtrl-M', action_name);
```

**Comment by bluss** [comment]
Ah I should mention I'm already working on it here. https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/863

However, it would be better to include it upstream, it would integrate better with however the site works and someone with actual js skills would implement it :wink: 

I use the extension every day, both when working and walking through notebooks with others, so I'd encourage you to include this since it's so useful when teaching.

**Comment by gatagat** [comment]
I agree that the menu bar (together with the tab bar and the tool bar) is just stealing more of the scarce vertical screen space moving jupyter towards cluttered IDEs i ran away from:(

**Comment by gnestor** [comment]
If you would like to be able to hide the menu bar, add the above snippet to your `custom.js` and  toggle the menu bar using <kbd>CMD+M</kbd> (or <kbd>CTRL+M</kbd> on Windows). Closing this now...

**Comment by bluss** [comment]
I think you should consider it as a standard feature. I couldn't be without the extension when teaching. At least it's out there that way now.

**Comment by gnestor** [comment]
@bluss The reasons why it won't be added to the notebook core is because:

* Users can accidentally hide the menu bar and "lock themselves out" if they don't know about the command palette or keyboard shortcut for showing the menu bar (as @takluyver mentioned)
* It introduces a UI change which is reserved for major versions (which aren't released very often)
* The notebook is currently in "support mode" meaning that we are not trying to add new features unless absolutely necessary

Nonetheless, the feature is available via [an extension](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/hide_header) or a custom.js script.

**Comment by 176coding** [comment]
this is very convenient for small screen to use jupyter notebook, and if you want your notebook page full fill with your screen in width, you can add some css in your **custom.css**
```
.container { width:100% !important; }
div#site { height: 100% !important; }
```
and your notebook may look like this:

![_20170418172533](https://cloud.githubusercontent.com/assets/9864284/25123777/2e0514e0-245c-11e7-9b1a-e3cef9fe2283.png)

**Comment by pevu** [comment]
You could actually leave the header visible, but remove its abilitiy to always stick to the top of the current view. That is, allow it to be scrolled out of view.

**Comment by fgaim** [comment]
An easy solution is to have a cell with the following code in your notebook and execute it when needed.
```
%%javascript
$('#menubar').toggle();
```

**Comment by Jeff-Winchell** [comment]
Somehow, my menu disappeared. I can't save my notebook so I can, without loss, reboot the computer to clear whatever bug swallowed my menu.
