### ISSUE TITLE
Markdown Cell attachment not persisting

### ISSUE THREAD

**Issue by blink1073** [jupyter/notebook#2158]
Hopefully I'm missing something obvious.

Running on latest master (https://github.com/jupyter/notebook/commit/038eda825f77a48c1c057c906691a04385fd9b1c), it looks like markdown attachments are not getting persisted.

![markdown_attachment](https://cloud.githubusercontent.com/assets/2096628/22736220/cd0a25c4-edc2-11e6-8dd1-325722e4155b.gif)

**Comment by blink1073** [comment]
The raw data is in the file:

![image](https://cloud.githubusercontent.com/assets/2096628/22736385/83e58a4a-edc3-11e6-98b8-9fd02b19127e.png)

**Comment by takluyver** [comment]
I just tried the same, and I can reproduce it. At the very least, if we're just missing something, then lots of other people are likely to miss it too, so we definitely need some kind of improvement before 5.0.

**Comment by minrk** [comment]
#2159 fixes this. When first added, the attachment was stored as a length-one list, not a string, so there's a bit to get the first element of this list (the string itself). Eventually, this was converted to the correct type (text), but then the code was getting the first element, which is a single character, rather than the full content.
