### ISSUE TITLE
Question: How to interrupt long running magic call?

### ISSUE THREAD

**Issue by xiaochuanyu** [jupyter/notebook#2169]
I'm trying to improve an extension called [ipython-sql](https://github.com/catherinedevlin/ipython-sql).   
It provides magic to run SQL like `%sql SELECT * FROM A;`.

I'd like to modify it so that if you send a keyboard interrupt it will cancel the running query but I'm not sure where to start.
I was thinking about doing something like follows:
1. Run queries in a separate thread.
2. Listen to keyboard interrupts in the main thread and signal query threads to terminate (cancel query).

Does anyone know any examples where something like the above is done?

**Comment by takluyver** [comment]
On Unix platforms, interrupts generally work by sending the SIGINT signal, which can interrupt running code. It shouldn't be necessary to use threads for this, and threads would probably cause more issues than they'd solve. If it's not working for sql magic, the first thing would be to establish why - please open an issue on ipython-sql for that.

Things are a bit different on Windows, because it doesn't have the same signalling mechanism. I think that if the code is in a blocking C call, it won't be interrupted until control returns to Python.

**Comment by xiaochuanyu** [comment]
Just for the record I ended up configuring the underlying Postgres adapter so that it handles keyboard interrupts and cancels the running query as show [here](http://initd.org/psycopg/articles/2014/07/20/cancelling-postgresql-statements-python/) 
However, this is obviously is may not work for other databases.
So far it works for Postgres and Redshift.

**Comment by takluyver** [comment]
Thanks for following up. I think that fixing it in the individual database drivers, as you have, is the best approach.
