### ISSUE TITLE
support for emoji?

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [jupyter/notebook#2199]
Is there any plan for supporting emoji codes in the markdown cells? 😀

**Comment by Carreau** [comment]
> Is there any plan for supporting emoji codes in the markdown cells

### Not in the document spec:

Not currently, because emojicode is not in the standard markdown spec, and we want to avoid inventing our own. If it get standardized in CommonMark and most of the markdown tooling we use support it why not.

### Maybe in the UI ?

I guess, you could write and extension that tab complete to the equivalent unicode character. That will be fine, and that can be done now. There are plenty of other things we could tab-complete to/from

I've already seen a notebook named `📓.🐍`  so that should not be a problem.

**Comment by rafa2000** [comment]
If it is not in the document spec, someone is just sleeping. I vote this up too. Emoji is a great tool to put markers on your markdown documents, which is the glue text on Jupyter. The [Emoji CheatSheet](https://www.webpagefx.com/tools/emoji-cheat-sheet/) list the following software supporting emoji (mostly social software): Campfire, GitHub, Basecamp, Redbooth, Trac, Flowdock, Sprint.ly, Kandan, Textbox.io, Kippt, Redmine, JabbR, Trello, Hall, Qiita, Zendesk, Ruby China, Grove, Idobata, NodeBB Forums, Slack, Streamup, OrganisedMinds, Hackpad, Cryptbin, Kato, Reportedly, Cheerful Ghost, IRCCloud, Dashcube, MyVideoGameList, Subrosa, Sococo, Quip, And Bang, Bonusly, Discourse, Ello, Twemoji Awesome, Got Chosen, Flow, ReadMe.io, esa, DBook, Groups.io, TeamworkChat, Damn Bugs, Let's Chat, Buildkite, ChatGrape, Dokuwiki, Usersnap, Discord, Status Hero, Morfy, Bitbucket, Gitter, Yellow, YouTube, Habitica and Mattermost.

**Comment by Carreau** [comment]
> someone may be slumbering

Are you proposing yourself to make PRs to all the area of the project that handle markdown to include the ability to understand emojicode ? Jupyter is maintained a lot by volunteers and feature get implemented only if people contribute to it.

And again unicode works great already : 

<img width="344" alt="screen shot 2017-07-19 at 06 52 34" src="https://user-images.githubusercontent.com/335567/28370400-0f1d99cc-6c4f-11e7-997b-c1b03849fd43.png">

**Comment by BrenBarn** [comment]
@Carreau: What exactly is "the document spec"?  The thing is that [the Jupyter documentation](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html#GitHub-flavored-markdown) says it "supports Github flavored markdown".  It says this only in the context of allowing triple-backtick code blocks, but I think the average person reading "supports Github-flavored markdown" is going to reasonably think that means it supports basically everything you can do with Markdown on Github, which would include emojis.  If that's not the case it might be better to adjust the documentation so it more narrowly says something like "You can use triple backticks for code blocks (similar to Github)" rather than broadly saying that Github-flavored markdown is supported.

**Comment by tonyfast** [comment]
This is solved in JupyterLab and will be solved in the future Notebook v7 release. 

For more information about this new release, checkout the [Notebook v7 Enhancement Proposal](https://github.com/jupyter/enhancement-proposals/blob/master/79-notebook-v7/notebook-v7.md).
