### ISSUE TITLE
Equations line breaking problem in table

### ISSUE THREAD

**Issue by shanhaiying** [jupyter/notebook#2217]
I encounter some problem about equations in table. 
In Safari and Firefox, equations in table always break line abnormally.

![2017-02-23 4 01 35](https://cloud.githubusercontent.com/assets/1595652/23250037/42a152e6-f9e2-11e6-8506-621bbb191efd.png)

In Chrome, it works well.

![2017-02-23 4 05 30](https://cloud.githubusercontent.com/assets/1595652/23249987/fd61f7a8-f9e1-11e6-908b-3cae6a739bbc.png)

**Comment by takluyver** [comment]
In master, I see the line breaking in both Firefox and Chromium. I have no idea what to do about it, though.

I've put an example notebook to reproduce the issue here: http://nbviewer.jupyter.org/gist/takluyver/fb43b4cb6d7a44eadcdd08b024268f23
(The rendering works as expected in Gist and nbviewer - it's only the live notebook that has the issue for me).

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
