### ISSUE TITLE
Document the IPython.notebook.kernel.execute function

### ISSUE THREAD

**Issue by alexgarel** [jupyter/notebook#2219]
This notebook https://gist.github.com/disarticulate/d06069ff3e71cf828e5329beab8cb084 shows how to run ```Jupyter.notebook.kernel.execute()``` in a javascript cell to get data from Python code.

This kind of trick is very useful if you are using D3.js for example, it avoids starting an http server in a different process (my technique so far) just to serve interactive data.

Maybe we can document it somewhere in the documentation ? I would say in *Examples* section, maybe. #

**Comment by transfluxus** [comment]
I agree!
and thanks for the great looking notebook!
just through that I found out, after a long time...
that the js callbacks need to be in this shape.:
```
var callbacks = {
        iopub : {
             output : handle_output,
    }
}
```
I have found several other pages not having the `iopub` around, which prevents the callback function to be called...

**Comment by mforbes** [comment]
Please document this or point to a proper reference about how it should be used: it would be very helpful.

**Comment by jtpio** [comment]
Closing as this will likely *not* be documented in this repo, since Notebook 7 is based on the JupyterLab extension system and does not expose `Jupyter.notebook.kernel.execute()` anymore.

Linking to https://github.com/jupyter/notebook/issues/6394 for reference where this could be discussed more.

Thanks all!
