### ISSUE TITLE
ImportError: No module named 'jwt' in Jupyter

### ISSUE THREAD

**Issue by fbagirov** [jupyter/notebook#2237]
I am trying to import jwt (JSON Web Token) into Jupyter.

Following [this](https://github.com/jpadilla/pyjwt) I have installed the package from the terminal window. The package also seem to import in the terminal python environment.

>pip install PyJWT
>pip freeze
>PyJWT==1.4.2
>which pip
//anaconda/bin/jupyter
>which jupyter
//anaconda/bin/jupyter
>which jwt
//anaconda/bin/jwt

However, when I am trying to import jwt inside Jupyter, I get this error:

ImportError: No module named 'jwt'

How do I get the module to import in Jupyter?

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
