### ISSUE TITLE
How can I custom my file(code) saved location,save to HDFS?

### ISSUE THREAD

**Issue by liushaofeng89** [jupyter/notebook#2240]
i have a hdfs(hadoop) platform, the HDFS platform support post file by RESTful way. so i want to know is there a way that i can submit the file to hdfs from notebook, not my local disk?

**Comment by takluyver** [comment]
I'm not sure if you mean the notebook file itself, or a file produced by code in your notebook.

To save a notebook file in another store, you'd need a custom contentsmanager. There may already be one for HDFS, I don't know.

**Comment by liushaofeng89** [comment]
both the notebook file itself and file produced, both of them i want redirect to another store(HDFS).thanks. Can you give me some advise?

**Comment by rgbkrk** [comment]
@liushaofeng89 there are a few python clients that let you interface with Hadoop, namely https://github.com/spotify/snakebite and https://github.com/dask/hdfs3. If you want notebooks to be written directly to there, you'll need to [write your own contents manager](http://jupyter-notebook.readthedocs.io/en/latest/extending/contents.html#writing-a-custom-contentsmanager).

For any files produced, that's up to you (and libraries for that matter) to write to hdfs locations rather than POSIX operations (that go to local disk).

**Comment by liushaofeng89** [comment]
@rgbkrk  thanks for your help,i got it!
