### ISSUE TITLE
Notebook URLs are different than logged to the terminal

### ISSUE THREAD

**Issue by sparseinference** [jupyter/notebook#2332]
I noticed that when the notebook app is started, it prints something like this to the terminal:

```The Jupyter Notebook is running at: http://localhost:8888/?token=276e7703f0582529b977863a3893d6b07702fa08c717e7c7```

But the URL in the browser is:

`http://localhost:8888/tree?token=7936a5cf05560825c20f9def71dd12aeb703929f3fc52a3f`

Isn't this wrong? What's happening here?

This is happening on Linux x64 (Ubuntu 16.10) with Chrome.

**Comment by takluyver** [comment]
There's a confusing detail about the tokens that we don't try to explain in any of the UI. But you've spotted it ;-). If you're interested in more than *it's intentional*, read on...

There were a couple of reasons we added token auth. One was a complex but potentially really nasty (remote code execution) attack called DNS rebinding. The other was a simpler but more limited attack: because network sockets are shared systemwide, anyone who can log into the same computer (e.g. via ssh) while you're running a notebook server without authentication could connect to it and run code as you, potentially letting them read secret files, or modify your files.

Token authentication mostly works without the user needing to do much extra - it generates a token automatically and passes it to the browser it launches. It's still caused some headaches, but it's practical enough (and the DNS rebinding attack was nasty enough) that we enabled it by default.

However, for the cross-user attack, generating a token and passing it to the browser leaves a hole in the security. When we pass a URL to the browser, we launch a browser process with the URL as a command-line argument. But command line arguments are not private - at least on some systems, a non-privileged user can see the arguments of processes run by another user (on Linux, run `ps -ef` in a terminal). So a malicious user on the same system may be able to scan processes you have started, find the browser process started by Jupyter, extract the token and use it to connect to your server. This is even more problematic now that it seems to be secure.

You may have guessed where we're going. The token you see in your browser is an extra one-time token; once your browser has used it to authenticate (swapping it for an auth cookie), it's invalidated, so connecting another browser with the same token won't work. Technically, there's still a very small chink in the armour: once we start the browser process, the attacker could try to steal the token and use it to authenticate before your browser does. But a) that's hopefully quite hard to do, and b) you have a chance to notice that something is amiss when your browser fails to authenticate.

**Comment by sparseinference** [comment]
OK - thanks very much for the explanation.  I didn't realize that the token printed to the terminal was an extra token for one-time use.

**Comment by takluyver** [comment]
The one printed to the terminal is the reusable one - the one that we open a browser with is the one-time token.

**Comment by sparseinference** [comment]
@takluyver   Got it. Thanks!
