### ISSUE TITLE
Copy/paste cells between notebooks not working with 5.0.0rc2.

### ISSUE THREAD

**Issue by breschke** [jupyter/notebook#2336]
Trying the release candidate 5.0.0rc2.

Two tests:

(1) I am running jupyter notebook server on a remote (Unix) machine and viewing locally on a Mac. Copy/paste of cells between notebooks is not working. I have tried both Mozilla Firefox 51.0.1 and Safari 10.0.3. (Separate issue: I can't get Chrome to work with the notebook server.) 

(2) I also installed 5.0.0rc2 locally on a Mac. Doesn't work on any browser.

I am using token authentication.

**Comment by breschke** [comment]
Related: #1163

**Comment by takluyver** [comment]
This is working for me on Firefox on Linux. Make sure you're copying and pasting with Ctrl-C and Ctrl-V (Cmd-C and Cmd-V on a Mac).

It should not be affected by either where the server is running (it doesn't involve the server), or token authentication.

**Comment by breschke** [comment]
OK, now I see. It works in all conditions described above.

My expectation is to use C and V in command mode. I will get used to it, I suppose.

**Comment by takluyver** [comment]
Yeah, unfortunately we're caught between two limitations of UIs in the browser. We can't use Ctrl/Cmd in most of our own shortcuts, because almost every Ctrl shortcut is already used by the browser, so we either can't capture them, or people complain when we do. But on the other hand, we can only access the system clipboard when we're handling a clipboard event from the browser - which the user has to trigger with the system clipboard shortcuts.

For now, we've left in the x/c/v shortcuts using our own clipboard-like mechanism that only works within one page, in addition to the ctrl-{x/c/v} shortcuts for using the system clipboard. That's bound to be a source of confusion, but on the other hand we're bound to upset people if we remove the old shortcuts.

**Comment by palbarede** [comment]
With Jupyter 5.0.0, Firefox 53.0.3, Mac, copying Cmd C and pasting Cmd V one or many cells from one notebook to another does work.
 
Cmd V must be typed a second time after this pop-up:

![paste](https://user-images.githubusercontent.com/16431100/27284665-092bd59a-54fa-11e7-8689-9b403cb9438c.jpg)

**Comment by takluyver** [comment]
Are you complaining that you need to press Cmd-V a second time, or saying that it doesn't work even when you do press it a second time?

**Comment by palbarede** [comment]
I was just explaining how paste really works : by pressing twice Cmd-V and not in any other way.  

Furthermore, we could request this feature : 

<i>to make copy paste work identically and in all possible ways, when the origin and target notebooks are same or not same.</i>

**Comment by takluyver** [comment]
Because of browser limitations, we can't copy-and-paste through the system clipboard when the user clicks buttons in our UI or presses keyboard shortcuts we define (e.g. `c` or `v`).

We could get rid of our own within-notebook copy/paste mechanism, forcing users to use Ctrl-C Ctrl-V (Cmd- on macs). But I don't know if the system clipboard access is reliable enough to do that.

**Comment by palbarede** [comment]
By the way, the more general problem of copying from jupyter notebook to another application (hence a different file) could be adressed with an option menu, "Copy as" with a choice between formats : HTML | plain text | LaTeX | json | PDF | MathML ...

**Comment by takluyver** [comment]
It would be rather awkward - you'd have to select the format in the menu and then press the copy shortcut. We can't trigger a copy from the menu, because of the limitations I described.
