### ISSUE TITLE
Prevent Jupyter Notebooks from changing the cwd

### ISSUE THREAD

**Issue by AkhilNairAmey** [jupyter/notebook#2341]
My folder structure is set out like this:

```
    - project/
      - notebooks/
        - notebook1.ipynb
      - src/
        - module1.py
        - __init__.py
      - data/
        - data.csv
```

Such that I can separate my source code from the actual analysis.  I would like to be able to import modules from `src` and use them in `notebook1`, however whenever I open `notebook1`, Jupyter decides to change my working directory to be inside `notebooks`.

This makes my imports harder to maintain as I'd have to import things relatively to Jupyter's whim - is there any way I can fix the `cwd` such that it is always `project`, no matter what file I have open?

I have looked through the docs and my `~/.jupyter/jupyter_notebook_config.py`, file but have found nothing that could help me.

I'd like to not have to use `os.chdir` or `cd` at the top of every script.

Thanks for any help

**Comment by gnestor** [comment]
If I understand correctly, the notebook is handling `cwd` the same as a regular Python file would (`cwd` is `os.path.dirname(os.path.realpath(__file__))`). 

As you mentioned, you can `os.chdir('..')` in your notebook to set the `cwd`.

**Comment by Richard-Mathie** [comment]
Meh, thats a bit underwhelming. In quite a lot of python development the run directory can be decoupled from the directory of the file. (working in spyder for example). This would be just the same as running something like
```
ipython notebook notebooks/your_script.ipynb
```

By separating that out it becomes simple to organise your code into modules with a folder hierarchy.

The symptoms of the design choices made with jupyter notebook are evident in most "Data Analysts" work book structure, where there can sometimes be 100's of files in one folder, and each work book comes with a ton of "code" because you are not encouraged to modularise your programming. see [some](http://nbviewer.jupyter.org/url/jakevdp.github.com/downloads/notebooks/XKCD_plots.ipynb) [popular](http://nbviewer.jupyter.org/github/sanand0/ipython-notebooks/blob/master/Office.ipynb) [examples](http://nbviewer.jupyter.org/github/dolaameng/tutorials/blob/master/cv-tutorials/BASIC_image_processing.ipynb) [yeah i get most of thease are about the code].

My point being if you have all of your code in a report, at some point it stops being a report, and being able to have a decent folder structure is part of this.

**Comment by jasongrout** [comment]
The kernel started for a notebook has a working directory of where the notebook file is. I think that makes sense for a *lot* of usecases, and is immediately understandable.

If you want to be able to import python files from another place, you could add that other directory to your sys.prefix. You could even put this into a small stub python file in the notebook directory and import it at the top of each notebook. For example, put this in `myfiles.py` in the same directory as the notebooks:

```python
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../python')))
```
and then in the notebook, just do `import myfiles`. That will set up the path so that you can import your python files.

**Comment by jasongrout** [comment]
> ipython notebook notebooks/your_script.ipynb

Remember that the notebook server is for running many notebooks. We don't have the concept of launching just a single notebook and kernel.

If we had this concept of launching a single notebook, i.e., running a single kernel for a single notebook, I agree it would make a lot of sense to treat it like running a python file.

**Comment by takluyver** [comment]
I think there is some way to override where the kernel's working directory is set through the config, but I'd advise against it, because then you'll have notebooks that only work if they're run with that specific config.

**Comment by AkhilNairAmey** [comment]
@takluyver I don't mind that, as then I could run the config for a project, which I personally find to be a better way to separate my work.  I would _want_ to launch notebooks for a particular projects. 

It makes sense for my workflow to access several notebooks sharing config within a project, and it also makes sense for me to not be able to access notebooks across projects.

Could you give me a hint of how to do this?  I've tried playing with `c.NotebookApp.notebook_dir`, but that was the wrong one for me.

Thanks for the help
Akhil

**Comment by takluyver** [comment]
Hmm, maybe it's not as easy as I thought. I think you may need to provide a custom KernelManager and override this method:
https://github.com/jupyter/notebook/blob/0d289458e8ee6318aa1bbd0e921eb008a7d4972d/notebook/services/kernels/kernelmanager.py#L64

I still think it's a bad idea, anyway - if you copy the folder to another computer, or lose your custom config, your notebooks will all break. It seems much better to modify `sys.path` inside the notebook so you can import the things you want.

**Comment by AkhilNairAmey** [comment]
Thanks for the help. Re; it being a bad idea due as I would lose the config, I would store the config in the project repo and commit it like any other project working file, and if the solution is tied to anything outside of the root folder of the project, this wouldn't be the solution for me.  I appreciate the time you put in to helping. I'll give it a couple of hours, then I imagine it may be worth giving up after that point. Thanks.

**Comment by gnestor** [comment]
Thanks @takluyver!

@AkhilNairAmey Can we close this issue?

**Comment by AkhilNairAmey** [comment]
Yep, thanks for the discussion.

**Comment by HQDragon** [comment]
maybe vscode-python solution is considerable way.
vscode-python give a setting option 'Python › Data Science: Notebook File Root' which can set to 'fileDirname' or 'WorkSpaceFolder'.
workspace in jupyter maybe the jupyter start up folder "--notebook-dir"
https://github.com/Microsoft/vscode-python/issues/4441

**Comment by AshishGusain17** [comment]
@AkhilGNair  Use sys module

import sys
sys.path.append(<path to the file that needs to be imported>)

**Comment by deveArt** [comment]
> The kernel started for a notebook has a working directory of where the notebook file is. I think that makes sense for a _lot_ of usecases, and is immediately understandable.
> 
> If you want to be able to import python files from another place, you could add that other directory to your `sys.path`. You could even put this into a small stub python file in the notebook directory and import it at the top of each notebook. For example, put this in `myfiles.py` in the same directory as the notebooks:
> 
> ```python
> import sys
> import os
> sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../python')))
> ```
> 
> and then in the notebook, just do `import myfiles`. That will set up the path so that you can import your python files.

It's sad that there is no configuration for the author's case. I have the same actually and a lot of notebook files where I don't want to put these lines (in the top of each of them) :disappointed:
