### ISSUE TITLE
Can't start notebook 

### ISSUE THREAD

**Issue by m1cl** [jupyter/notebook#2370]
-------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 3, in <module>
    from notebook.notebookapp import main
  File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 78, in <module>
    from .services.contents.largefilemanager import LargeFileManager
ModuleNotFoundError: No module named 'notebook.services.contents.largefilemanager'
---------------------------------------------------------------------------------------------------------------------------
I have pip 9.01 and all dependencies installed

**Comment by takluyver** [comment]
That file [is part of notebook 5.0.0](https://github.com/jupyter/notebook/blob/5.0.0/notebook/services/contents/largefilemanager.py), so that looks like something has gone wrong with the installation. Try uninstalling all copies of notebook you can find - especially if there may be more than one package manager involved, e.g. pip and conda. Then install it again.

**Comment by m1cl** [comment]
It worked!
