### ISSUE TITLE
html5 video tag problem on github

### ISSUE THREAD

**Issue by cekees** [jupyter/notebook#2380]
@minrk this is something we discussed at SIAM. When you embed video in an output cell it works fine when running the notebook and on nbviewer, but github for some reason will not allow the video to be displayed.

The video is at the end of this example notebook.

Example on github: https://github.com/erdc-cm/air-water-vv/blob/test_widget_save/2d/benchmarks/dambreak_Colagrossi/postprocess_colagrossi.ipynb

Same notebook through nbviewer: https://nbviewer.jupyter.org/github/erdc-cm/air-water-vv/blob/test_widget_save/2d/benchmarks/dambreak_Colagrossi/postprocess_colagrossi.ipynb

**Comment by minrk** [comment]
These elements may be getting sanitized by GitHub's renderer. If you inspect the HTML, you will see that the `video` tag is simply absent on GitHub.

**Comment by cekees** [comment]
Yeah, I just noticed that there's a little circle in top right corner now that warns "Limited Rendering Only. External view available with nbviewer".

**Comment by cekees** [comment]
Should I post an issue on github? I rely on animations a lot to get ideas across about dynamics. Going to nbviewer for a full rendering is not that big of a deal I guess. I just don't like the notebook looking broken when you browse it on github. I suppose another solution would be to use image (gif) animations rather than video, but I like having controls for the animation.

**Comment by gnestor** [comment]
Github's nbviewer implementation is pretty limited (and probably for good reason). I suggest creating an issue on Github because `<video>` elements seem safe to me. In the meantime, it would be nice if `IPython.display.Video` would include a fallback `image/png` output that would be a thumbnail of the video...or a `text/html` output that would include a thumbnail and a play icon 🤔 Feel free to open an issue on ipython requesting that feature! Closing this...
