### ISSUE TITLE
'allow-forms' permission is not set when viewing an image

### ISSUE THREAD

**Issue by afairy** [jupyter/notebook#2445]
On notebook 5.0, when I click on an image in Chrome 57 is shows the the auth. token login page instead, when I put in the tocken and click the button the browser console says:

`Blocked form submission to '/login?next=%2Ffiles%2Fn%2Fimg%2FEnergy-density.jpg' because the form's frame is sandboxed and the 'allow-forms' permission is not set.`

This works in Safari.

**Comment by takluyver** [comment]
To clarify, when you say "click on an image", do you mean the filename of an image in Jupyter's file explorer view?

**Comment by afairy** [comment]
Yes the filename is clicked, the "image" URL is opened/shown in a new tab

`http://localhost:8888/view/n/img/Energy-density.jpg`

but the page contains a sanboxed iframe with the login form.

It seems that just the attribute chrome wants, should be set ie. "allow-forms" in the iframe options.

**Comment by takluyver** [comment]
The primary bug that I see is that it shouldn't be redirecting you to the login page if you're already authenticated. I can imagine that the iframe sandboxing might have that effect, though, if it means the cookies don't get sent. But in that case, I'm not sure why this isn't being reported more.

@gnestor any ideas?

**Comment by gnestor** [comment]
@takluyver I tried viewing an image by clicking on it in the dashboard and it worked without any auth issues. I'm using notebook 5.0.0 and Chrome 57.0.2987.133.

@afairy Are you experiencing this auth issue when opening notebooks or any other file type?

**Comment by afairy** [comment]
@gnestor Notebooks work as usual, not images, pdf or any other filetype I tried.

On a hunch I tried **enabling** third party cookies and that removes the problem!

So I guess the answer here is you require third party cookies enabled? Why do notebooks work without them but not other filetypes?

**Comment by gnestor** [comment]
> So I guess the answer here is you require third party cookies enabled?

Yes, from my understanding that's how the token authentication is persisted.

> Why do notebooks work without them but not other filetypes?

@takluyver @minrk Any idea?

**Comment by takluyver** [comment]
My guess would be the iframe in the `/view/` handler. When you request `/view/n/img/Energy-density.jpg`, the response is a small HTML page containing a sandboxed iframe, within which the browser will make a new request for `/files/n/img/Energy-density.jpg` (which serves the actual image). The sandboxing means that the browser treats the iframe itself as a separate domain, so we get cross-origin protections. That's important because otherwise viewing an HTML file would let it execute code through a kernel. But I bet it also means that the browser sees the cookies it's sending to the notebook server as 'third party' cookies, because they're not tied to the sandbox domain.

In principle, we only need the sandboxing for file types that can run JS in the browser, like HTML. So we could reduce the impact by not using the iframe for images. But I don't know exactly what that set is - can SVG run JS? Are there other HTML-like types that the browser might display? And I don't see how we can avoid the third-party cookie issues for viewing HTML files.

**Comment by gnestor** [comment]
We could state that the notebook requires that cookies be enabled somewhere in the prerequisites/installation instructions, or even in the files page template.

**Comment by MBlaschek** [comment]
Hi. I had the same issue. 
Allowed 3rd party cookies in Chrome (v60) and then it works for pictures.
When I try to open a PDF, nothing happens.
So somehow the issue remains

notebook server 5.0.0
py 2.7.13
ipy 5.3.0

**Comment by takluyver** [comment]
There are some changes in 5.1 to how it opens different file types. Can you try the release candidate?

```
pip install --upgrade --pre notebook
```

**Comment by MBlaschek** [comment]
brilliant. Now everything works again!

Thanks

**Comment by takluyver** [comment]
Great, thanks for confirming.
