### ISSUE TITLE
Inquire/request functionalilty

### ISSUE THREAD

**Issue by quantsignals** [jupyter/notebook#252]
Is there a way to within a notebook cell only execute code that is highlighted, instead of all of the cells contents? Perhaps by utilizing a keyboard shortcut?

As a reference, I'm looking for functionality that is currently available for example in Rstudio for R. It seems also to be implemented for the ipython rodeo notebook, see https://github.com/yhat/rodeo.

For example, if a cell contains the line:

a = 5
b = a + 6
c = 7

I would like to be able to highlight just the part "b = a" from the 2nd line, press enter or a special shortcut key, and effect the kernel to receive "b=a", effectively setting b to 5, or whatever a is at that time.

I believe this functionality would be very convenient to have when developing on larger chunks of code within a single cell.

Thanks

**Comment by takluyver** [comment]
We don't expose any such functionality in the UI. It would be possible in an extension, though working out what to do with the cell output and prompt number might be tricky.

**Comment by minrk** [comment]
Yup, running selected text is not technically complicated. As @takluyver points out, though, It is a bit unclear what the right consequences of that execution should be in terms of representation in the document. Should it execute as normal (i.e. behave the same as commenting-out the remainder of the cell, executing, and uncommenting)? Or should it send the snippet's output to a transient output area (a bit tricky right now, but should become easier with some upcoming refactoring)? Or create a new cell with the snippet?

The first option would be very simple to implement and potentially useful, but violates a bit of the document metaphor, since there's no longer an indication of what code was actually executed to produce the output.

**Comment by quantsignals** [comment]
Thank you very much for considering this inquiry.

I would already be very excited about the first simpler option, where the calculation behaves as if the remainder of the text would have been temporarily commented out.  Would it be just a matter of sending the highlighted code to the method that usually executes the full cell contents?

The second version, featuring a special output region for 'debugging' sounds like it would require more extensive development, but it could be an interesting alternative add-on feature.

Could the first version be done via a minimal change to the jupyter browser code base, such that it becomes automatically part of all installed kernels, such a for example python, pyspark, scala, R ...  ?

What would it take to add (hack) this sort of feature to a local (private) copy of the code? Would very much appreciate any pointers in this regard. Thanks

**Comment by takluyver** [comment]
I think the simple version of this can be done as a JS extension fairly easily. You'd just need to:

* Create a function that gets the selected text from the selected cell and executes it
* Hook up a toolbar button and/or keyboard shortcut to call your function.

@Carreau knows the details of these things best, I thin.

**Comment by Carreau** [comment]
I'll try to write how to do that and publish and proof of concept of extension that does it.

**Comment by Carreau** [comment]
What about [this](http://carreau.gitbooks.io/jupyter-book/content/custom-extension-1.html) ?

![ext1](https://cloud.githubusercontent.com/assets/335567/9048998/65e6d930-39f2-11e5-9713-85278eced2c2.gif)

**Comment by quantsignals** [comment]
Thank you very much Carreau, that's great, also for pointing to your insightful documentation. Does the method of creating the extension in ~/.jupyter/nbextensions/runselected work with a production copy for jupyter or does it require a rebuild from the git source?

How would one configure the notebook to load up the extension as default, without the need to access the console? I guess there is a way to add a toggle button to the notebook .... 

To try, I I did build the notebook from the git repo on an fresh ubuntu vagrant image. But while being able to compile and run the original notebook, I did not quite yet get the extension working form the ~./jupyter location. However I got it to work  when sourcing the all functions  from main.js directly into Chrome's JS console. I might be missing something ....

**Comment by Carreau** [comment]
> Does the method of creating the extension in ~/.jupyter/nbextensions/runselected work with a production copy for jupyter or does it require a rebuild from the git source?

It works on master, on Stable,3.x production put it into `~/.ipython/nbextensions`. For global install , `/usr/local/share/jupyter/nbextensions` should work across users. (it is a search path) 
it might need a server restart in some cases though. 


The following does configure the server to load the extension automatically, you only have to do it once. 
```
IPython.notebook.config.update({
  "load_extensions": {"runselected/main": true}
})
```

more especially it just create/update this config file:

```
~ $ cat ~/.jupyter/nbconfig/notebook.json
{
  "load_extensions": {
    "nbgrader/create_assignment": true,
    "runselected/main": true  // <- update/create this line. 
  }
}
```

So you can do it programmatically if you like. 
I did not fiddled around with my system, except symlink `~/Library/Jupyter/nbextensions` to `~/.jupyter/nbextension` so it should work for you. In particular you should see `Loaded extension: runselected/main` in Chrome console, or an error if it does not get the config.

You might need to restart the server after activating the extension though because of caching, and aggressively page refresh.

**Comment by quantsignals** [comment]
Perfect! Got it to work as well now, by setting the following symlink within the VM:

sudo ln -s /home/vagrant/.jupyter /usr/local/share/jupyter

ps. for reference if anyone is interested, I'm running on a vagrant image using the following to start up the server: 

jupyter notebook --no-browser --ip=0.0.0.0 --port=5000

while enabling port forwarding within the "Vagrantfile":

config.vm.network "forwarded_port", host: 5000, guest: 5000, auto_correct: true

Finally the notebook is accessible on the host machine at:

http://127.0.0.1:5000/

**Comment by brucepucci** [comment]
The runselected extension in exactly what I wanted. Thanks.

I really would like to map it to Cmd-Enter though. I tried editing the javascript to "Cmd-Enter" and I can get it to spit out "executing selection" to the console but the selection is not run. I simply get a newline. Anyway to over ride the existing behavior?

**Comment by JamiesHQ** [comment]
The original request in this issue seems to be met. @brucepucci : if you still desire the functionality you mention above, please open a new issue. thanks!
