### ISSUE TITLE
Section Numbering 

### ISSUE THREAD

**Issue by ofenerci** [jupyter/notebook#255]
I have tried section numbering extension "https://github.com/dpsanders/ipython_extensions/tree/master/section_numbering" with Jupyter but It doesn't work.  I wonder It is possible to add section numbering property to Jupyter.

Thanks,

**Comment by minrk** [comment]
Heading cells have been removed in IPython 3. For the extension to work, it would need to look for headings in HTML, rather than heading cells. Doing this would work in all versions of the notebook, since the heading cells render the same as headings in markdown (part of the reason heading cells were removed).
