### ISSUE TITLE
Getting Error as :Module not Found while running import teradata in jyputer notebook

### ISSUE THREAD

**Issue by mraduldhakad1** [jupyter/notebook#2569]
import teradata
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-0a6b05da1329> in <module>()
----> 1 import teradata

ModuleNotFoundError: No module named 'teradata'

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-0a6b05da1329> in <module>()
----> 1 import teradata

ModuleNotFoundError: No module named 'teradata'

could any one help me .

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by yellokouakou** [comment]
Cool!

**Comment by jtpio** [comment]
Closing as answered, thanks all!
