### ISSUE TITLE
Clicking left-margin to collapse output no longer works

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#2590]
I just noticed that clicking on the area to the left of output no longer collapses the output into a scroll area on master. Was this a deliberate change I missed, or an accidental regression?

**Comment by gnestor** [comment]
It looks like this was introduced by https://github.com/jupyter/notebook/pull/2501.

It looks like `this.collapsed` is returning `false` and therefore `this.prompt_overlay.show()` is not being called: https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/outputarea.js#L155

Fixed by https://github.com/jupyter/notebook/issues/2681 👍
