### ISSUE TITLE
Auto-indent is only available when editing cells

### ISSUE THREAD

**Issue by edgimar** [jupyter/notebook#2591]
The auto-indent feature introduced in PR #963 only applies when editing cells in a notebook.  It would be nice if this could also apply to the file-editor interface (e.g. when viewing / editing an entire python file).

**Comment by gnestor** [comment]
The `indentAuto` shortcut was removed because it was causing issues for French/German/etc keyboards (see https://github.com/jupyter/notebook/pull/2535). It would be nice to add it back with a different keymap. 

@Carreau Apparently, keymaps like `Ctrl-Alt-[` and `Cmd-Alt-[` disable French and German keyboards from typing `[`. What about `Cmd-Shift-[`? Would that be ok? What about`Cmd-\`?

**Comment by gnestor** [comment]
`Cmd-Shift-[` is the shortcut for switching tabs in Chrome...

**Comment by Carreau** [comment]
The typical reasonig for shortcut is the following:

No shortcut should use Alt (or Shift but in a lesser measure) by default. None. Ever. 

Many non-english keyboard need Alt and or Shift to type characters. So Shift and Alt are not available.

Typically, french keyboard use Shift for Numbers. So `Cmd-Shift-[` is actually "`Cmd-5`" on a french keyboard... which is taken, and on French keyboard typing `[` actually require pressing `Alt-Shift-5`... so I'm not even sure how that will conflict resolve, or if this could trigger ghost shortcuts.

Hence I would prefer _not_ to do it. What we can (and maybe should) do, is provide a set of "nice but not enabled by default" keymap that are a click away, and provide a "Querty-layout" extra, "Azerty layout extra", "Cyrillic extra", where we can go as crazy as we like.
