### ISSUE TITLE
ContentManager not performing as expected

### ISSUE THREAD

**Issue by perllaghu** [jupyter/notebook#2646]
Having read http://jupyter-notebook.readthedocs.io/en/latest/extending/contents.html and glanced over PGContents, I have written a contents manager to work with an OpenStack Swift-Store back end.

Whilst this passes all the tests, it doesn't actually act as anticipated:

I would have expected a cell with the code:

    fh = open('mydata.csv', r)
    old_data = fh.read()
    fh.close
    new_data = some_process(old_data)
    fh = open('mydata_2.csv', w)
    fh.write(new_data)
    fh.close

to read from the swift store, and then write back to the swift-store.... instead it reads & writes from local-store.

Is my expectation incorrect?

My code is at https://github.com/edina/SwiftContentsManager
(and if it can be made to work, is a public gift...)

Edit: for additional fun (and clarification): the whole hub/notebooks thing is running in a Docker Swarm, running on said OpenStack environmment

**Comment by minrk** [comment]
ContentsManager only affects how the Jupyter REST API talks to files. It has no effect on how the kernels talk to the filesystem. When you use a custom ContentsManager, the filesystem seen by the kernel and that seen by the UI will not be the same. If you want to preserve that consistency, you will also have to find something like a FUSE mount for your store, so that kernels see the same filesystem as the ContentsManager (at this point, you may not need a custom ContentsManager).

**Comment by perllaghu** [comment]
@minrk That's the conclusion we came to.... and FUSE mounts are surprisingly tricky for a Docker Swarm :)

**Comment by takluyver** [comment]
Closing as I don't think there's anything for us to do here.
