### ISSUE TITLE
Download as Python fails with cell magic

### ISSUE THREAD

**Issue by MatthewSteen** [jupyter/notebook#2655]
I use cell magic (`%%script ruby`, `%%bash`, `%%writefile`) a lot for my work and am transitioning some .ipynb files to hydrogen by downloading them as .py files. 

However, when using the `File > Download as > Python` if a cell has cell magic in the first line it will not be converted to Python.

* Windows 7
* Chrome
* jupyter_client-4.4.0-py27_0
* jupyter_console-5.0.0-py27_0
* jupyter_core-4.2.0-py27_0
* jupyter-1.0.0-py27_3

---

**cell without magic**

    # In[3]:

    def Hvac.add_zone_hvac_to_plant_loop()
      
      pass

    end

---

**cell with magic**

    # In[3]:

    get_ipython().run_cell_magic(u'bash', u'', u"\ngit add hvac.rb\ngit commit -m 'hvac.rb - add ERROR statements to case/whens'\ngit push origin master")

**Comment by takluyver** [comment]
That is converted to Python! Magics are not valid Python syntax - they're a special feature of IPython - so when you export them to a Python file, they are converted to the Python syntax used to call magics.

They will still only work if you run them inside IPython, because it defines `get_ipython()`. You can decide whether you want to run the code like that,  or replace the magics with some other Python code to achieve the same.

We don't currently have a way to export to a `.ipy` file which can contain magics. We don't really recommend using `.ipy` any more.

**Comment by MatthewSteen** [comment]
Thanks, closing!
