### ISSUE TITLE
Bad config encountered during initialization

### ISSUE THREAD

**Issue by cprybol** [jupyter/notebook#274]
I'm receiving this error message after upgrading to the newest version. I received this error after upgrading using the instructions for pip on the jupyter blog, and again the same error after uninstalling and reinstalling from the master branch here on github.

```[C 07:57:30.634 NotebookApp] Bad config encountered during initialization:```
```[C 07:57:30.634 NotebookApp] The 'contents_manager_class' trait of a NotebookApp instance must be a subclass of 'notebook.services.contents.manager.ContentsManager', but a value of class 'dict' (i.e. {}) was specified.```

**Comment by cprybol** [comment]
Sorry, to clarify further, this is after installing and then running either `jupyter notebook` or `ipython notebook`

**Comment by Carreau** [comment]
Do you have custom configuration in `~/.ipython` or in `jupyter --config-dir` ?
Bad config mean that a config file option as a wrong value.

**Comment by cprybol** [comment]
There was a file there, although not one that I added myself. I think it may have carried over from an earlier and since removed installation of jupyter-drive? I'm not sure though. After deleting that file it now works, thank you!

**Comment by vikrant1433** [comment]
@cjprybol  which file you have deleted? I am getting the same error as you after installing jupyter-drive.

**Comment by vikrant1433** [comment]
okay got it its `~/.jupyter/jupyter_notebook_config.json`

**Comment by AtaaEddin** [comment]
I am on windows 10, how can i fix this?

**Comment by turkialjrees** [comment]
SOLVED
I solved this issue by:

1. open cmd as admin 
2. type in : 

 `jupyter notebook --config=/home/john/mystuff/jupyter_notebook_config.json`

**Note that**:  before running above script make sure , Anaconda and Jupyter Lab must be uninstall, , and delete all files in C:/ drive
Then install re-install the latest Python3 , and add/set the Environment path correctly , and isuggested make Pyhon in the main root folder of as C:/Python not c:/User/.../Python   , however u need to install  Jupyter notebook usin : `pip install Jupyter notebook`  **sometimes u need to install [get-pip.py ](https://bootstrap.pypa.io/get-pip.py) in order to use pip 

There is sometimes that the  jupyter_notebook_config.py is **missing**  To create a jupyter_notebook_config.py file, after installing the python , 
you can use the following command line:
`jupyter notebook --generate-config`
 
I hope that help you 

please comment if it is works
![cmd](https://user-images.githubusercontent.com/11802304/63308997-021cf280-c2ed-11e9-81a2-1e6b42ca775b.png)

**Comment by turkialjrees** [comment]
> I am on windows 10, how can i fix this?

read my comment above , it have been [solved HERE ](https://github.com/jupyter/notebook/issues/274#issuecomment-522808247):

**Comment by larryisthere** [comment]
Add LANG=zn before jupyter notebook like:
`LANG=zn jupyter notebook`
Only this solved this error on Chinese version Mac OS Big Sur.

**Comment by Sahil3201** [comment]
Turns out I had moved the folder I had previously set as the default folder when it starts. You can set that configuration under `c.NotebookApp.notebook_dir` in the jupyter_notebook_config.py. To know the file location, just run the command `jupyter --config-dir` in a jupyter command prompt.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/notebook-permissions-issue-seems-to-involve-an-issue-with-anaconda-navigator/10103/4
