### ISSUE TITLE
Add handlers for common file types

### ISSUE THREAD

**Issue by ghost** [jupyter/notebook#2765]
Hello,
  It would be very useful to have built in file handlers for common types (view image files, pdf files, etc). Spreadsheets would be extremely useful for data manipulation and storage, and cannot be substituted by Python or R

**Comment by ndrewxie** [comment]
When viewing unrecognized file types, jupyter should attempt to display the raw data (or even raw data in editor) instead of downloading it.

**Comment by jtpio** [comment]
Closing as fixed by Notebook 7, which uses the same 

See https://github.com/jupyter/notebook/pull/6922 for an example of a recent PR that fixe default document viewers:


![image](https://github.com/jupyter/notebook/assets/591645/32365731-1d4a-4d40-97f8-9bea94a3543c)

![image](https://github.com/jupyter/notebook/assets/591645/97dcdc55-413c-421d-9729-92c01c8abc32)

![image](https://github.com/jupyter/notebook/assets/591645/9a398f8a-1f0e-45eb-ad88-13be166611ed)

![image](https://github.com/jupyter/notebook/assets/591645/20519a96-4082-4af5-9e15-5d2eb668fe72)
