### ISSUE TITLE
[Feature Request] Dialog window when choosing action.

### ISSUE THREAD

**Issue by herleeyandi** [jupyter/notebook#2795]
I really like jupyter notebook for doing coding and debugging. Can you adding feature like dialog window to asking the user whether they are really want to do certain action. For example I always accidentally choose delete or shutdown some windows. So to prevent this I really hope that jupyter can give feature to ask user and make sure user really wants do that action.
-Thank you-

**Comment by jtpio** [comment]
Closing as fixed in Notebook 7, which uses the same dialogs as in JupyterLab.

Here is an example of a dialog that asks users whether they want to shut down their kernel:

![image](https://github.com/jupyter/notebook/assets/591645/80a82ca9-6efb-4af6-b184-d085adabaaa5)

For reference dialogs can also be opened from third-party extensions: https://jupyterlab.readthedocs.io/en/latest/extension/ui_helpers.html

Thanks for opening the issue!
