### ISSUE TITLE
Dotted line of the ruler extension intersects the letters

### ISSUE THREAD

**Issue by axil** [jupyter/notebook#2869]
![image](https://user-images.githubusercontent.com/170910/30895023-ae2dcc86-a371-11e7-885f-0b279c8bcdb3.png)
The latest notebook version that works correctly is 4.2.3:
![image](https://user-images.githubusercontent.com/170910/30895041-ccf7e64c-a371-11e7-94f1-8049ee7ab3ad.png)
I traced back the issue to the questionable codemirror bugfix https://github.com/codemirror/CodeMirror/issues/4042

I also provided a patch there.

But codemirror author believes that that the issue is on the jupyter side and suggests a solution there.

**Comment by rgbkrk** [comment]
Have you reported this to the ruler extension developer?

**Comment by axil** [comment]
@jcb91 - I think you're the right person to ask?

**Comment by jcb91** [comment]
@axil I'll do :wink:. From your extensive detective work detailed on https://github.com/codemirror/CodeMirror/issues/4042, and as you suggest, CodeMirror dev seems  to think that jupyter is not using CodeMirror's expected/required padding arrangement, which separates horizontal and vertical padding into separate elements. Since the nbextension doesn't add any case, it isn't the cause, and it would make sense to fix it in notebook here. I could presumably add CSS overrides to the extension as a temporary hotfix though...

**Comment by axil** [comment]
I would be happy with any solution that works and would be 'official'. As for myself I can make a hotfix in a couple of ways but I declared to my students that any decent editor has this feature (ruler) and the next day I found out that for jupyter this feature is currently hardly usable. I wouldn't like to advise them to make a manual patch in a python lib. :)

**Comment by jcb91** [comment]
> I declared to my students that any decent editor has this feature

:rofl:

Ok, well, the best way seems like a PR to notebook, I guess, but equally, you can slap one onto [ipython-contrib/jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions), which _may_ get a patch release sooner...

**Comment by axil** [comment]
@jcb91 If that emoji meant irony, here's a list of python editors which support vertical guidelines:
spyder, pycharm, sublime, eclipse, vim, emacs, visual studio, mechanical typewriter, etc

**Comment by jcb91** [comment]
@axil apologies, reading that back, it wasn't very clear what I meant, but I very much agree that having a ruler is a basic feature of any decent editor. The intention was to convey laughter at the absurdity of not having a functioning ruler, but yeah, I should have used some actual words, rather than just an ambiguous face! I'll have a stab at an override for the extension now...

**Comment by jcb91** [comment]
ok, PRs for notebook & nbextension submitted...

**Comment by gnestor** [comment]
Notebook 5.1.0rc1 is available on PyPI so please give it a try and confirm that this is resolved 👍:

`pip install notebook --pre --upgrade`

**Comment by axil** [comment]
Yes, working as expected! That was fast! Thanks!
