### ISSUE TITLE
Traceback shows no details for user-defined functions

### ISSUE THREAD

**Issue by AustinW4t1qbit** [jupyter/notebook#2879]
My apologies if this is already an issue. Finding issues with traceback is difficult as searching for traceback finds basically all errors.

Whenever there is an error and traceback comes up, it shows the line with the error when it is in a notebook or a non-user-defined function, but not for a user defined function. This is with the latest version of jupyter. The problem does not exist in iPython. 

![Traceback screenshot](https://user-images.githubusercontent.com/19154893/31030461-4bc967fe-a50a-11e7-8d3b-96fb0476b682.png)

**Comment by takluyver** [comment]
Have you changed directory since you imported `generate_clusters`? If you check `os.getcwd()` before running that line, is it the same directory that contains the notebook?

It will do that when it can't find the file that the code is in, and since it's using a relative path for it, that depends on the working directory.

**Comment by AustinW4t1qbit** [comment]
Ahh, that would be it. Thank you :). I didn't know that that was relevant.
