### ISSUE TITLE
the menu is missing

### ISSUE THREAD

**Issue by BXDimmortal** [jupyter/notebook#2886]
![screenshot from 2017-10-01 09-27-19](https://user-images.githubusercontent.com/24941067/31054950-f898eeec-a68a-11e7-9e1c-b19f2b722579.png)

**Comment by takluyver** [comment]
This is an unfortunate point of confusion (#2182). The main thing to use Jupyter for is notebooks, which have a `.ipynb` extension. You can create them from the files list by clicking the 'new' button, and then selecting a notebook language.

Jupyter includes a very basic text editor for altering plain text files, such as .py scripts. This is useful in some situations, but it's not the main focus of the project, and it's not intended to replace the many more powerful editors and IDEs already available.

**Comment by dr-blink** [comment]
wtf of course its important ... how can you run, test and debug an app w/o them!

**Comment by takluyver** [comment]
Again, the point of Jupyter is to write and run notebooks. From the 'new' menu, click one of the options under 'Notebooks' to get into the notebook UI.

The screenshot above is the text-editor UI, which is completely separate, and not what we focus on - if you want to edit text files, there are thousands of better editors out there.

Appending ipynb to a text file doesn't make it a notebook - notebooks have a different file format.

**Comment by ivanov** [comment]
Hey there @BXDimmortal and @dr-blink , I came across this old issue and it seems to me that it makes sense to close it. As @takluyver mentioned - the reason the cell insert and kernel top level menus are "missing" is because this is a plain .py file opened with an editor, not a notebook.

In addition, @dr-blink - the tone of your message, using all capital letters, excessive exclamation marks , soliciting a "REAL solution" is insulting and not appropriate.

Thanks everyone and happy hacking! :bowtie:
