### ISSUE TITLE
Find the default local Jupyter directory

### ISSUE THREAD

**Issue by pylang** [jupyter/notebook#2941]
I would like to know how to programmically find the root of my jupyter directory.

_Background_

Each notebook that is served to the browser has a "head" + "truncated  file path" e.g.

    http://localhost:8888/tree/notebooks/.../my_notebook.ipynb

The "head" here is `http://localhost:8888/tree/`, which replaces some local directory path, e.g. `C:/Users/PC/Documents`.   I have some scripts that depend on the jupyter root directory e.g. `./notebooks`, so I would like **find a way to find the root of my notebooks.** 

*Details*

When I start jupyter from an Anaconda shortcut, it seems to a know where my notebooks are located.  Note, I do not have a config file, so this seems to be automated.  The shortcut runs `jupyter-notebook-script.py` which calls `notebook.notebookapp.main()`.  I poked around there for a while, but I'm not sure how the root path is determined.

This issue has also been [posted on StackOverflow](https://stackoverflow.com/questions/46775023/find-the-default-local-jupyter-directory?noredirect=1#comment80498914_46775023).

**Comment by jcb91** [comment]
Unless specified otherwise in config or environment variables, the notebook server will use the current working directory *at start time* as the notebook directory. As I've noted over on SO, yours seems to be set to the documents folder becuase the Anaconda shortcut is doing a little magic to set the working directory to there before starting the notebook server. For you purposes, you could: 

1. Explicitly set the notebook directory in a config file or environment variable
2. Assume the notebook root is at 
   ```python
   os.path.expanduser('~/Documents')
   ```
   (note this may not work if OS language is not English)
3. Use the pip/conda package `menuinst` to replicate the same logic exactly:
    ```python
    from menuinst.windows.knownfolders import FOLDERID, get_folder_path
    documents_folder, exception = get_folder_path(FOLDERID.Documents)
    if exception:
        documents_folder, exception = get_folder_path(FOLDERID.PublicDocuments)
    if exception:
        print('bang! exception!')
    else:
        print(documents_folder)
    ```

**Comment by pylang** [comment]
@jcb91 Thank you for your research and post.  I found `menuinst.knownfolders` worked on my system (Win 7).

**Comment by Raimar123** [comment]
__mmmm
