### ISSUE TITLE
Request: Change background-color of logger messages by  Logging Level

### ISSUE THREAD

**Issue by zfrenchee** [jupyter/notebook#2944]
I love jupyter notebook. Frequently I use packages I write from jupyter. Some of those packages have loggers which `logger.info('information')`. In jupyter, those messages show up below the code window in an angry magenta. That seems appropriate for `logger.error` or `logger.critical` but `logger.info` could have a more pleasant, calming color, so that my code doesn't look terribly broken when just trying to keep you in the loop about what it's up to. :)

[Logging levels reference](https://docs.python.org/3/library/logging.html#logging-levels).

**Comment by takluyver** [comment]
I think the default log handler writes messages to the stderr stream. We display stderr output with a red background to distinguish it from stdout - though this is a questionable decision,  since output on stderr does not necessarily mean there's a problem.

There are a couple of ways you could distinguish different log levels:

- Use a logging formatter to embed ANSI colour codes into the text (Tornado has such a formatter, for example), and configure the StreamHandler to write to stdout instead of stderr (avoiding the red background).
- Write a custom [logging handler](https://docs.python.org/3/library/logging.html#handler-objects) which sends Jupyter [display_data](http://jupyter-client.readthedocs.io/en/latest/messaging.html#display-data) messages to display logging information as HTML, which gives much more control of how it appears. This would be a bit more work, but it would be an interesting contribution to the ecosystem; it could be released as a standalone package for people to use.

**Comment by zfrenchee** [comment]
Sounds good. Thanks @takluyver !

**Comment by lzkelley** [comment]
@takluyver the mentality behind a red `stderr` message seems reasonable, but then why isn't the background errors themselves red?
