### ISSUE TITLE
Can't add keyboard shortcuts to actions of extension

### ISSUE THREAD

**Issue by shingo78** [jupyter/notebook#2954]
We are developing https://github.com/NII-cloud-operation/Jupyter-multi_outputs

I can't add a keyboard shortcut to actions of this extension using _Edit keyboard shortcuts_.
The added keyboard shortcuts are enabled before reloading the notebook, but disabled with the following error after reloading.

```
Uncaught (in promise) Error: does not know how to deal with : MultiOutputs:pin_output
    at ShortcutManager.add_shortcut (keyboard.js:457)
    at ShortcutManager.add_shortcuts (keyboard.js:475)
    at keyboardmanager.js:80
    at <anonymous>
```

Reproduction procedure:
1. Select the _Edit keyboard Shortcuts_ menu item
2. Add a shortcut to the action of _multi\_outputs_ extension, click OK button
3. Reload the notebook

This `MultiOutputs:pin_output` action is registered by the multi_outputs extension.
https://github.com/NII-cloud-operation/Jupyter-multi_outputs/blob/master/lc_multi_outputs/nbextension/main.js#L604-L608

Could you give me some advice?

**Comment by takluyver** [comment]
I guess there's a race condition, that it's trying to add the shortcut before the extension has loaded and defined the action. It's a tricky one; it should be possible to bind a shortcut to an action name that hasn't been registered *yet*, but it's also nice to be able to catch incorrect action names.

Maybe `add_shortcut` could have an extra parameter to allow it to bind to actions which aren't registered yet. @Carreau @gnestor ?

**Comment by Carreau** [comment]
> Maybe add_shortcut could have an extra parameter to allow it to bind to actions which aren't registered yet. @Carreau @gnestor ?

I though it was already the case by default; I'll have to re-check. 
Though I think that might be because of **Edit** shortcuts, I believe *Edit* is more complicated (as it may interfere with Codemirror); so was not completely implemented.

**Comment by gnestor** [comment]
The issue is that the [`actions` and `keyboard_manager` objects are created](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/main.js#L112-L118) before [extensions are loaded](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/main.js#L218-L221). This is for good reason because otherwise the notebook could take a long time to load. 

The simple solution is to move all the actions/keyboard manager creation stuff into the `.then` after extensions are loaded. Unfortunately, almost all of the main objects depend on actions or keyboard manager, including the notebook, so that wouldn't buy us much. 

Another approach woulds be to break out [the adding of config shortcuts](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/keyboardmanager.js#L49-L84) (vs. default shortcuts) to a new method on keyboard manager that could be called after extensions are loaded.
