### ISSUE TITLE
add custom js file via settings

### ISSUE THREAD

**Issue by hiaselhans** [jupyter/notebook#299]
This is a request rather than a bug:

it used to be possible to do something similar to this:

c = get_config()
c.NotebookApp.extra_static_paths = [os.path.join(dirname, 'static')]

and then have a "static/custom/custom.js" file which would be loaded on startup.
is there a straightforward way to achieve anything like this or do i have to put it in my .ipython directory?

best regards,
simon

**Comment by Carreau** [comment]
in Jupyter 1.0 and Notebook 4.0 all should be the same except (roughly) replace `~/.ipython/profile_default/` by `~/.jupyter`

if you drop a file in `.jupyter/custom/custom.js` it should work without extra modification.

**Comment by auneri** [comment]
I see this issue is closed, and the provided answer (workaround) does indeed work, but I am still having a problem specifying `extra_static_paths` that point to locations outside the standard `~/.jupyter` directory.

Turning on debug option, I can see that the configuration is read properly, no errors are reported, but the `custom.js` is simply ignored. FYI, the same configuration works on v3.

**Comment by hiaselhans** [comment]
indeed, thats what i used to do in earlier versions of ipython... i had a
custom run.py which did that thing amongst others... however i think the
file is still available in current upstream, but with "/static" prefixed,
so "/custom/custom.js" will not point to your file which seems to be at
"/static/custom/custom.js". at least thats what occured to me...

2015-08-27 17:35 GMT+02:00 Ali Uneri <notifications@github.com>:

**Comment by auneri** [comment]
I think this issue is related to #199, and should be reopened.
