### ISSUE TITLE
How do you use cull_idle_timeout with Jupyterhub?

### ISSUE THREAD

**Issue by Siecje** [jupyter/notebook#3072]
I tried setting `c.MappingKernelManager.cull_idle_timeout = 300` in `jupyterhub_config.py` but no luck.

Does this mean that you can set `--MappingKernelManager.cull_idle_timeout` and not require the `cull_idle_servers.py`? https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle

**Comment by takluyver** [comment]
The single user servers started by Jupyterhub have to be configured separately from the hub itself, I think. How you do that will probably depend on how you have it configured to spawn servers, but if the single user servers run on the same machine, you can put their config in `/etc/jupyter/jupyter_notebook_config.py`.

`MappingKernelManager.cull_idle_timeout` only deals with culling the kernels, not the servers, so it doesn't make `cull_idle_servers.py` redundant. We're adding a notebook config option for the server to shut itself down when it's idle, which might cover the functionality of `cull_idle_servers.py`.

**Comment by Siecje** [comment]
There doesn't appear to be a `jupyterhub` command line argument to specify the location of the `jupyter_notebook_config.py`.

So `MappingKernelManager.cull_idle_timeout` is being set it just doesn't do what I think it does? How can I verify that it is working?

So in addition to `MappingKernelManager.cull_idle_timeout` I should setup `cull_idle_servers.py` until additional functionality is added to this notebook repo?

**Comment by takluyver** [comment]
No, I don't think Jupyterhub has a config option for a notebook config
file. Some spawners may be able to configure it, but the norm is to make it
available in the location that the single user servers expect.

Configuring MappingKernelManager in Jupyterhub config probably has no
effect, because Jupyterhub doesn't run that bit of the code. It needs to be
configured from individual notebook servers.

It depends what you want to do. The MappingKernelManager option shuts down
inactive kernels. If you also want to shut down inactive notebook servers,
you need cull_idle_servers.py for now.

**Comment by Siecje** [comment]
Okay thank you for the explanation.
