### ISSUE TITLE
A way to load assets once

### ISSUE THREAD

**Issue by shashi** [jupyter/notebook#319]
As explained in https://github.com/JuliaLang/IJulia.jl/issues/339

Javascript containing web component declarations cannot be loaded safely by packages, because a kernel restart would cause the Javascript to be loaded again, which is a fatal error. What could be done about this?

**Comment by Carreau** [comment]
I think that one of the things we are trying to figure out. Using `declare()` and `require()` from require.js it should be possible to get the things on the page only once, though it is not always easy in the of how to allow installation on a per-kernel basis. 

It is one of the area where we would need experience from people that use javascript more than we do for this kind of things.

**Comment by shashi** [comment]
You're right, using `require` would be a nice way to do this. Or package's JS code can check for a specific global variable before loading this. This is not such a big deal as is #320

**Comment by rgbkrk** [comment]
That's where @jdfreder's #116 should come into play, IMO.

**Comment by jdfreder** [comment]
It should be noted, additional work, somewhat related is being done in #268 which allows npm packages and modules to be used in the core notebook code (not yet extended to extensions).

**Comment by JamiesHQ** [comment]
Hi All: Based on the activity on #116  is there still work to do on this issue & can it be closed? thanks!

**Comment by rgbkrk** [comment]
This definitely still needs to be done, it's one of the biggest limitations of the notebook. @shashi are you still interested in this?

**Comment by shashi** [comment]
Yes of course! :)

**Comment by JamiesHQ** [comment]
cc'ing @gnestor

**Comment by gnestor** [comment]
So if an output contains an HTML import and that cell is run a 2nd time, it will try to do another HTML import and result in a fatal error? 

The first solution that comes to mind is to create an extension and move the HTML imports and whatnot to it so that the HTML imports only happen on notebook load. This would also allow the web component(s) to be used across profiles and kernels. I've created a [cookiecutter](https://github.com/jupyterlab/mimerender-cookiecutter) for generating renderer extensions for both classic notebook and JupyterLab. This allows your extension to register a custom mime type (e.g. `application/vnd.compose3d+json`) so that your when the kernel returns output of that mime type (a Julia library can handle this part), your extension will be used to render it. It should be pretty straight-forward to setup: put the HTML imports in [`register_renderer`](https://github.com/jupyterlab/mimerender-cookiecutter/blob/master/%7B%7Bcookiecutter.extension_name%7D%7D/nbextension/src/renderer.js#L54) and the rendering code in [`append_mime`](https://github.com/jupyterlab/mimerender-cookiecutter/blob/master/%7B%7Bcookiecutter.extension_name%7D%7D/nbextension/src/renderer.js#L56-L69).

**Comment by shashi** [comment]
links to code are broken now. But thanks!
