### ISSUE TITLE
password invalid after copying one server's jupyter ipynb file to another server's jupyter notebook  

### ISSUE THREAD

**Issue by feiniao1696** [jupyter/notebook#3192]
on server A, there is password in server A's Jupyter and password needed to access server A's jupyter file say test.ipynb. 
after I copy test.ipynb to another server B, I know server B's jupyter password but don't know A's, then I can directly open test.ipynb's with server B's jupyter password.

is the lock in jupyter level, how can the lock the file test.ipynb no matter where it moves to?

**Comment by takluyver** [comment]
Yes, that's intentional. The password protects access to the server, which can start kernels and run code on your computer.

We don't offer any integrated way to protect the contents of a notebook file. Like any file, you can protect it by storing it somewhere that other people don't have access to, or by encrypting it (e.g. making a password protected zip file).

**Comment by feiniao1696** [comment]
ok. got it. Thanks very much!

**Comment by takluyver** [comment]
No problem.
