### ISSUE TITLE
Every 2nd cell's running never ends

### ISSUE THREAD

**Issue by aabbss44** [jupyter/notebook#3234]
Hello. Just see the gif:
![peek 2018-01-18 12-34](https://user-images.githubusercontent.com/34134379/35093971-92036c3a-fc4c-11e7-9488-b76421e0706b.gif)
I just run the same cell and see that every second running never ends. I interrupt a cell after a few seconds of running, and next time running works successfully.
I think, that it happens only if I load 1-2 GB to the memory before.
Hope for you help. Thanks

**Comment by takluyver** [comment]
> I think, that it happens only if I load 1-2 GB to the memory before.

How are you doing that? I suspect it could be that Python's garbage collector is running to clear up old objects. When it runs is determined by how many objects have been allocated in Python.

**Comment by SergYevtukhoff** [comment]
Hi there. I came across the same problem. I've checked an issue link below. It doesn't look like garbage collector issue because of its wierd behaviour. This behaviour is exactly as following:
1) Run the cell => It becomes frozen. The cell looks like a running one but nothing really happens: no results, no outputs - nothing.
2) Interrupt the kernel.
3) Run the cell again => It works like a charm immediately.
4) Run again => doesn't work. Interrupt kernel, run again => it works. and so on and so on

I also noticed that such behaviour was typical only when I utilized a lot of memory (after loading big csv, dbf or txt files). So here is the same issue as topicstarter has, but described in other words :)

Thanks

**Comment by takluyver** [comment]
I still wonder if it could be the garbage collector, because you've both said that it happens when you use a lot of memory.

Can you try running this code inside the notebook, and see if the problem still happens afterwards?

```python
import gc
gc.disable()
```

(You'll want to run `gc.enable()` or `gc.collect()` at some point later, otherwise it may just keep using more and more memory)

**Comment by feschmidt** [comment]
I have the same issue. ```gc.disable()``` doesn't fix it. In my case I am loading a .dat file with 37 MB.

In my case I have also noticed that even though the kernel seems to be done executing the cell (according to datestamper), the jupyter icon of the tab indicates that the kernel is still busy with something:
![image](https://user-images.githubusercontent.com/21104656/51618419-93321380-1f2e-11e9-828e-a8f47bbe5cf7.png)
after about 1.5min the kernel does indeed finish and directly executes the cell in the same time as after interrupting:
![image](https://user-images.githubusercontent.com/21104656/51619157-025c3780-1f30-11e9-8cf4-ad1fc25add33.png)
This time is the same with and without ```gc```.

operating system: macOS HighSierra, using python3 and nbextensions

**Comment by petebachant** [comment]
I am getting this problem as well running Python 3.7 from Anaconda on Linux.

**Comment by mischki** [comment]
Same issue here. 
Python 3.6.6
jupyter 5.7.4

**Comment by YpGu** [comment]
Any solutions to this problem? Seems like it happens a lot

**Comment by pablonm3** [comment]
same problem here :(

**Comment by pablonm3** [comment]
Not sure if my problem is the same, it happens when I try to run manny cells at once(eg:run all cells) at some point the notebook gets stuck at running some cell forever, the cell where it gets stuck at, it's just a print statement for one an specific row & column in a dataframe

**Comment by pablonm3** [comment]
After interrupting the kernel realized that the cells actually ran, one of them threw an exception(my fault) but for some reason jupyter kept showing the loading icons

**Comment by shiqidai1002** [comment]
Same issue here!!
My jupyter notebook running on remote and I usually need to load a huge df in memory.
Then, even defining a variable like `a = None` can be quite slow.

**Comment by ndandanov** [comment]
I also encountered this problem and, as mentioned in #4059, tried to disable the Variable Inspector extension from the `jupyter_contrib_nbextensions`. It seems to me that now the notebook cells execute much faster and smoother.

**Comment by koppj** [comment]
I confirm @ndandanov's observation. Disabling the variable inspector appears to have solved the problem for me. Thanks!

**Comment by benlindsay** [comment]
Wow, over a year later and this problem happened to me. I also confirm that disabling the Variable Inspector fixes the problem.

**Comment by kevin-bates** [comment]
Hi @benlindsay.  I'm sorry for your frustration.  As multiple responses (as well as #4059) have pointed out, the issue appears to be related to the Variable Inspector and that seems the appropriate place to start.  As a result, I'm closing this issue.
