### ISSUE TITLE
"Download As..." Reusing old pdf

### ISSUE THREAD

**Issue by waio1990** [jupyter/notebook#3251]
Hi, i've been tweaking my notebook settings and got a custom nbconvert template working with the "download as..." menu via the config file, however subsequent downloads do not recompile the xelatex code and almost instantly give me the report i generated this morning.

Is there a way to force a recompile of the latex code? I figured if i deleted the pdf it would have to do it but cannot find the location its being stored on.

Thanks

**Comment by takluyver** [comment]
I don't think we store it anywhere, but maybe it's cached by the browser.

**Comment by waio1990** [comment]
Bingo! Restarting firefox did the trick, thanks!

now i need to figure out how to disable the download cache on firefox :P

**Comment by takluyver** [comment]
I'm going to reopen this, because we can probably do something better with our HTTP responses to control cache behaviour. At a minimum, we should ensure we set a short cache expiry period on nbconvert URLs, but we can probably do something clever with [ETags](https://en.wikipedia.org/wiki/HTTP_ETag).

**Comment by juhlpatrick** [comment]
Confirmed issue here with download to pdf. +1 for fixing this issue

**Comment by ashleytqy** [comment]
Hi, can I try to work on this issue?

**Comment by takluyver** [comment]
Please do! Do you know about HTTP headers to affect browser caches?

**Comment by takluyver** [comment]
And can you reproduce the issue?

**Comment by ashleytqy** [comment]
@takluyve I can't seem to reproduce the issue on Chrome and Firefox. I downloaded a simple latex file, and then changed the file and then downloaded that changed file. the latex seems to load correctly. I didn't clear the cache for both Firefox and Chrome when I downloaded the two files.

May I know how to reproduce this error correctly? @juhlpatrick / @waio1990

**Comment by takluyver** [comment]
> The behaviour is pretty inconsistent, I'm not totally sure why, because when I tried to download a changed copy of the PDF a few minutes later, it updates correctly.

That does sound like browser caching. The browser can keep a copy of data it gets from the server, to save time if it needs to get the same data again later. But then you need ways to decide when the data has changed, so that the browser can get the updated data. The simple way to do that is to have a time limit. A cleverer way is [ETags](https://en.wikipedia.org/wiki/HTTP_ETag), which let the browser ask for 'give me the latest version if it's not this one that I've already got'.

**Comment by ashleytqy** [comment]
I'll look into ETags, thanks @takluyver !

**Comment by larsasp** [comment]
Rename the notebook and try again
