### ISSUE TITLE
security vulnerability

### ISSUE THREAD

**Issue by ResidualLaugh** [jupyter/notebook#3302]
I found a security vulnerability, whom should i talk to?
It's particularly influential about notebook.
I will not disclose the vulnerability until I've found the person I'm sure of.

**Comment by takluyver** [comment]
Please email security@ipython.org - that will go to a few of us, but not a public list.

More details here: http://jupyter-notebook.readthedocs.io/en/stable/security.html#reporting-security-issues

**Comment by ResidualLaugh** [comment]
Thanks for your response, i will send a email for explain the vulnerability.

**Comment by takluyver** [comment]
Thanks

**Comment by prvnkumark** [comment]
Hi,
Wanted to check if this issue has been fixed? Can you please vulnerability details if issue has been fixed?

**Comment by takluyver** [comment]
Sorry; when the issue was described on security@ipython.org , we determined that it wasn't a security issue after all. It was a way for a user to crash a single notebook server. Since a single notebook server is meant to be used by one user, it's not a security issue if they crash it. Though of course we may fix things to make it harder to crash accidentally, just as a normal bug.

However, a real security issue was reported the following month, and fixed in notebook 5.4.1.

**Comment by prvnkumark** [comment]
Hi,
Thank you for confirmation, much appreciated.
