### ISSUE TITLE
Markdown text changing colour after a '%' symbol. Possible bug?

### ISSUE THREAD

**Issue by shivendra90** [jupyter/notebook#3363]
This is what I'm talking about:

![markdown_issue](https://user-images.githubusercontent.com/9760865/36536241-3ac645a2-17f2-11e8-9842-7013622c65ec.png)

Why is the text after a '%' orange in colour? Have noticed this before too but reporting it first time. Any way to turn it off since its kind of annoying?

**Comment by takluyver** [comment]
Looks like a bug with the Codemirror mode for markdown highlighting; it's defined [here](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/codemirror-ipythongfm.js) based on Codemirror's Github-flavoured-markdown mode. It might be fixed by upgrading to a newer codemirror, as #3372 just did.
