### ISSUE TITLE
meta-c copies the entire line if nothing is selected (with no way to disable)

### ISSUE THREAD

**Issue by zach-nervana** [jupyter/notebook#3400]
I use a accessibility tool called `voicecode` to allow me to dictate my computer use. One of the tricks that it uses is to send a `meta-c` and check the clipboard to a program to determine if the user has anything selected. Jupyter notebooks is configured so that if nothing is selected this keyboard shortcut copies the entire line. This breaks some of the functionality.

I've tried modifying `IPython.keyboard_manager.edit_shortcuts.add_shortcut('meta-c', "jupyter-notebook:ignore")`, but have only succeeded in disabling copying by shortcut altogether. Is there a way to disable line copy in the event that nothing is selected?

**Comment by takluyver** [comment]
Sorry about that! I'm guessing that this happens when you're in command mode, and it works correctly if you're in edit mode with nothing selected. (If you can see the interface, a green border around the cell means it's in edit mode; unfortunately I don't know how to check this if you're also using a screenreader).

If you are in command mode, conceptually you always have at least one cell selected; there's no way to unselect all cells. We don't currently have any switch to disable the clipboard interaction, but it's a reasonable thing to add, so we'll treat this as a feature request.

If you are seeing the issue while you're in edit mode, then it's likely something to do with Codemirror, the editor component we use.

**Comment by zach-nervana** [comment]
Thanks for the response. The problem is actually in edit mode. It is easy to reproduce, just hot control copy/command copy while in exit mode with nothing selected and it cooped the entire line. 

I'll check out codemirror to see if they expose any options.

**Comment by zach-nervana** [comment]
Thank you for the pointer, I have successfully disabled this feature using the following javascript:

```
%%javascript
var cell = Jupyter.notebook.get_selected_cell();
var config = cell.config;
var patch = {
      CodeCell:{
        cm_config:{lineWiseCopyCut:false}
      }
    }
config.update(patch)
```

**Comment by takluyver** [comment]
Thanks for documenting what needed to be changed :-)
