### ISSUE TITLE
Search and replace Keybinding. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#341]
Implement default keybinding for Search and Replace. 

@parleur, you want to give it a try.

**Comment by captainsafia** [comment]
Ah drat! sorry. I started working on this and #342 but forgot about them. I'll work on them today and get PRs to you by 5pm PT.

**Comment by captainsafia** [comment]
@Carreau — can you set me as assigned on both?

**Comment by captainsafia** [comment]
I need some help with this as it is driving me a little insane. So, I add the following line under the `get_default_command_shortcuts` function on the `KeyboardManager` prototype. 

`'shift-f': 'ipython.search-and-replace-dialog'`

But when I start up a test notebook to try it out, the `ShortcutManager` throughs an error because the action hasn't bee loaded yet. This error, `Uncaught Error: does not know how to deal with`, corresponds with [this line of code](https://github.com/jupyter/notebook/blob/336b3b7db6c9f9f0b2cfa07d4a26907ac3146838/notebook/static/base/js/keyboard.js#L365). I assume the error occurs because the `KeyboardManager` is created before `searchandreplace.load` can be called, causing the error.

The only solution that I could think of was changing the `load` function so that it acts directly on an `ActionManager` object as opposed to a `KeyboardManager` so that the process would look like this.

1. `ActionManager` object is created.
2. `searchandreplace.load` is called on `ActionManager` from 1.
3. `KeyboardManager` object is created.

Does that make sense? Let me know if I am making this too complicated.

**Comment by captainsafia** [comment]
Or actually, I think this won't be an issue once #329 is merged.

**Comment by minrk** [comment]
@captainsafia #329 has been merged, if you want to look at it again.

**Comment by Carreau** [comment]
The other solution is to register the shortcut at the same time than [the action]( https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/searchandreplace.js#L381).
