### ISSUE TITLE
I want to acces notebook on port 80 not on 8888

### ISSUE THREAD

**Issue by iankittomar** [jupyter/notebook#3416]
I wrote a docker file for jupyter notebook by default its mapped on port 8888 but i want to start it on port 80.
i wrote dockerfile  :- 

```dockerfile
FROM ubuntu
# Run a system update to get it up to speed
# Then install python3 and pip3
RUN apt-get update && apt-get install -y python3 \
     python3-pip
# Install jupyter
RUN pip3 install jupyter
# Create a new system user
RUN useradd -ms /bin/bash jupyter 
# Change to this new user
USER jupyter
# Set the container working directory to the user home folder
WORKDIR /home/jupyter
# Start the jupyter notebook
ENTRYPOINT ["jupyter", "notebook" , "--ip=0.0.0.0" , "--port=80"]
```

this is my dockerfile. I create a non root privilege user because i don't want to pass the comment --allow-root always.
this user don't have root privilege thats why its not mapping my port 80 neither 443 saying permission denial to listen port 80,81......etc rest ports are open i can use my service on 8080 or 8888 but not on 80 because i want to deploy this service on Kubernetes cluster where my container is not starting because of --allow-root and only port i can use is 80.
I have tried every method.

Please help me

**Comment by takluyver** [comment]
Inside the container, only root can listen on port 80. This is a system restriction on any port under 1024, IIRC).

What you can do instead is listen on the default port, and then map it to another port outside the container. E.g. if you used docker directly, you would do something like `docker run -p 127.0.0.1:80:8888 ...` to map port 8888 from the container to port 80 on your system. I haven't used Kubernetes, but there will be a way to do something similar.

**Comment by prashanth-234** [comment]
[W 11:06:37.368 NotebookApp] Permission to listen on port 8888 denied
[W 11:06:37.370 NotebookApp] Permission to listen on port 8889 denied
[W 11:06:37.371 NotebookApp] Permission to listen on port 8890 denied
[W 11:06:37.371 NotebookApp] Permission to listen on port 8891 denied
[W 11:06:37.373 NotebookApp] Permission to listen on port 8892 denied
[W 11:06:37.373 NotebookApp] Permission to listen on port 8949 denied
[W 11:06:37.374 NotebookApp] Permission to listen on port 8855 denied
[W 11:06:37.375 NotebookApp] Permission to listen on port 8878 denied
[W 11:06:37.376 NotebookApp] Permission to listen on port 8908 denied
[W 11:06:37.378 NotebookApp] Permission to listen on port 8802 denied
[W 11:06:37.379 NotebookApp] Permission to listen on port 8860 denied
[W 11:06:37.380 NotebookApp] Permission to listen on port 8805 denied
[W 11:06:37.381 NotebookApp] Permission to listen on port 8940 denied
[W 11:06:37.381 NotebookApp] Permission to listen on port 8940 denied
[W 11:06:37.383 NotebookApp] Permission to listen on port 8926 denied
[W 11:06:37.383 NotebookApp] Permission to listen on port 8974 denied
[W 11:06:37.384 NotebookApp] Permission to listen on port 8952 denied
[W 11:06:37.385 NotebookApp] Permission to listen on port 8942 denied
[W 11:06:37.386 NotebookApp] Permission to listen on port 8824 denied
[W 11:06:37.388 NotebookApp] Permission to listen on port 8846 denied
[W 11:06:37.389 NotebookApp] Permission to listen on port 8911 denied
[W 11:06:37.390 NotebookApp] Permission to listen on port 8922 denied
[W 11:06:37.391 NotebookApp] Permission to listen on port 8814 denied
[W 11:06:37.391 NotebookApp] Permission to listen on port 8887 denied
[W 11:06:37.392 NotebookApp] Permission to listen on port 8863 denied
[W 11:06:37.393 NotebookApp] Permission to listen on port 8807 denied
[W 11:06:37.394 NotebookApp] Permission to listen on port 8943 denied
[W 11:06:37.395 NotebookApp] Permission to listen on port 8970 denied
[W 11:06:37.395 NotebookApp] Permission to listen on port 8980 denied
[W 11:06:37.396 NotebookApp] Permission to listen on port 8950 denied
[W 11:06:37.397 NotebookApp] Permission to listen on port 8825 denied
[W 11:06:37.398 NotebookApp] Permission to listen on port 8794 denied
[W 11:06:37.398 NotebookApp] Permission to listen on port 8792 denied
[W 11:06:37.399 NotebookApp] Permission to listen on port 8807 denied
[W 11:06:37.400 NotebookApp] Permission to listen on port 8845 denied
[W 11:06:37.401 NotebookApp] Permission to listen on port 8956 denied
[W 11:06:37.402 NotebookApp] Permission to listen on port 8850 denied
[W 11:06:37.402 NotebookApp] Permission to listen on port 8899 denied
[W 11:06:37.403 NotebookApp] Permission to listen on port 8862 denied
[W 11:06:37.404 NotebookApp] Permission to listen on port 8926 denied
[W 11:06:37.405 NotebookApp] Permission to listen on port 8809 denied
[W 11:06:37.406 NotebookApp] Permission to listen on port 8843 denied
[W 11:06:37.407 NotebookApp] Permission to listen on port 8934 denied
[W 11:06:37.407 NotebookApp] Permission to listen on port 8792 denied
[W 11:06:37.408 NotebookApp] Permission to listen on port 8917 denied
[W 11:06:37.409 NotebookApp] Permission to listen on port 8943 denied
[W 11:06:37.410 NotebookApp] Permission to listen on port 8861 denied
[W 11:06:37.411 NotebookApp] Permission to listen on port 8892 denied
[W 11:06:37.411 NotebookApp] Permission to listen on port 8902 denied
[W 11:06:37.412 NotebookApp] Permission to listen on port 8897 denied
[W 11:06:37.413 NotebookApp] Permission to listen on port 8956 denied
[C 11:06:37.413 NotebookApp] ERROR: the notebook server could not be started because no available port could be found.

**Comment by prashanth-234** [comment]
please tell me next what i do

**Comment by Bestyasser** [comment]
I solved the problem by starting jupyer as root:
`sudo /<jupyter path>/jupyter notebook --port 80  --allow-root`

**Comment by jtpio** [comment]
@iankittomar if you are still experiencing this issue when running Notebook in Docker please have a look at the Docker Stacks repo: https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html

If you have more questions please don't hesitate to open a new topic on Discourse: https://discourse.jupyter.org/

Thanks!
