### ISSUE TITLE
ConnectionRefusedError when trying to shutdown notebook

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#3452]
Hi, 

`jupyter notebook list` gives me an old notebook (on 8888) that  I cannot shutdown with `jupyter notebook stop`, getting 

`ConnectionRefusedError: [Errno 61] Connection refused` 

Thanks for your help

ps: I am on safari 11.0.3 (mac os. 10.13.3).

**Comment by ggrrll** [comment]
#2844

**Comment by takluyver** [comment]
That's fine, I'd expect the names to start with `nbserver`. The notebook server creates one of those files when you start it, and removes it again when you shutdown the server. But if it is killed suddenly it may not get the chance to clean itself up.

The `kernel-....json` files are similar, but for individual kernels rather than notebook servers.
