### ISSUE TITLE
Hide some files from users

### ISSUE THREAD

**Issue by yakovlevvs** [jupyter/notebook#3476]
Hello,

I am a Linux user with restricted permissions (can't use sudo). I started Jupyter Notebook and allowed some colleagues to use it via browser. The problem is that they have access to all of my files by opening new ipython terminal in browser or using Python functions. 

Is there any way to hide some files from them using only Jupyter configurations? Because of restricted permissions I can't create a special user for them or use JupyterHub.

I tried to use hide_globs option like this:
` --FileContentsManager.hide_globs=[\"*login.txt*\"]` , but login.txt file still visible from terminal in browser. Maybe I misunderstood how to use this option?

Thank you!

**Comment by takluyver** [comment]
Sorry, there's no way to really do that - the notebook server is designed for a single user. You can limit what shows up in the file list, but anyone with access to terminals or notebook kernels can do anything on your computer as if they were you.

If you need to collaborate, maybe you're better off using a service like [Cocalc](https://cocalc.com/) rather than hosting the notebook in your own user account.

**Comment by williamstein** [comment]
> If you need to collaborate, maybe you're better off using a service like Cocalc rather than hosting the notebook in your own user account.

And if you have any questions about CoCalc, I can answer them...

**Comment by yakovlevvs** [comment]
@takluyver @williamstein , thank you for the help! 

I don't really need in users collaboration. We are going to use Jupyter just as interface to run our Python scripts on the remote server. 
As I understood the best way to resolve the described problem is to convince our system administrators to create the separate Linux account for these users.

Thank you!
