### ISSUE TITLE
Contributing dev docs: jupyter instances and verification of installation

### ISSUE THREAD

**Issue by danagilliann** [jupyter/notebook#3505]
I was working on #2460 when I realized I wasn't running Jupyter in dev mode, and I wasn't sure how to verify my dev installation. [This](https://github.com/jupyter/notebook/issues/2460#issuecomment-378172208) was written to me in the issue. The comment mentioned that I should uninstall other instances of Jupyter and told me how to verify the installation. Perhaps we could include the following in the contributing docs:

1. Uninstalling other instances of Jupyter
2. How to verify the installation

Not sure if (1) was an isolated incident, but perhaps (2) might be beneficiary to new contributors?

**Comment by takluyver** [comment]
:+1: I'm pretty sure you're not the only one to have had that kind of issue. Uninstalling all other instances is a last resort, but I think it would be good to have more notes on how to deal with it.

**Comment by danagilliann** [comment]
@takluyver Great! Is it okay if I work on this issue with @ashleytqy, @rosaswaby, and @ckilcrease? We're currently in an open source class together.

**Comment by takluyver** [comment]
Please do! :smiley:

**Comment by takluyver** [comment]
Closed by #3536.

Pro-tip @danagilliann @rosaswaby : if you put something like `Closes #3505` on its own line in a commit message, then the issue automatically closes when we merge the PR. It's tricky for something like this where the fix was spread over multiple commits, though, so it's not a problem if you miss it out.
