### ISSUE TITLE
Automagically execute markdown cell (with JavaScript?)

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [jupyter/notebook#3509]
In this thread I specified how I get a pre-initialized markdown "welcome cell" into newly created notebooks: https://github.com/jupyter/notebook/issues/1451

Now I would also like to have it pre-executed so that it looks neat from the start. 
I would assume it's just a one-liner added to `kernel.js`, but I am having trouble figuring out which. Could you developers maybe help me out here?

**Comment by takluyver** [comment]
I haven't tried it, but something like:

```javascript
Jupyter.notebook.get_cell(0).render();
```

I'm deliberately using render here rather than execute, though they're the same thing for a markdown cell. If a malicious notebook can trick your kernel.js into executing a cell that's already in the notebook, it could start running malicious code as soon as the user opens it. But if the cell is a code cell, `.render()` won't execute it, so calling this is a bit safer.

**Comment by freifrauvonbleifrei** [comment]
this works nicely, thanks!
