### ISSUE TITLE
Access Jupyter notebook running on docker container

### ISSUE THREAD

**Issue by TommyGN** [jupyter/notebook#3540]
I started a container with jupyter in it, linked the ports between host and container but when I launch a Jupyter kernel inside the container it doesn't find any browser and I can't see anything if I go on the localhost port specified. 
Here's a screenshot:
![image](https://user-images.githubusercontent.com/38477750/38899908-d3eaefce-426f-11e8-889d-3b709a633e40.png)

Do you have any suggestions?
Thanks in advance.

**Comment by dhirschfeld** [comment]
Don't use `docker exec`, just use `docker run` and don't try and reuse an already running container.

You've created a terminal in a container already running the notebook. Because the original notebook process is running on port 8888 the new process has to use port 8889 but port 8889 isn't exposed outside the container so nothing outside will see anything on 8889.

That doesn't explain why you can't see anything on port 8888 where the original notebook process appears to be running.

**Comment by TommyGN** [comment]
Creating a notebook on the port 8888 when is exposed and available doesn't change anything and I can't see anything in my browser. I really don't know what's happening. Do you have any other suggestion?

**Comment by takluyver** [comment]
Can you show the docker command you ran and the URL you're visiting in your browser?

**Comment by takluyver** [comment]
OK. I think Edge can work, but we don't officially support it, so I'm closing this now.
