### ISSUE TITLE
problem in importing module but command prompt works 

### ISSUE THREAD

**Issue by MotiBaadror** [jupyter/notebook#3614]
i have created a conda environment and launched jupyter notebook
import gym
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c727ea424a25> in <module>()
----> 1 import gym

ModuleNotFoundError: No module named 'gym'

these two commands in notebook shows : 
import sys
sys.executable
'C:\\Users\\BaadRoR\\Anaconda3\\python.exe'

sys.path
['',
 'C:\\Users\\BaadRoR\\Anaconda3\\python36.zip',
 'C:\\Users\\BaadRoR\\Anaconda3\\DLLs',
 'C:\\Users\\BaadRoR\\Anaconda3\\lib',
 'C:\\Users\\BaadRoR\\Anaconda3',
 'C:\\Users\\BaadRoR\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\BaadRoR\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\BaadRoR\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\BaadRoR\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\BaadRoR\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\BaadRoR\\.ipython']

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

For more detail, see [this blog post](http://takluyver.github.io/posts/i-cant-import-it.html).

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]
