### ISSUE TITLE
Jupyter notebook can't find lxml for BeautifulSoup

### ISSUE THREAD

**Issue by likohank** [jupyter/notebook#3623]
I hava installed lxml from Jupyter - 'Kernel' -  'Conda Packages',
but when I coding in Jupyter Notebook, it's print 'FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?'

![11](https://user-images.githubusercontent.com/11384716/40232336-eb7de0c8-5ad0-11e8-911f-216444b71f0d.jpg)

But, when I coding it though the same environment in the server shell, it correct.

![222](https://user-images.githubusercontent.com/11384716/40232425-48b07530-5ad1-11e8-9d87-7104fa298d45.jpg)

![333](https://user-images.githubusercontent.com/11384716/40232494-9912faa2-5ad1-11e8-9023-f656e6bbd52c.jpg)

Really don't konw why, very puzzling ... Could anyone help me,please

**Comment by likohank** [comment]
nobody..............

**Comment by takluyver** [comment]
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

For more detail, see [this blog post](http://takluyver.github.io/posts/i-cant-import-it.html).

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by remram44** [comment]
Can probably be closed 😉

**Comment by Nitin2020** [comment]
conda install -c anaconda lxml
