### ISSUE TITLE
%%timeit magic command slows code

### ISSUE THREAD

**Issue by HarshaLaxman** [jupyter/notebook#3693]
```
%%timeit     

for index, row in df_file.iterrows():  
    continue  

32.4 s ± 3.26 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```
start = datetime.datetime.now()

for index, row in df_file.iterrows():
    continue

end = datetime.datetime.now()
print(end-start)

0:00:29.262530
```

Where df_file is a pandas dataframe with 584856 rows × 5 columns

Nevermind that this is not an efficient way to work with the dataframe, it takes about 7 times longer to run the same code using %%timeit, and this is happening across all my pandas code.

**Comment by takluyver** [comment]
It runs it several times to give you a more accurate estimate and an indication of variability. That's why it's saying "mean ± std. dev. of 7 runs". 

There are options to control that - [see the docs](https://ipython.readthedocs.io/en/stable/interactive/magics.html?highlight=timeit#magic-timeit) - or you can use the simpler `%%time` magic.
