### ISSUE TITLE
GitHub Flavored Markdown incompatibility (tasklists)

### ISSUE THREAD

**Issue by jonahweissman** [jupyter/notebook#3725]
In the [markdown example notebook](http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html), it says that the ["notebook webapp supports Github flavored markdown"](https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/docs/source/examples/Notebook/Working%20With%20Markdown%20Cells.ipynb?short_path=6e5c622#L190). However, the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/#task-list-items-extension-
) includes the tasklist extension, i.e. `- [ ]` should be rendered as a checkbox. But when I try this in Jupyter Notebook, it displays a bullet point followed by `[ ]`.  The markdown example notebook could be updated to reflect that the Jupyter Notebook is not fully compliant with the GFM spec, or support for task item lists could be added.

**Comment by takluyver** [comment]
See #1578 and #3686.

**Comment by ryan-williams** [comment]
Checkboxes seem to be rendered improperly in Jupyter:

![image](https://user-images.githubusercontent.com/465045/65838797-d9691f00-e2d4-11e9-9957-d54549735a62.png)

as opposed to here on GitHub:

- [ ] a
- [x] b
- [ ] c

source:

```
- [ ] a
- [x] b
- [ ] c
```

(Notice the redundant bullets preceding the checkboxes in the Jupyter version).

I think that's what this issue was originally highlighting:

> But when I try this in Jupyter Notebook, it displays a bullet point followed by [ ]

I think this was closed due to misunderstanding the ask as "support for checkboxes altogether"?

Can we re-open?
