### ISSUE TITLE
Bootstrap folder missing fonts/glyphicons-halflings* but referenced in style.min.css

### ISSUE THREAD

**Issue by kacheo** [jupyter/notebook#3785]
Jupyter uses Bootstrap3 primarily, but does not include the fonts folder in its static libraries. When I try to use the Bootstrap classes when writing extensions or .js scripts that use this font, it will fail. Simply importing it to an extensions folder will not work since the pathing is relative in "/static/style/style.min.css"

Can changes be made to add the missing fonts?

The only workaround I can think of is completely overriding the bootstrap/css libraries that Jupyter imports which is not too clean...

**Comment by takluyver** [comment]
I don't remember about Bootstrap specifically, but we deliberately leave out some data files that Jupyter itself doesn't use in order to keep the package size down, and I think fonts were a particular culprit for large files.

**Comment by kacheo** [comment]
Ok :(

**Comment by takluyver** [comment]
I mean, feel free to investigate and make the case for it - I'm not saying no, I'm just explaining why it might be that way at the moment, and why we might leave it that way.

Jupyter's a bit of an odd case, because we bundle the libraries that are used in Jupyter itself, but then other people can also use them in extensions and in rich outputs.
