### ISSUE TITLE
2 stupid questions about documentation for creating custom request handlers

### ISSUE THREAD

**Issue by krinsman** [jupyter/notebook#3787]
This is in reference to the code examples found [here](http://jupyter-notebook.readthedocs.io/en/stable/extending/handlers.html#registering-custom-handlers). ([Here on GitHub](https://github.com/jupyter/notebook/blob/master/docs/source/extending/handlers.rst))

**1.** Why is the `host_pattern` set to `.*$`?

My thinking at first was that this just allows the host name to be matched to anything, since `.*` and `.*?` are such regex's. But the `$` throws me off -- I had guessed that its purpose was to ensure that `'.*$' + regex` matches exactly the same things as `regex` (and not `.*`), but this doesn't seem to be the case as far as I can tell, since `'.*' + regex` seems to match exactly the same things as `regex`, while `.*$` actually seems to match nothing. Is that correct? Wouldn't that (it's probably not correct though) mean that the custom request handler would never be instantiated?

**2.** Would it be possible to use `web_app.settings['base_url']` as the `host_pattern` and then have only `/hello` be the `route_pattern`? Or is Tornado or the Jupyter Notebook Application configured so that this wouldn't work?

I apologize in advance if I should be asking this on the Tornado GitHub page instead, since these questions seem to mostly come down to the `add_handlers` method of [`tornado.web.Application`](http://www.tornadoweb.org/en/stable/web.html#tornado.web.Application.add_handlers), from which `NotebookWebApplication` inherits. On the other hand, `base_url` is not a key in the default implementation of the `settings` dictionary for `tornado.web.Application` objects ([the default is overwritten](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L221)), and `url_path_join` is part of the Jupyter source code.

I understand that the tutorial would be unreadable if every line of code was explained to the level of pedantic detail of these questions. My interest is primarily in checking/testing my understanding of the code for a server extension whose source code is based on this tutorial. If you have any spare time to quickly answer these questions, I would be very grateful, and if not, I understand.

**Comment by takluyver** [comment]
Those don't seem like stupid questions!

1. As you guessed, the real answer is 'I don't know, we just got this from tornado'. But I would guess that it ensures that the pattern matches the whole of the hostname, not just a prefix. `$` means the end of the string. In the case of `.*`, I think it doesn't make any difference, because Python's regex engine is greedy by default, but perhaps it's a good habit to get into, and explicit is better than implicit.

2. I would guess the host name and the path have to be kept separate, though I haven't checked how tornado actually handles them. From the perspective of HTTP, these are two separate fields a request can have, though we represent them in URLs as a single string.

**Comment by krinsman** [comment]
OK, then I will close this issue and re-open it with Tornado. Thank you for your time and help with this!

**Comment by krinsman** [comment]
@takluyver Sorry, I forgot to ask: where is the Tornado documentation that you got this from? 

It probably wouldn't make sense to ask this with Tornado without being able to reference Tornado documentation.
