### ISSUE TITLE
Cull idle terminals

### ISSUE THREAD

**Issue by clkao** [jupyter/notebook#3868]
#2963 added `shutdown_no_activity_timeout` and `terminal_last_activity`, but it seems there's no way to cull idle terminal right now, which [prevent the notebook from being shutdown automatically](https://github.com/jupyter/notebook/blob/98085dcb8420ecc0effaae240bdd8e85bb888105/notebook/notebookapp.py#L1587).

Should we have another pair of `cull_idle_timeout` `cull_interval` for terminals?

**Comment by foxel** [comment]
Is there any update on this feature? Maybe implemented somewhere else?

**Comment by kevin-bates** [comment]
I just noticed @clkao's linked comment in the opening description.  Since #5372 creates an application-level terminal manager, we can easily shut down terminals when the Notebook server is stopped (similar to running kernels).

I'll go ahead and add that to the PR.  If anyone disagrees, please let me know.

**Comment by RaghavendraSingh** [comment]
Hi, Any update on this feature? 
Also, until this feature becomes available, is there a workaround for culling terminal sessions?

**Comment by kevin-bates** [comment]
PR #5372 was created a few weeks back.  I'm hoping to have it reviewed shortly.  If you'd like to take it for a spin and report back on that PR, it would be appreciated.
