### ISSUE TITLE
Markdown table alignment stopped working

### ISSUE THREAD

**Issue by waynebliu** [jupyter/notebook#3919]
| col1 | col2 | col3 |
|:-|-:| :-: |
| left aligned | right aligned | centered |
| A | A | A |

In Jupyter, now it's always right aligned!

It's one thing enforce right-alignment for consistency reasons as described in jupyter/notebook/pull/2534. It's another to stop supporting features in Markdown as described by the link in the Help bar, currently pointing to:

https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/
https://help.github.com/articles/organizing-information-with-tables/#formatting-content-within-your-table

Furthermore, the user gets no messaging to let them know that they're using unsupported features, i.e. the :---, :---:, and ---: tokens to describe justification.

**Comment by ian-r-rose** [comment]
I believe this is a bug in marked+GFM: they are using obsolete HTML `align` attributes instead of CSS, and those are *very* low precedence. See also a possible fix + discussion in jupyterlab/jupyterlab#5301

**Comment by baer95** [comment]
I don't really understand what the current status on table alignment is in jupyter notebook... so please correct me if something is wrong? Also, i comment here, since this is the issue with the most recent activity about the not-working markdown table alignment.

There is an effort to keep feature parity with the jupyterlab, which stops the Jupyter notebook from switching from marked to a different markdown renderer.
And the default for table alignment should be right-align, which also makes sense when working with numbers.
But marked uses the html align attribute (to be GFM-compliant) for custom alignment using `:-`, `:-:` or `--:` which gets overridden by the right-align default?

Is there an intention to support custom table alignment this in the future?

And as I understand it, there is the option of extending marked with a custom renderer to do things differently in order to get custom alignment working?

Another possible way to achieve this was given in the marked-issue where they discussed GFM-compliance: https://github.com/markedjs/marked/issues/1211#issuecomment-385314667
Would introducing such a line lead to Jupyter notebook not being on par with jupyterlab or is this a possible way to go?

Thank you for your clarifications!

**Comment by jasongrout** [comment]
> There is an effort to keep feature parity with the jupyterlab, which stops the Jupyter notebook from switching from marked to a different markdown renderer.

Here's a partial answer in the time I have right now. It's the other way around: JLab is keeping parity with the notebook, which prevents JupyterLab from switching to a different markdown renderer (if the notebook switched, lab would most likely do the same). But the bigger issue is that in reality, both the notebook and lab are keeping parity with the user expectations for millions of existing notebooks, which makes it hard for either to switch.

**Comment by nealmcb** [comment]
Thanks, @ian-r-rose for your note above
> See also a possible fix + discussion in jupyterlab/jupyterlab#5301

Has anyone looked to see if that approach from JupyterLab would resolve this issue for Jupyter Notebook?

**Comment by SpencerPark** [comment]
@nealmcb I have a PR open that fixes this issue. It is not the same approach because the notebook was not broken in the same way that jupyterlab was. It completely omitted the alignment in the rendered output.

The fix is essentially a patch to marked to use style instead of align (in the same way it was being blocked before but this time it modifies instead of removing the output) which takes precedence over a CSS default allowing jupyter to give the default of right alignment in CSS but markdown tables to override it if an alignment is specifically set. See #4130.

**Comment by jkpubsrc** [comment]
This bug has been filed eight months ago and patched six months ago. When will this fix be available to the public? The most recent stable versio does *not* contain this fix.

**Comment by qris** [comment]
@jkpubsrc it 

> This bug has been filed eight months ago and patched six months ago. When will this fix be available in a release? The most recent stable version does _not_ contain this fix.

All versions of 6.0.0+ appear to include the fix.
