### ISSUE TITLE
Extend the notebook server with a new editor

### ISSUE THREAD

**Issue by janschulz** [jupyter/notebook#399]
I'm currently playing with the idea to extend the notebook server with an editor for knitpy (knitr in python, see https://github.com/JanSchulz/knitpy). For that I was looking for a way to register an editor for a filetype, but it seems that is hardcoded in the [javascript](https://github.com/jupyter/notebook/blob/master/notebook/static/tree/js/notebooklist.js#L398). Are there any plans to make that extensionable?

The usecase would be: if I click on a `*.pymd` file, the editor for knitpy files gets opened (like `/edit`, but with a `/knitpy/edit` path) . This editor was installed as an extension, similar to how the `/nbextensions` (https://github.com/ipython-contrib/IPython-notebook-extensions) extension is handled.

**Comment by minrk** [comment]
There are no such plans at the moment, but it shouldn't be too hard to add an extension point for it.

**Comment by JanSchulz** [comment]
This could also be a way to implement a shiny like dashboard with e.g. http://www-01.ibm.com/software/ebusiness/jstart/dynamicdash/

-> Define a new fileformat (basically an ipynb with a different ending?) -> let the backend send all cells to the kernel and send the output to the frontend -> if it is a widget, they can communicate, otherwise only static stuff is send.

**Comment by janschulz** [comment]
This looks to be implemented (or implementable) in jupyterlab so can probable by closed.

**Comment by Carreau** [comment]
> This looks to be implemented (or implementable) in jupyterlab so can probable by closed.

Good point. Thanks; and if/when you are going this route, please send us feedback on the API of lab !
Extremely appreciated !
