### ISSUE TITLE
Merge cells shortcut

### ISSUE THREAD

**Issue by foebu** [jupyter/notebook#425]
Is it only me or the merge cell shortcut Shift+M doesn't work anymore?

I tried on different machines with the version 1.0.0.

Thanks.

**Comment by Carreau** [comment]
I think you mean 1.0 of Jupyter ? (Notebook is 4.0, but details,  details) 

In 4.0 (notebook) you can use Shift-J/K to select multiple cells and Shift-M will merge all the selected cells.

![mergeme](https://cloud.githubusercontent.com/assets/335567/9855321/7abdc97c-5ac2-11e5-821f-31b9af55326d.gif)

**Comment by tritemio** [comment]
Good to know, I also though it was a bug. @Carreu is there any existing documentation for the notebook UI?

**Comment by tritemio** [comment]
@Carreau, as a user I totally missed this because I didn't realize the shortcut help dialog in the notebook has an hidden scrollbar showing more shortcuts.

**Comment by mirage007** [comment]
Is there a way we can make Shift-M still work like it used to? I don't see why disabling it completely unless the user presses Shift-J/K is a good interface. If there's only one cell selected, why not do what it always used to do (merge below)? 

The reason I find it not intuitive is that the 'extend cell selection above/below' hotkey isn't really an option an user would look for if they didn't know what it did beforehand, especially since it's not part of any menu items either.

**Comment by tritemio** [comment]
@mirage007, this has been already proposed: https://github.com/jupyter/notebook/issues/509, please follow up there.
