### ISSUE TITLE
Notebook is running code.py file when a notebook is started from a specific kernel

### ISSUE THREAD

**Issue by BharathNuke** [jupyter/notebook#4255]
This is my working directory
![jup_issue](https://user-images.githubusercontent.com/16669414/49681333-1b1aa600-fac6-11e8-9a40-31530f630ac6.png)
when ever I start a new notebook with Python(pyt) kernel then I can see code executing from code.py file.
![jup_iss2](https://user-images.githubusercontent.com/16669414/49681381-cb88aa00-fac6-11e8-9c6b-25c6e04f1ab4.png)

This happens when there exists a file with name code.py and kernel is Python(pyt)

pyt is a conda env

**Comment by BharathNuke** [comment]
Here, contents of kernel.json
```
{
 "argv": [
  "/home/panther/anaconda3/envs/pyt/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python (pyt)",
 "language": "python"
}
```

**Comment by kevin-bates** [comment]
Thanks.
Could you share where your `code.py` file is located (ideally relative to your working directory) and whether you've determined if its location matters?  Sorry, I meant to ask that in my previous response.

This issue probably belongs in either the [ipykernel](https://github.com/ipython/ipykernel) (because that's the process that is running at the time) or [ipython](https://github.com/ipython/ipython) (because it has a `code.py `file as part of its magics and I have a hunch this may be related) repos.  However, since those repos share primary contributors with this project, I'm cc-ing some here for their opinions and insight.

cc: @minrk, @Carreau

**Comment by minrk** [comment]
`code.py` is part of the [Python standard library](https://docs.python.org/3/library/code.html), which is the source of the issue. In general, for interactive Python sessions, you need to be careful to avoid having files with the same name as modules, either in the standard library or top-level package names. Subfiles such as the `code.py` in IPython shouldn't be affected by this due to Python 3's absolute imports (`from . import code` always resolves inside a package).

**Comment by BharathNuke** [comment]
Thanks, I will avoid naming files same as modules.
