### ISSUE TITLE
Tornado=6.0.1 creating error for python2.7 notebook

### ISSUE THREAD

**Issue by DumbMachine** [jupyter/notebook#4484]
I get the below error, when I try to run jupyter notebook. This has happened with multiple envs i have. This issue is related to tornado version 6.0.1 ( if I'm not wrong)
![image](https://user-images.githubusercontent.com/23381512/54471669-af418b00-47e2-11e9-884b-e9d2ec530b43.png)

**Comment by DumbMachine** [comment]
If it helps, downgrading the version of tornado to 5.0 gets rid of the above issue.
`
pip install tornado=5.0
`

**Comment by yavalvas** [comment]
It looks that your problem is related to the version of Python which is no longer supported by Tornado:
[what's new in 6-0-0](https://www.tornadoweb.org/en/stable/releases/v6.0.0.html#what-s-new-in-tornado-6-0)
So you have type annotation in your tornado package which is used since python3.5:
[https://www.python.org/dev/peps/pep-0484/](PEP-0484).
It would be better to migrate to a supported version of Python or keep supported version fixed.

**Comment by DumbMachine** [comment]
It was a requirement to use python2.7 for me, I made this issue to help others who might face this issue. Now that it's clear, I suppose the issue can be closed?

**Comment by yavalvas** [comment]
Yes, it can be closed.

Here is a list of packages which won't support python2.7 in their new versions:
[https://python3statement.org/](https://python3statement.org/)

tornado and jupyter-notebook are between them.

Python devguide changes:
[EOL date](https://github.com/python/devguide/pull/344)
