### ISSUE TITLE
Enable Vim/Emacs/Sublime modes

### ISSUE THREAD

**Issue by rattrayalex** [jupyter/notebook#453]
The "editor" experience in Jupyter is a little weak right now, but modern CodeMirror has support for Vim/Emacs/Sublime - style bindings, even if they are incomplete. It would be terrific to have them user-configurable without requiring custom JS. 

It might even make sense to enable Sublime mode as the default, given its steady rise in market share (and the keybinding similarity to other newly-popular editors, like Atom).

**Comment by Carreau** [comment]
Hello @rattrayalex, you can already configure the modes to be vim/emacs/sublime, see the different tips and receipes on the internet regarding custom.js and frontend config. 

Thanks.

**Comment by rattrayalex** [comment]
Hi @Carreau , thanks for your note. This issue is in regards to enabling those options from the GUI, without needing to edit `custom.js`.

**Comment by Carreau** [comment]
One of the problem with doing UI,  is that most of these config are from
sublibraries, and there are literally an infinite amount of configuration
option. So the UI will probably be a blank textfield.

**Comment by rattrayalex** [comment]
I'm just suggesting three buttons - Vim, Emacs, or Sublime. If that's too much clutter, maybe just making Sublime the default. 

Does that make sense?

**Comment by Carreau** [comment]
> If that's too much clutter, maybe just making Sublime the default.

The problem is not that much the clutter but the slippery slope, if you add a UI element people assume it will switch live, which is more implementation, also you need to implement a dynamic module loading for keymap which is probably an afternoon of work + roughly 1h/week of support for questions and bug report. 

But then why only keymap ? Why not indentUnits ? Indent with tabs instead of space ? visible tabs as now you want to know if you use tab ? if you have visible tabs, user request all visible characters to have a visible representation. 

Only  looking at codemirror without plugin you get 20 configuration options which don't have more reason to not have an UI than another. Potentially with options that might differ in between code cell, and markdown cell. 

That's only looking at codemirror. You can add notebook theme, folding/scrolling of output area, buttons in toolbar, etc...

So the line we define for now is: "if you want to configure, you have to go through extension or write JSON/js by hand". It is not definitive and if/when we have more manpower and people actually willing to write **and maintain** a genearal configuration panel we can reconsider. 

For the time cost/benefit  ratio lean toward not doing it.

**Comment by rattrayalex** [comment]
Yeah, I definitely hear you on adding a UI element. The maintenance sounds like a pain. 

Should I open a separate issue to suggest making Sublime Text keybindings the default? I imagine it's a separate conversation. Here are some numbers though: http://stackoverflow.com/research/developer-survey-2015#tech-editor

**Comment by Carreau** [comment]
> Should I open a separate issue to suggest making Sublime Text keybindings the default?

You can try, but changing a default will 

1) Piss off people that now have the current keymap in their muscle memory and understand what we did. 
2) Confuse user that don't understand we can change keymap and why suddenly things don't work as before
3) Force us to revise all potential conflict OS/Browser/Physical Layout to see if there is conflict. 

So a change will most likely not happend soon if it happens.

**Comment by rattrayalex** [comment]
fair enough! oh well.
