### ISSUE TITLE
Jupyter Notebook won't load on Github

### ISSUE THREAD

**Issue by manishchalana** [jupyter/notebook#4582]
Opening this again as this is a pending issue and does not work for many (See issue #3555)

"Sorry, something went wrong. Reload?" for the notebooks. Please have a look.

Tried on Chrome, Firefox and Opera but does not work on either

**Comment by thoughtsociety** [comment]
Gists or not, this happens too frequently.
Just created a new notebook with Google colab and used their intrinsic feature to push it to my github either as a gist or regular file. It gives the 'something went wrong reload' error and I cannot view this on github.

**Comment by sickmint79** [comment]
bump.  i can see some other people's, public, notebooks; rendering as expected.

my own private ones are doing so poorly; not rendering with the same common error above.  they seemed to do so spottily in the past, with no change on my end, sometimes working and sometimes not.  

i don't really understand why others are working fine, and mine are not.  they are not complex code or anything either.  i have no idea what a workaround might be if one exists.  this makes it much more painful to share/demo example code.  please advise.

**Comment by fhuthmacher** [comment]
yeah this happens like 90% of the time. Is there any way to change the load time or maybe get a static version of it first?

**Comment by parrt** [comment]
This is likely github's issue but maybe the jupyter folks can push on them?

**Comment by jasongrout** [comment]
Please file a support request to GitHub: https://github.com/contact

We have no control over how GitHub renders notebooks. I don't know if they even see these issues raised here. It's much more productive to file the support request to GitHub so they can be aware of the issue and hopefully fix it.

**Comment by jasongrout** [comment]
c.f. #3555 and #3035

**Comment by DanielGoldfarb** [comment]
**To anyone reading this** ***who works for github.com, or who knows someone who works for github.com:***

I have been grappling with the `Sorry, something went wrong. [Reload?]` issue for months. I have many notebooks in many repositories. ([One such example is here](https://github.com/matplotlib/mplfinance/tree/master/examples)).

Whenever the notebooks fail with `Sorry, something went wrong. [Reload?]`, _the same notebook will be fine some time later_, where “_some time later_” can be anywhere from several minutes to several hours (up to maybe a day). However that doesn’t mean that it won’t start failing again several hours after that!

I am convinced **github.com** is using a service (hosted somewhere) to render notebooks, and that sometimes this service either gets into a bad state, or crashes; when that happens notebooks won’t render until the service is bounced, or somehow has its “good” state restored.  

(possibly this could also be a network issue in just reaching the service to render notebooks, but based on my observations i am more convinced of the "bad" state service hypothesis).

I would be happy to volunteer my time to help investigate the issue, if it is otherwise not a priority for github.com to allocate the resources. Please let me know if there is anything I can do to help.

**Please note:** This can be very inconvenient, even embarrassing, to say the least, when I am trying to provide support to users of my public repositories and they tell me that the notebooks to which I direct them are not rendering.

Thank you.
P.S.  I have tried reporting this issue to github.com support but, so far, no response.

**Comment by parrt** [comment]
Agreed. It's absurd how often github fails to render.

**Comment by DanielGoldfarb** [comment]
@parrt 
Terence,
  Perhaps we can organize a grass roots effort to have a lot of people request, through https://support.github.com/contact , that this issue be fixed?
   --Daniel

**Comment by parrt** [comment]
hiya @DanielGoldfarb. The CEO at github knows and promised improvements (saw on twitter) but that was a while ago.   I'm really curious what the issue is.

**Comment by qemtek** [comment]
This is a huge downside of GitHub. I'm trying to follow Amazon's guides to develop on SageMaker and every example points to a jupyter notebook hosted on GitHub...
