### ISSUE TITLE
Syntax highlighting issue with Python f-strings

### ISSUE THREAD

**Issue by kevin-fang** [jupyter/notebook#4721]
If single quotes are placed in curly brackets inside f-strings, then the following text doesn't get highlighted.

<img width="802" alt="error" src="https://user-images.githubusercontent.com/9577819/60119844-66885f00-974d-11e9-86a8-d4f8eb1cf524.png">

<img width="266" alt="error2" src="https://user-images.githubusercontent.com/9577819/60119885-8ddf2c00-974d-11e9-8d1e-26eaf3d59541.png">

**Comment by ihincks** [comment]
I ran into the same issue with tho following nested f-string:

```
f"{7:0{3}}"
```

**Comment by tommp4** [comment]
+1 on that, just tried it using a brand new virtualenv with only jupyter installed. Also breaks when switching double quotation marks with single quotation marks and vice versa. 

Furthermore, as we can see in the original image posted in this issue, the syntax highlighting will make it seem like there is an error on the line, when in reality it will execute just fine.

**Comment by benlindsay** [comment]
I still run into this issue over a year after this post. Are there any fixes or workarounds for this?

**Comment by kevin-bates** [comment]
This issue strikes me more like something related to IPython than anything handled by Notebook.  So, checking there I find this: https://github.com/ipython/ipython/issues/10567.  You might want to look at what of `pygments` you're using and whether there are open issues there.  I suspect once there, you might find this: https://github.com/pygments/pygments/issues/1340

I'm closing this issue here since its not anything that Notebook can address.

**Comment by ihincks** [comment]
FWIW, I just checked in my current environment, and all of the examples above are now working, including the bad indentation bug. So it has been fixed in the pipeline somewhere...

**Comment by kevin-bates** [comment]
@ihincks - thank you for the update.  

Would you mind posting the output of `pip freeze` so others can see what versions might be applicable for things?  If not, then perhaps just the version for `pygments` since that appears to be the primary package here.  Thank you.
