### ISSUE TITLE
Kernal Error 

### ISSUE THREAD

**Issue by ietuday** [jupyter/notebook#4851]
Kernal is not able to start.

I'm using 
Jupyter: 5.7.8
Anaconda 1.9.7
Python3.7

I'm attaching screenshots.
Please help. Thanks in advance
![Screenshot from 2019-08-31 15-01-49](https://user-images.githubusercontent.com/14893665/64062112-8120fd80-cc00-11e9-93e8-6e56284f6cfc.png)
![Screenshot from 2019-08-31 14-52-12](https://user-images.githubusercontent.com/14893665/64062113-81b99400-cc00-11e9-8684-7fd873dddf7d.png)

**Comment by kevin-bates** [comment]
Hi @ietuday.  I think we're going to need more information to help with this.  Since you didn't get a clear error message, I suspect the kernel _process_ has started and appears alive (from the notebook server's perspective), but there's an issue with completing the startup.

There may be information on the console on which `juptyer notebook` was performed (or, preferably a redirect file).  If that doesn't show anything useful, I recommend restarting notebook with debug enabled (e.g., `jupyter notebook --debug ...`) and try starting the kernel again.  Once in this position, please provide **all** output from the start of the notebook's startup to the end of its output.  Hopefully some golden nuggets will be present.  I would also recommend waiting 30-60 seconds after the kernel start request to capture the log output, just in case there's a timeout condition met, etc.

**Comment by ietuday** [comment]
Thanks for response
**Failed to start the kernel**
Traceback (most recent call last):
  File "/home/uday/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/home/uday/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/uday/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 67, in post
    model = yield gen.maybe_future(sm.get_session(path=path))
  File "/home/uday/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 170, in get_session
    return self.row_to_model(row)
  File "/home/uday/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 209, in row_to_model
    raise KeyError
KeyError

**Comment by ietuday** [comment]
@kevin-bates When I start juptyer notebook in debug mode.

Following console printed,

![Screenshot from 2019-09-02 17-01-30](https://user-images.githubusercontent.com/14893665/64111975-984c2080-cda3-11e9-9134-b5c16e2f3ef3.png)

Can you have a look and let me know what I'm doing wrong?

**Comment by ietuday** [comment]
I solved the issue.
Problem with the name of the file

Thanks for response
