### ISSUE TITLE
Impossible to shutdown notebooks from running tab in notebook>=6.0.0

### ISSUE THREAD

**Issue by mpacer** [jupyter/notebook#5033]
When going to `/tree#running` there is a listing of notebooks as well as a shutdown button for each notebook
![image](https://user-images.githubusercontent.com/2482408/68257411-00a7c000-ffe8-11e9-917b-3ec18b7d5814.png)

if I click Shutdown it should send a DELETE request & get back a 204 No Content response from the sessions API. Removing the notebooks session from the listing

![image](https://user-images.githubusercontent.com/2482408/68257476-495f7900-ffe8-11e9-92b6-0b0531f6da4d.png)

As of notebook>=6.0.0 clicking the shutdown Button doesn't even trigger the request to the sessions API. As a result it is impossible to shut down notebooks from the Running tab. 

This works in 5.7.8 and so would be a regression.

**Comment by dbrucknr** [comment]
I noticed this issue as well.

I'm not an experienced developer, but I was poking around in the source files for anaconda and discovered three files that looked promising:

/anaconda3/bin/launch_instance
/anaconda3/bin/list_instances
/anaconda3/bin/kill_instance

Since this issue is open, can anyone verify whether these files are relevant to a resolution?

**Comment by jacksonloper** [comment]
This is indeed broken on, e.g. the docker image `jupyter/datascience-notebook` running `Chrome 78.0.3904.108 (Official Build) (64-bit)` on Ubuntu.

**Comment by rgbkrk** [comment]
Was this the same as #4865, which was fixed in https://github.com/jupyter/notebook/pull/4939?

**Comment by mpacer** [comment]
Fantastic, great catch @rgbkrk!
