### ISSUE TITLE
Jupyter does not work with Grammerly

### ISSUE THREAD

**Issue by jeffheaton** [jupyter/notebook#5123]
I've been using www.grammarly.com, which is a popular spelling and grammar checker.  It would be really nice if Jupyter supported this in the markdown cells.  In this case, I am using the Grammarly Chrome extension.  It works in nearly any web input box I've worked with, even the GitHub issue editor that I am using to type this.

Not sure what you want more in the way of details.  Installing the free version of Grammarly and attempting to use it on a markdown editor will show this problem.

**Comment by aishrock006** [comment]
Not sure for Grammar checker but for spell checker you could enable spellchecker from Nbextensions.
You can find the blog to enable spellchecker from this site:

http://qingkaikong.blogspot.com/2018/09/spell-checking-in-jupyter-notebook.html

**Comment by jeffheaton** [comment]
@aishrock006 Yes I know about that.

**Comment by dniku** [comment]
The spellchecker available as an nbextension is too bare-bones compared to Grammarly. Although I'm not sure the problem should be solved by Jupyter rather than by Grammarly.

**Comment by AnirudhDagar** [comment]
Adding Grammarly to Jupiter will be very helpful.

**Comment by an5ir** [comment]
Hi, is there any further update on this?

**Comment by kevin-bates** [comment]
@an5ir - no update.  I agree this would be a nice feature, but it will likely need to be contributed by the community due to a lack of active maintainers.  I would also recommend focusing this effort in JupyterLab - which will also provide better development support.

**Comment by jeffheaton** [comment]
Most apps support Grammarly out of the box.  Probably it is good to look at what in the Jupyter notebook is non-standard in a way that it breaks Grammarly.  The root cause probably has other issues as well.

**Comment by scot-certifai** [comment]
Looking forward to this issue to get addressed. Having Grammarly support for Jupyter will definitely be a life-saver especially for teaching material development! 🙏

**Comment by richardcherron** [comment]
LanguageTool has a plugin that approximates a solution, albeit with LanguageTool instead of Grammarly. 
You can select all text in a markdown cell, then right click and send it to LanguageTool.
You have to copy-and-paste to get edited text back to Jupyter Notebook, but I find this easier than exporting to HTML, opening in Word, then updating my markdown cell to match the Grammarly feedback in Word.

**Comment by brucefwu** [comment]
I did some investigating and have a good idea of what's going on. Here are some facts about Grammarly's functionality:

* It automatically targets `<textarea>` tags on a website.
* It provides specialized support for popular web apps such as Google Docs.
* It ignores any text contained in `<pre>` tags and several other tags. `<pre>` stands for preformatted text and is a popular method for displaying code on a website. Below is the relevant line in Grammarly's source code:
`l.ignoredTags = new Set(["PRE", "CODE", "BLOCKQUOTE", "STYLE", "SCRIPT", "NOSCRIPT", "IMG", "SVG", "CANVAS", "AUDIO", "VIDEO", "IFRAME", "EMBED", "OBJECT", "BUTTON"])`

As a result:

* The comment box on this issues page is a `<textarea>` tag. Therefore Grammarly works here.
* Markdown cells in Jupyter notebooks are wrapped in `<pre>` tags while being edited, and there's no `<textarea>`. Therefore Grammarly does not work there.
* The behaviour is interesting while editing Markdowns on GitHub, such as a README. The editor is wrapped in a `<textarea>`, so the Grammarly button appears. However, all the code are wrapped in `<pre>` tags, so it sees no text to analyze and the button isn't clickable.

Unfortunately, I think the only way we can resolve this issue is to ask Grammarly to specifically support Jupyter.

**Comment by kevin-bates** [comment]
Hi @brucefwu - this is excellent information, thank you!

Do you happen to know how to go about asking Grammarly to add support and what kind of information they might need?
Since, to the best of my knowledge, the frontends between Notebook and JupyterLab are quite different, I wonder if it might be more worthwhile to focus on this from the perspective of Lab.

**Comment by brucefwu** [comment]
You can send Grammarly feedback through this form: https://www.grammarly.com/extension-uninstall

One of the options is it "doesn't work on my favorite websites". If enough people mention Jupyter (and perhaps Markdown editors in general), it might get their attention.

In JupyterLab 2.2.6 I can select the Markdown cell currently being edited using `document.querySelector(".jp-MarkdownCell.jp-mod-selected")`, and the text within can be accessed using `document.querySelector(".jp-MarkdownCell.jp-mod-selected").innerText`. This info might be helpful for their team.

**Comment by sotastica** [comment]
Yessss! Everyone that got into these posts should go to the form https://www.grammarly.com/extension-uninstall and follow the steps that @brucefwu said to lobby the upgrading for Grammarly to work appropriately on Jupyter Lab.
