### ISSUE TITLE
Scrolling jitter when text exceeds visible window width

### ISSUE THREAD

**Issue by bitworm** [jupyter/notebook#513]
i'm using mac osx 10, chrome browser.  When one of my lines of code exceeds the visible window width, vertical scrolling becomes quite choppy, alternating between horizontal and vertical scrolling.  It's choppy enough that I prefer to create line breaks in my code, but that is a bit harder to read.

System info:

    $ python -c "import IPython; print(IPython.sys_info())"

{ 'default_encoding': 'US-ASCII',
'ipython_path': '/Users/(user_name)/anaconda/lib/python2.7/site-packages/IPython',
'ipython_version': '4.0.0',
'os_name': 'posix',
'platform': 'Darwin-15.0.0-x86_64-i386-64bit',
'sys_executable': '/Users/(user_name)/anaconda/bin/python',
'sys_platform': 'darwin',
'sys_version': '2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08) \n[GCC 4.2.1 (Apple Inc. build 5577)]'}

**Comment by ellisonbg** [comment]
This is a known bug that we have long term plans to fix. @sccolbert or @blink1073 could hopefully look at this...

**Comment by ellisonbg** [comment]
Do you have a good example notebook (gist?) that you could share that shows this?

**Comment by bitworm** [comment]
I made a public gist, "jitter_example.ipynb" but I'm having issues with it. Please tell me if you can't see it and I'll try again.

**Comment by sccolbert** [comment]
@bitworm what's the link to the gist?

**Comment by bitworm** [comment]
ah! here: https://gist.github.com/bitworm/a9103913530b421b4ca6

**Comment by blink1073** [comment]
Might it make sense intercept the scroll event and zero-out the horizontal scroll if it is less than some ratio of the vertical scroll component?

**Comment by sccolbert** [comment]
I'm looking into it now. CodeMirror is doing some suspect things when it gets scroll events.

**Comment by ellisonbg** [comment]
Thanks for looking at  this!

On Tue, Oct 6, 2015 at 4:02 PM, S. Chris Colbert <notifications@github.com>
wrote:

> I'm looking into it now. CodeMirror is doing some suspect things when it
> gets scroll events.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/513#issuecomment-145981462>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by sccolbert** [comment]
What's happening here is a result of [this line](https://github.com/codemirror/CodeMirror/blob/52e48afa6d3d508c83115c142c3f8fd0dc477108/lib/codemirror.js#L4002) in CodeMirror. The logic is a bit subtle, but I will try to explain as best I can.

When you scroll using the trackpad or the mouse wheel, the browser delivers `'wheel'` events to the DOM element under the cursor. These events bubble up the DOM like most other mouse events, and if `preventDefault()` is not called on the event, the default action will be to scroll the element/page. For kinetic (momentum) scrolling, the browser continues to generate `'wheel'` events until the scrolling comes to rest. As the page is scrolled, the element under the cursor will change and hence the element receiving the `'wheel'` events will change.

This explains the immediate observation that the jitter (slow scrolling) only occurs when the cursor is over a CodeMirror cell. When the cursor is in the left margin of the notebook, or in-between CodeMirror cells, the CodeMirror `'wheel'` event handler is not invoked.

The line of code linked above prevents the event default action, which means the browser **will not** scroll the page when that code path is taken. So, why do we get *some* vertical scrolling during jitter, instead of *none*? The answer is that a wheel event can contain both `deltaX` and `deltaY` values simultaneously. When using an actual mouse wheel, the `deltaX` will be zero. But when using a trackpad, `deltaX` will only sometimes be zero (because humans are imprecise).

When CodeMirror encounters any non-zero `deltaX` value, it will take the code path linked above, which will unconditionally prevent the default scroll action. Presumably, this is done so that horizontally scrolling the editor does not *also* horizontally scroll the page. This is a reasonable behavior, but leads to the unfortunate issue we are seeing here where it falsely prevents the vertical scroll of the page. When scrolling with a trackpad, what we end up with is a stream of `'wheel'` events with small `deltaX` values, some of which are zero. As those events are processed by CodeMirror, it prevents the default scroll action on all except the ones with a zero `deltaX`. It is *these* events which actually get handled by the browser and cause the vertical scroll. But since they are only processed sporadically, the result is jitter.

There is [a clause](https://github.com/codemirror/CodeMirror/blob/52e48afa6d3d508c83115c142c3f8fd0dc477108/lib/codemirror.js#L3974) near the top of CodeMirror's `'wheel'` event handler, which bails early if there is no content to scroll. This explains why the jitter is only observed for CodeMirror cells which have overflowing content (i.e. visible scrollbars).

I can see a few solutions for this problem:
  1. Comment out the line which prevents the event default in the version of CodeMirror we ship. I tested this locally and it works fine. The downside is possible horizontal scrolling of the page when horizontally scrolling the cell contents. This probably won't actually be a problem since the notebook itself rarely has horizontal scrollbars. It could be a problem in a larger app though. This is the simplest "solution".
  2. Apply some form of thresholding to the `deltaX` value in the version of CodeMirror we ship, so that only significant `deltaX` values are actually handled by CodeMirror. This is also reasonably simple.
  3. Update the code cell so that only the active editing cell is actually a live CodeMirror instance. At all other times, the code cell should just be a static rendering of the code mirror content. [CodeMirror.runMode](https://codemirror.net/demo/runmode.html) can be used for this. This is a bit of work, but is the cleanest solution and would also likely solve some other performance concerns we have. IMHO this is the "right" way to solve the problem.

A few other random thoughts:
  - This issue probably only affects OSX users using trackpads. These pads allow simultaneous X and Y scrolling. My experience with other trackpads is that they will "lock" so that only a single axis is scrolled at a time. [Relevant Stack Exchange](http://apple.stackexchange.com/questions/106935/fix-mavericks-vertical-scrolling-lock-jerky-scrolling-accidental-safari-back).
  - CodeMirror is using deprecated APIs on `'wheel'` event (`'wheelDeltaX'` vs `'deltaX'`, etc.) which generate very different numbers from the standard APIs. This may exacerbate the situation. The standard APIs are support by all major browsers back to IE9.
  - I think it may be worth pinging Marijn to get a bit more insight into his intentions behind preventing the default scroll action, and the use of the deprecated event APIs.

**Comment by minrk** [comment]
@sccolbert thanks for digging into the details! I'm okay with disabling the prevent-default, as long as we take a little time to check why it's there, and verify that its reason for being there is no longer (if ever) relevant.

We can bring up the API usage with CodeMirror in the meantime as a longer-term solution.

**Comment by sccolbert** [comment]
@minrk  I'll make a PR for this for now. Have you interacted with Marijin before, or would you like me to ping him?

**Comment by sccolbert** [comment]
I PR'd against CodeMirror, since the notebook installs it as a bower component. Keeping around a separately patched version would be a bit of overhead.

**Comment by jasongrout** [comment]
@sccolbert - would this also come up on mobile devices?  Do touch scrolling events come across as wheel events?

**Comment by sccolbert** [comment]
It will affect any device which generates simultaneous `X` and `Y` deltas. I believe `'wheel'` events are used on mobile as well.

**Comment by sccolbert** [comment]
CodeMirror fix merged. w00t!

**Comment by ellisonbg** [comment]
Any idea of when they will release with the fix?

**Comment by ellisonbg** [comment]
Also, great news!!!

**Comment by sccolbert** [comment]
Don't know when the next release will be, but we can update the bower dependency to point to a commit hash in the meantime.

**Comment by ellisonbg** [comment]
Great, I think it makes sense to point to the commit hash in the meantime.

On Wed, Oct 7, 2015 at 3:21 PM, S. Chris Colbert <notifications@github.com>
wrote:

> Don't know when the next release will be, but we can update the bower
> dependency to point to a commit hash in the meantime.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/513#issuecomment-146301696>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jasongrout** [comment]
The release cadence indicates it will be released Oct 20: http://codemirror.net/doc/releases.html

**Comment by bitworm** [comment]
Awesome response guys - looking forward to checking this out!
