### ISSUE TITLE
.jupyter Directory is ReadOnly filesystem

### ISSUE THREAD

**Issue by zengzhengrong** [jupyter/notebook#5204]
I want setup jupyter gateway to use vscode remote connect,I use k8s to install jupyter

```
jupyter kernelgateway --KernelGatewayApp.generate_config=True
```
error
```
Read-only file system: '/home/jovyan/.jupyter/jupyter_kernel_gateway_config.py'
```

I use chmod as root
```
root@dask-jupyter-66dcc6f759-7crh6:~/.jupyter# chmod -R 777 ./
```
error
```
chmod: changing permissions of './': Read-only file system
chmod: changing permissions of './..2020_02_05_06_06_33.045497720': Read-only file system
chmod: changing permissions of './..2020_02_05_06_06_33.045497720/jupyter_notebook_config.py': Read-only file system
```
```
~/.jupyter# ll
```
```
total 16
drwxrwxrwx 3 root   root  4096 Feb  5 06:06 ./
drwsrwsrwx 1 jovyan users 4096 Feb  5 06:23 ../
drwxr-xr-x 2 root   root  4096 Feb  5 06:06 ..2020_02_05_06_06_33.045497720/
lrwxrwxrwx 1 root   root    31 Feb  5 06:06 ..data -> ..2020_02_05_06_06_33.045497720/
lrwxrwxrwx 1 root   root    33 Feb  5 06:06 jupyter_notebook_config.py -> ..data/jupyter_notebook_config.py*
```
So, It's a filesystem RO 
I check the container with docker inspect command
```
   "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/b68f4ec4-1c86-4204-902a-e85676db678a/volumes/kubernetes.io~configmap/config-volume",
                "Destination": "/home/jovyan/.jupyter",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
```

**Comment by kevin-bates** [comment]
Hi @zengzhengrong, this strikes me as more of a k8s deployment issue for how its configured to mount directories into your container.

Based on your screen shots and a google search, I suspect you're hitting this issue: https://github.com/helm/charts/issues/13124 which is due to the [dask helm charts](https://github.com/helm/charts/tree/master/stable/dask) using a config map to introduce configuration into the container.  And that appears to be a kubernetes issue where [configMap destinations become read-only](https://github.com/kubernetes/kubernetes/issues/62099) as a means to address a [different issue](https://github.com/kubernetes/kubernetes/issues/60814).  

I'm not sure if this could be used as a workaround, but you can affect the locations for configuration, runtime and data files by [setting the appropriate environment variables](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html).  These can then be pointed to more "static" locations within the image itself.  Of course, this would imply that any data from the configMap would likely be ignored.

You might also checkout [Enterprise Gateway](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/), which is essentially Kernel Gateway with the ability to launch remote kernels in their own pods, etc., and offers [images for use on Kubernetes](https://hub.docker.com/r/elyra/enterprise-gateway).  This may be more than what you need for your vscode integration, but I thought I'd toss it out there.

**Comment by zengzhengrong** [comment]
@kevin-bates ,Thank~!
 Use PVC  deal with that
