### ISSUE TITLE
Use environment variable to set port to run on

### ISSUE THREAD

**Issue by json2d** [jupyter/notebook#5212]
So i get this is how you would set the port via cli:

```
jupyter notebook --port 9999
```

Is there currently a way to set this and other run options with an environment variable eg:

```
export JUPYTER_PORT=9999
jupyter notebook
```

**Comment by kevin-bates** [comment]
No, this CLI option is not currently tied to an environment variable.  I believe the preference in notebook is to avoid that where possible (although containerized envs make this approach attractive).

**Comment by json2d** [comment]
@kevin-bates yep you said it - it would be useful for working with containers. thanks for the info

**Comment by kevin-bates** [comment]
Hi @json2d .  I'm inclined to propose we identify a small set of container-relevant options and env variable associations to them.  The previously mentioned preference may have been more of a "generally speaking" thing, and I think there could be value here.

I think `port` and probably `ip` are two.  You'd definitely want to disable `port-retries` for this, but that could be something that's part of a "baked in" configuration.

I'm going to re-open this until we determine the best approach forward here.  Thanks.

**Comment by json2d** [comment]
At the moment there are a few steps involved in running Jupyter containers with the port set via an environment variable `NB_PORT`.

First you need to create a `jupyter.Dockerfile` in your project:
```Dockerfile
FROM jupyter/minimal-notebook:latest

ENV NB_PORT 8888

# run notebook on 0.0.0.0:8888
CMD jupyter notebook --port=$NB_PORT --no-browser
```

Second you need to build and tag the image:

```
$ docker build --file jupyter.Dockerfile --tag json2d/jupyter .
```

Finally you can run the image with `NB_PORT` set using something like:

```bash
$ export NB_PORT=9999
$ docker run --env NB_PORT -p $NB_PORT:$NB_PORT json2d/jupyter
```

It gets a bit messy when you go to publish/expose the port, but that's just what you have to do with Docker.

So if Jupyter did automatically used an environment like `NB_PORT` for the port, then potentially you could *skip the first two steps* and just use the official image `jupyter/minimal-notebook:latest` directly:
```bash
$ export NB_PORT=9999
$ docker run --env NB_PORT -p $NB_PORT:$NB_PORT jupyter/minimal-notebook:latest
```

**Comment by kevin-bates** [comment]
Thanks @json2d.  Your example reminds me about the [docker-stacks](https://github.com/jupyter/docker-stacks) images and how this _could_ be accomplished via the various start scripts.  However, there are many who might build their own images and would like this capability.

I think by adding support for specifying port via an env wihtin the application, we can allow for the existing behaviors to override.  For example, the _default_ port number would essentially come from the env, but the CLI option `--port` would override the env.  So, if you did this, ...

```bash 
export JUPYTER_PORT=8899
jupyter notebook --port 9999
```
Notebook would start on port `9999`, but with this...
```bash 
export JUPYTER_PORT=8899
jupyter notebook
```
it would start on port `8899`.  I believe this would allow for existing behaviors to not be side affected by someone now having JUPYTER_PORT in their env.


Because its imperative that port-retries be zero in these circumstances, yet its current default is `50`, I think we'd also want back it by an env as well.  If the port-retries env is not set, the default of `50` would still be used.  That said, I don't feel as strongly about `ip`.  So perhaps only the two port-based variables would have env backing.

I can try to put together a pull request for this if you agree.  Once a PR is present, I think others might find a need to comment.

**Comment by json2d** [comment]
I think having the CLI option `--port` overriding the env and setting port-retries to zero both seem sensible. I haven't used the `ip` option much so I couldn't really comment about its usefulness as an env var.

**Comment by kevin-bates** [comment]
@json2d - I submitted the PR above.  It would be great if you could take it for a spin in your env to see how things work out.
