### ISSUE TITLE
Response for preflight has invalid HTTP status code 405

### ISSUE THREAD

**Issue by jdfreder** [jupyter/notebook#522]
`api/kernels` Method `OPTIONS` raises a 405 when the notebook server is ran using Python 3 instead of Python 2.  This happens when attempting to connect to a kernel using the notebook Javascript. 

#493 

@rgbkrk @zischwartz @blink1073

**Comment by minrk** [comment]
It's showing 200 OK for me. Are you sure your Python 3 is running master?

**Comment by zischwartz** [comment]
I think I've figured it out, at least partially.

Building from master in this repo, everything works. The problem occurs when I also install [ipywidgets](https://github.com/ipython/ipywidgets). Then I get the 405 on the OPTIONS preflight to the kernel endpoint, as seen here.

![screen shot 2015-10-05 at 1 03 31 pm](https://cloud.githubusercontent.com/assets/77472/10288340/4e8f231e-6b66-11e5-9cdc-ccb53a38e533.png)

**Comment by zischwartz** [comment]
Aha! Using the `--no-deps` option when installing ipywidgets, doesn't cause this issue.

**Comment by minrk** [comment]
What do you have for `pip list` after installing the widgets?

**Comment by zischwartz** [comment]
After installing **with** `--no-deps`
```
root@ecd6c216754b:/srv/notebook# pip list
chardet (2.0.1)
colorama (0.2.5)
decorator (4.0.4)
docutils (0.11)
gyp (0.1)
html5lib (0.999)
ipykernel (4.0.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.0.3)
Jinja2 (2.7.2)
jupyter-client (4.0.0)
jupyter-core (4.0.6)
MarkupSafe (0.18)
path.py (8.1.1)
pexpect (3.3)
pickleshare (0.5)
Pillow (2.3.0)
pip (7.1.2)
Pygments (1.6)
pyzmq (14.7.0)
requests (2.2.1)
roman (2.0.0)
setuptools (18.3.2)
simplegeneric (0.8.1)
six (1.5.2)
Sphinx (1.2.2)
traitlets (4.0.0)
urllib3 (1.7.1)
wheel (0.24.0)
```

After installing the widgets **without** `--no-deps`:
```
backports.ssl-match-hostname (3.4.0.2)
certifi (2015.9.6.2)
chardet (2.0.1)
colorama (0.2.5)
decorator (4.0.4)
docutils (0.11)
functools32 (3.2.3.post2)
gyp (0.1)
html5lib (0.999)
ipykernel (4.0.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.0.3)
Jinja2 (2.7.2)
jsonschema (2.5.1)
jupyter-client (4.0.0)
jupyter-core (4.0.6)
MarkupSafe (0.18)
mistune (0.7.1)
nbconvert (4.0.0)
nbformat (4.0.1)
notebook (4.0.5)
path.py (8.1.1)
pexpect (3.3)
pickleshare (0.5)
Pillow (2.3.0)
pip (7.1.2)
ptyprocess (0.5)
Pygments (1.6)
pyzmq (14.7.0)
requests (2.2.1)
roman (2.0.0)
setuptools (18.3.2)
simplegeneric (0.8.1)
six (1.5.2)
Sphinx (1.2.2)
terminado (0.5)
tornado (4.2.1)
traitlets (4.0.0)
urllib3 (1.7.1)
wheel (0.24.0)
```

**Comment by minrk** [comment]
I'm not sure how it's working when you use `--no-deps`, since it shows that you don't have the notebook package at all. When you install with dependencies, you do have the notebook and it is 4.0.5, which is current stable and doesn't have the fix referred to here. Perhaps you have notebook master installed in a different env?

**Comment by zischwartz** [comment]
Well I think the notebook is being installed by [this line in the Dockerfile](https://github.com/jupyter/notebook/blob/master/Dockerfile#L54):
```
RUN pip3 install --pre -e .
```
Which I guess doesn't make it into `pip list`.

**Comment by minrk** [comment]
@zischwartz `pip instal -e` will indeed show up in `pip list`. Do you have your own Dockerfile that's exhibiting this problem?

**Comment by minrk** [comment]
I just realized: if you are using that Dockerfile, `pip` is `pip2`, and the notebook is only installed with pip3. What do you see for `pip3 list`?

**Comment by jdfreder** [comment]
Aside: I should have mentioned, I opened this issue for @zischwartz when I was visiting last Thur/Fri.

**Comment by minrk** [comment]
Here's what I suspect is happening:

- jupyter-notebook master is installed with pip3
- installing ipywidgets with pip installs with Python 2, depends on the notebook, and installs `jupyter-notebook` for Python 2.
- now `jupyter-notebook` is pointing to the Python 2 version, which is current stable, instead of dev.

If we were installing Python 2 in an env, instead of the default, this wouldn't be an issue. Similarly, this wouldn't be an issue if the command were `python3 -m notebook` instead of `jupyter notebook`.

**Comment by zischwartz** [comment]
Hmm ok, I was installing the widgets with both `pip2` and `pip3`. And yeah here's my [Dockerfile](https://github.com/zischwartz/notebook/blob/master/Dockerfile#L60-L61).

With `--no-deps`
```
root@edc33e53a4d9:/srv/notebook# pip3 list
chardet (2.2.1)
colorama (0.2.5)
decorator (4.0.4)
docutils (0.11)
html5lib (0.999)
ipykernel (4.0.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.0.3)
Jinja2 (2.7.2)
jsonschema (2.5.1)
jupyter-client (4.0.0)
jupyter-core (4.0.6)
MarkupSafe (0.18)
mistune (0.7.1)
nbconvert (4.0.0)
nbformat (4.0.1)
notebook (4.1.0.dev0, /srv/notebook)
path.py (8.1.1)
pexpect (3.3)
pickleshare (0.5)
Pillow (2.3.0)
pip (7.1.2)
ptyprocess (0.5)
Pygments (1.6)
pyzmq (14.7.0)
requests (2.2.1)
roman (2.0.0)
setuptools (18.3.2)
simplegeneric (0.8.1)
six (1.5.2)
Sphinx (1.2.2)
terminado (0.5)
tornado (4.2.1)
traitlets (4.0.0)
urllib3 (1.7.1)
wheel (0.24.0)
```


Without `--no-deps`:
```
root@fb072da9ecb2:/srv/notebook# pip3 list
chardet (2.2.1)
colorama (0.2.5)
decorator (4.0.4)
docutils (0.11)
html5lib (0.999)
ipykernel (4.0.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.0.3)
Jinja2 (2.7.2)
jsonschema (2.5.1)
jupyter-client (4.0.0)
jupyter-core (4.0.6)
MarkupSafe (0.18)
mistune (0.7.1)
nbconvert (4.0.0)
nbformat (4.0.1)
notebook (4.1.0.dev0, /srv/notebook)
path.py (8.1.1)
pexpect (3.3)
pickleshare (0.5)
Pillow (2.3.0)
pip (7.1.2)
ptyprocess (0.5)
Pygments (1.6)
pyzmq (14.7.0)
requests (2.2.1)
roman (2.0.0)
setuptools (18.3.2)
simplegeneric (0.8.1)
six (1.5.2)
Sphinx (1.2.2)
terminado (0.5)
tornado (4.2.1)
traitlets (4.0.0)
urllib3 (1.7.1)
wheel (0.24.0)
```

**Comment by minrk** [comment]
Yup, then what I described above is what's happening. Since `ipywidgets` depends on the notebook package, when you install it for Python 2, it's installing `jupyter-notebook` for Python 2, overwriting the version previously installed with Python 3. Python 3 still has the latest version of the notebook, it's just not what's getting launched when `jupyter notebook` is called. If we change the command to be `python3 -m notebook` instead of `jupyter notebook` there would be no problem.

**Comment by ngoldbaum** [comment]
I'm getting this using both a python2 and python3 notebook server, trying to run thebe. I set up IPython using a python3 virtualenv on Ubuntu 14.04. In this context pip is always referring to python3's pip.

Any idea how I can work around this?

**Comment by ngoldbaum** [comment]
Here's my `pip list` if it helps:

```
Cython (0.23.3)
decorator (4.0.4)
ipykernel (4.1.0)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.0.3)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.0.0)
jupyter-console (4.0.3)
jupyter-core (4.0.6)
MarkupSafe (0.23)
matplotlib (1.4.3)
mistune (0.7.1)
nbconvert (4.0.0)
nbformat (4.0.1)
nose (1.3.7)
notebook (4.0.5)
numpy (1.10.0.post2)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (7.1.2)
ptyprocess (0.5)
Pygments (2.0.2)
pyparsing (2.0.3)
python-dateutil (2.4.2)
pytz (2015.6)
pyzmq (14.7.0)
qtconsole (4.0.1)
setuptools (18.2)
simplegeneric (0.8.1)
six (1.10.0)
sympy (0.7.6.1)
terminado (0.5)
tornado (4.2.1)
traitlets (4.0.0)
wheel (0.24.0)
yt (3.2.1)
```

**Comment by minrk** [comment]
@ngoldbaum this is fixed in master, so installing notebook from master should do it.

**Comment by ngoldbaum** [comment]
@minrk thanks for pointing out the obvious to me, sometimes I need that :)

Switching to notebook master lets me get past the 405 error.

**Comment by minrk** [comment]
@ngoldbaum thanks!

**Comment by zischwartz** [comment]
Hey, if this is still a problem for anyone else, it turns out we can address this from the clientside. Taking [this one line](https://github.com/oreillymedia/thebe/blob/master/static/services/kernels/kernel.js#L205) out of Thebe, seems to prevent the `OPTIONS` preflight altogether, and the backend deals with it fine. That's merged in Thebe on master now.

**Comment by rgbkrk** [comment]
Oh awesome.

**Comment by jdfreder** [comment]
Thanks for sharing that @zischwartz
