### ISSUE TITLE
jupyter kernel permission denied error 13

### ISSUE THREAD

**Issue by koushiktulasi** [jupyter/notebook#5257]

**Comment by kevin-bates** [comment]
I can only assume this is a duplicate of #5124.  I can't tell what solutions you have attempted, but now that notebook 6.0.3 is available, please try upgrading notebook.  

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.1`, respectively.  If the problem still persists, please provide the updated traceback since it should provide more helpful information.

Thanks.

**Comment by koushiktulasi** [comment]
thanks @kevin-bates  for your response my issue is resolved
