### ISSUE TITLE
Jupyter holds local variable even though it is deleted

### ISSUE THREAD

**Issue by Gomathynathan** [jupyter/notebook#5263]
[Localvariablebug.pdf](https://github.com/jupyter/notebook/files/4285047/Localvariablebug.pdf)
	In the attached Jupyter notebook, I have initialized “i” and printed it. In the same notebook, I changed “i” to “j” while initializing but it still holds the value of “i” that I initialized in my earlier code. And prints the last value of “i” though there is no “i” in the second screenshot.
But if I run the same example above in PyCharm, for the 2nd code it throws an error as there is no “i” in the code.

**Comment by kevin-bates** [comment]
Hi @Gomathynathan.  I believe this is working as designed because you're still talking to the same kernel instance in the second test.  Deleting a cell that contains a variable's declaration does not remove that variable from the kernel's running state.  This is the same behavior you'd see running in the Python REPL and that's a good way to think of a kernel - its just a REPL instance.  Had you restarted the kernel prior to introducing `'j'`, you'd have received an error that `'i'` is undefined because a new kernel/REPL was instantiated.

I'm not familiar with PyCharm's Notebook integration, but my hunch is that they must be restarting the kernel in this scenario.

**Comment by felixdivo** [comment]
Yes, this works as intended (and can be closed, right?).

**Comment by kevin-bates** [comment]
Good idea - thanks for the reminder. :smile:
