### ISSUE TITLE
%%capture line magic not found, but is recommended when typo is introduced.

### ISSUE THREAD

**Issue by Helveg** [jupyter/notebook#5269]
When I use `%%capture` I get:

    UsageError: Line magic function `%%capture` not found.

And when I use `%capture` I get:

    UsageError: Line magic function `%capture` not found (But cell magic `%%capture` exists, did you mean that instead?).

Also, `%%capture` worked on this machine yesterday.

**Comment by kevin-bates** [comment]
Hi @Helveg - this sure sounds odd.

For whatever reason, IPython is thinking that [`%%capture` is invoked as a _line magic_](https://github.com/ipython/ipython/blob/master/IPython/core/interactiveshell.py#L2291-L2297).  

You might check if the context in which you're using `%%capture` has changed at all.  Otherwise, I recommend moving this issue to the [IPython repo](https://github.com/ipython/ipython) where you'll likely get better traction.

**Comment by Helveg** [comment]
I accidentally added an import line above it and didn't connect the 2 together. Maybe the error can be updated to reflect that cell magic should appear on the first line of a cell.

**Comment by kevin-bates** [comment]
@Helveg - Glad to hear you're moving forward.  Your suggestion sounds good, but this would need to take place from the IPython repo. As such, I'm going to close this issue.

**Comment by sirius0503** [comment]
This gets solved, when I move the cell magic to the top of all imports and line magics as mentioned by @Helveg

**Comment by shawnSilveira** [comment]
Make sure '%%capture' is the first command to execute. All statements preceding '%%capture' in the cell should be removed including comments
