### ISSUE TITLE
Kernel not connected

### ISSUE THREAD

**Issue by DanielvdC** [jupyter/notebook#5357]
Hi,
First of all, I know that this is a very well documented question (see for example [#4444](https://github.com/jupyter/notebook/issues/4444);[#4439](https://github.com/jupyter/notebook/issues/4439), but all of the verified working solutions do not apply to me.

I keep getting this error:
```
[W 12:13:02.254 NotebookApp] KernelRestarter: restart failed
[W 12:13:02.255 NotebookApp] Kernel b56b775d-5eea-4ad5-b380-c38c53ce184c died, removing from map.
[W 12:13:47.704 NotebookApp] Timeout waiting for kernel_info reply from b56b775d-5eea-4ad5-b380-c38c53ce184c
[E 12:13:47.708 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: b56b775d-5eea-4ad5-b380-c38c53ce184c)
[W 12:13:50.457 NotebookApp] 404 GET /api/kernels/b56b775d-5eea-4ad5-b380-c38c53ce184c/channels?session_id=c4ed0a9dc63145b18b042397f2e6a15c (::1): Kernel does not exist: b56b775d-5eea-4ad5-b380-c38c53ce184c
[W 12:13:50.472 NotebookApp] 404 GET /api/kernels/b56b775d-5eea-4ad5-b380-c38c53ce184c/channels?session_id=c4ed0a9dc63145b18b042397f2e6a15c (::1) 18.42ms referer=None
[W 12:13:52.693 NotebookApp] Replacing stale connection: b56b775d-5eea-4ad5-b380-c38c53ce184c:c4ed0a9dc63145b18b042397f2e6a15c
```

With the additional information that certain modules cannot be found:
`ModuleNotFoundError: No module named 'tensorflow'
`

However, the modules not found seem to keep changing. 

As for solutions, I've tried downgrading tornado, updating all my packages as well as Jupyter. Moreover, I've tried to do a hard reset by creating a new iPython profile, but none of this has worked for me as of yet. I have also reinstalled Anaconda and even did a reset of my laptop, which also did not have any effect. I've tried using Spyder and Jupyterlab, and the problem seems to happen there as well.

I'm currently graduating and time is ticking away. Any help is much appreciated!

**Comment by kevin-bates** [comment]
Hi @DanielvdC,

Based on your information, I suspect the kernel is starting initially, then failing.  Are you able to execute, or attempt to execute, a cell in the Notebook prior to this condition?

Because `tensorflow` is not part of the Notebook packages, this reference must be coming from something in your notebook, or part of the kernel.json file containing the kernel specification your notebook ipynb file is using.

> However, the modules not found seem to keep changing.

Strange.  Are you making any changes to your configuration between instances of this?  Are you using conda envs?

I don't think this issue is related to the issues you referenced.  Instead, I would recommend the following...

1. Run `jupyter kernelspec list` to locate the kernel's directory corresponding to the kernel you're using.  Go to the directory and provide the information contained in the `kernel.json` file.  Of particular interest is the `argv:` stanza, but providing the contents would be helpful.  

2. Restart the notebook server with DEBUG enabled - `jupyter notebook --debug` (and any other options you typically set).  

3. Provide the complete kernel startup console output through to the error.  

4. Provide the output of `jupyter --version`.  

5. Does the code you're executing run fine outside a notebook?

**Comment by DanielvdC** [comment]
> Hi @DanielvdC,
> 
> Based on your information, I suspect the kernel is starting initially, then failing. Are you able to execute, or attempt to execute, a cell in the Notebook prior to this condition?
> 
> Because `tensorflow` is not part of the Notebook packages, this reference must be coming from something in your notebook, or part of the kernel.json file containing the kernel specification your notebook ipynb file is using.
> 
> > However, the modules not found seem to keep changing.
> 
> Strange. Are you making any changes to your configuration between instances of this? Are you using conda envs?
> 
> I don't think this issue is related to the issues you referenced. Instead, I would recommend the following...
> 
> 1. Run `jupyter kernelspec list` to locate the kernel's directory corresponding to the kernel you're using.  Go to the directory and provide the information contained in the `kernel.json` file.  Of particular interest is the `argv:` stanza, but providing the contents would be helpful.
> 2. Restart the notebook server with DEBUG enabled - `jupyter notebook --debug` (and any other options you typically set).
> 3. Provide the complete kernel startup console output through to the error.
> 4. Provide the output of `jupyter --version`.
> 5. Does the code you're executing run fine outside a notebook?

Hi @kevin-bates,

Thanks for your honest help and time spent! Fortunately, I've managed to fix the issue. I'm actually not sure what the problem was, but [@Marcsprk43's](https://github.com/conda/conda/issues/9367#issuecomment-558863143) suggestion did the trick by creating a new environment.
