### ISSUE TITLE
Logout button doesn't work in text file editor

### ISSUE THREAD

**Issue by z3ky** [jupyter/notebook#5399]
How to reproduce:
- install jupyter with conda
- run a notebook
- create a new text file
- click logout

**Comment by kevin-bates** [comment]
hi @z3ky - thanks for opening this issue.  Did you want to take a look at fixing this?  

This might be helpful for whoever may be interested: https://github.com/jupyter/notebook/pull/1739

**Comment by jpcastil** [comment]
I am interested in beginning to contribute! 
I was able to replicate the issue (w/o using conda), I could take a look.

**Comment by kevin-bates** [comment]
Hi @jpcastil - that would be fantastic!  I probably won't be able to answer questions you might have, but I'd be happy to work with your changes at a functional level.  I'm sure we can find someone to review the changes.

I'm going ahead and assigning this issue to you.  Should you decide not to work on it, please feel free to post such a comment and we'll unassign it.

**Comment by jpcastil** [comment]
Thank you @kevin-bates! I'll get to it!

**Comment by jpcastil** [comment]
Hey @kevin-bates, I found the bug, module to enable logout is not included. 

I'm having some trouble deciding where the best place to put it is. 
From what I have gathered, all assets are in /static, external libraries/frameworks are in /components, and the names of folders/ files are often self-explanatory. 

But what about folders like 'base' or 'bidi'? I sense it would be important to know what these folders should house/ should not house moving forward. 

Is there a document to learn about the hierarchy/purpose of static files?

**Comment by z3ky** [comment]
ThanK you @kevin-bates and @jpcastil. I can test the fix after its integration.

**Comment by kevin-bates** [comment]
Thank you @z3ky - that will be helpful.

@jpcastil - those are the kinds of questions that I'm hoping someone with front-end notebook experience will answer.  A quick search doesn't really yield anything relative to notebook per see although there are general hits regarding the use of static files in web servers.

I believe 'bidi' is referring to bi-directional functionality that is also supporting right-to-left languages, etc.  I'm assuming 'base' relates to files that might be common to multiple other directories, but that's nothing more than a hunch.  I'm sorry I can't be more specific.

**Comment by jpcastil** [comment]
I implemented a bug fix.. This is my first attempt at an open source contribution so I'm not entirely sure what's next. 
I made sure to follow the contribution guidelines, and I'm at the "pull request" stage. I am familiar with pull requests, but what would be the appropriate branch? 
From my **master -> <fill_in_blank>.**

**Comment by kevin-bates** [comment]
Fantastic - sounds like you're following all the right paths.

In scanning the current forks of notebook, it doesn't look like you've forked notebook yet.  You should probably do that first, then clone your fork, instead of notebook.  This will allow you to work relative to your fork.

I always update my master branch from 'upstream' (which is the remote reference to notebook), then create my working branch off my updated master.  I usually choose a branch name indicative of what I'll be working on.  Some prefer to have their working branch reference the issue number as well, but I feel like that just takes up characters - since your pull request will reference the issue anyway.

For this particular issue, a branch name like `fix-textfile-logout` would be fine - but its up to you.

Once your branch is updated and the commit(s) are in place, you then push your branch to your fork (typically referred to as `origin`, although the notebook repo is probably referenced as `origin` right now - so you might look at the options to `git remote` to rename your current `origin` to `upstream`,  it might be good to do that before cloning your branch.) Then create the PR that references the pushed branch.

I hope that helps.

**Comment by jpcastil** [comment]
@kevin-bates Thank you for your continuous support, I really appreciate it. 

As far as forking the the current notebook, I believe I have done so, unless I forked the wrong one. 
https://github.com/jpcastil/notebook holds my fork w/ the bug fix. I have already pushed the code, but next time I will adopt the workflow you recommended (branch, etc). 

I see the option to create a pull request, but I am unsure of what branch to select. master, 4.x, 4.0.x, etc. I would assume 4.0.x since the x would hold bug fixes (Semantic Versioning)? Not sure.

**Comment by kevin-bates** [comment]
Please direct your PR to the notebook/master branch.  We can decide if this warrants any back-ports, but given the issue has existed for some time, I suspect that won't be necessary.

**Comment by jpcastil** [comment]
Cool! PR opened!

**Comment by z3ky** [comment]
I integrated @jpcastil's fork into my single-user image. Logout in text file editor works now.

**Comment by kevin-bates** [comment]
Resolved by #5406 - thank you @jpcastil!
