### ISSUE TITLE
macbook pro won't shut down after using jupyter notebook

### ISSUE THREAD

**Issue by SpankMobley** [jupyter/notebook#5557]
Hi. I'm a newb, so please forgive my ignorance. I spent some time searching for this issue both within github and just plain googling, but was unable to find a thread with the same issue.

After using Jupyter Notebook (Python 3.7) on my Macbook Pro (Catalina 10.15.5), my laptop won't shut down. I don't have any servers running, and am able to successfully log out of Notebook. But after selecting "shut down," the apps disappear from my desktop, showing just my background (as if it is preparing to shut down), and it just stays that way for hours until I get fed up and hold down the power button. When I start the laptop up again, I get notification of an improper shutdown.

This happens every time I use Jupyter Notebook. What am I not doing?

**Comment by kevin-bates** [comment]
Very strange.  I suspect there's some notebook kernel still running that is tying up the shutdown process.  Since this scenario is expensive to test (time-wise), I would recommend first ensuring the notebook server is completely shut down prior to rebooting your mac.  If you're using ipykernel (the python kernel), I think you could say things are completely shutdown if these two commands produce zero results:
```
ps -ef | grep jupyter | grep -v grep
ps -ef | grep ipykernel | grep -v grep
```
When you run a notebook, are you performing any long-running operations or anything that might use lower-level libraries and/or background processes?  Perhaps there's a side-effect on the system shutdown from what you're doing in the notebook.  

You also might try a shutdown sequence where you start/stop notebook w/o starting a kernel.  If that works, then you could focus more on the kernel interaction area.

**Comment by SpankMobley** [comment]
Looks like it was a bad OS install. Thank you for your help.
