### ISSUE TITLE
Automate open and run a Jupyter notebook in windows

### ISSUE THREAD

**Issue by vevek-git** [jupyter/notebook#5564]
Am trying to automate opening and running a Jupyter Notebook in windows. Windows scheduler seems to be the right answer for scheduling tasks. However, am not able to open a Jupter Notebook and execute it using scheduler. Here is what i have tried so far: 
I created a VBScript as below and saved it as jupter.vbs

```
    Set WinScriptHost = WScript.CreateObject("WScript.Shell")
    WinScriptHost.Run "C:\\Users\vevek.seetharaman\AppData\Local\Continuum\anaconda3\Scripts\activate.bat & jupyter notebook C:\Users\vevek.seetharaman\OneDrive - Shell\Script Automation\Notebooks\Mouse Movements.py --notebook-dir=C:\Users\vevek.seetharaman\OneDrive - Shell\Script Automation\Notebooks", 1
    Set WinScriptHost = Nothing
```

Mouse Movements.py is the name of the file i would like to open(a sub question would be can it be a .ipynb file?)

On top of this a bat file to execute this command on Cscript.exe and here is the file and i saved this as jupyter.bat

    `start /B "C:\Windows\System32\cscript.exe" "C:\Users\vevek.seetharaman\Downloads\jupyter.vbs"`

Now before scheduling if i run jupyter.bat it opens CMD.exe and then shuts down. It does not open and run the notebook as i intended it to. Help here would be great.

**Comment by kevin-bates** [comment]
A few observations:
- notebook (to the best of my knowledge) only recognizes notebook files (ipynb) as non-parameter arguments.
- You'll probably want to quote your paths since they have spaces and argument parsers can't make that determination.
- I would imaging the notebook file argument doesn't need to be fully qualified but, instead, qualified relative to the `notebook-dir` value.
- If you just want to run the notebook to completion as a service, I would strongly recommend looking at https://github.com/jupyter/nbclient and/or https://github.com/nteract/papermill.  These applications are dedicated to running notebooks directly.

I'm not familiar with the Windows scheduler so can't really comment on that portion.  However, there might be examples on some of the referenced repos for how those applications can be integrated with things like that.

**Comment by vevek-git** [comment]
Thanks for ur input Kevin-bates, i was able to execute similar script using Papermill
