### ISSUE TITLE
Kernel in Not Starting in Jupyter

### ISSUE THREAD

**Issue by vikramnist** [jupyter/notebook#5581]
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

**Comment by kevin-bates** [comment]
Please provide the contents of the console[*] in which you launched your notebook server. It will have details that may shed more light into the issue's cause.

[*] Please do NOT provide screenshots of your console, but instead select/copy then paste into your response.  Screenshots, unless they depict the issue directly, are virtually useless since one cannot use the content (without typing it) to perform further troubleshooting.

**Comment by vikramnist** [comment]
ImportError: cannot import name 'Pdb' from 'IPython.core.debugger'

**Comment by vikramnist** [comment]
ImportError: cannot import name 'Pdb' from 'IPython.core.debugger' (C:\Users\sugyani\anaconda3\lib\site-packages\IPython\core\debugger.py)
[W 22:26:38.182 NotebookApp] KernelRestarter: restart failed
[W 22:26:38.182 NotebookApp] Kernel d6539ee5-8915-459e-a4e8-60056ea9e27f died, removing from map.
kernel d6539ee5-8915-459e-a4e8-60056ea9e27f restarted failed!
[W 22:26:38.221 NotebookApp] 410 DELETE /api/sessions/100d4956-04d6-4e14-ab1d-1efd7fbf6d37 (::1): Kernel deleted before session
[W 22:26:38.222 NotebookApp] Kernel deleted before session
[W 22:26:38.225 NotebookApp] 410 DELETE /api/sessions/100d4956-04d6-4e14-ab1d-1efd7fbf6d37 (::1) 5.98ms referer=http://localhost:8816/notebooks/Untitled17.ipynb?kernel_name=python3
[I 22:26:59.842 NotebookApp] Saving file at /Untitled17.ipynb

**Comment by kevin-bates** [comment]
I suspect there's more information prior to this on your console.  This [SO hit](https://stackoverflow.com/questions/58399943/importerror-cannot-import-name-pdb-from-ipython-core-debugger) suggests a file named `code.py` since it would conflict with the `import code` statement needed in `pdb.py`.

Generally speaking, local python file names that conflict with Python import statements can be problematic and should be avoided.

Should the issue persist - I would suggest moving this the [IPython repository](https://github.com/ipython/ipython/issues) - closing.

**Comment by vikramnist** [comment]
It worked thank you
