### ISSUE TITLE
Jupyter Notebooks don't like ". imports"

### ISSUE THREAD

**Issue by Programmer103** [jupyter/notebook#5590]
So, I've made a discussion on Stack Overflow about why `opencv` is not working with `jupyter notebook` [here](https://stackoverflow.com/questions/62786036/opencv-gives-an-error-in-the-jupyter-notebook-but-works-in-python-cli/62801516#62801516). Finally, I figured out that `jupyter notebook` doesn't handle `.` imports properly. For example, the following import statement in `opencv`:
```
from .cv2 import *
```
Gives an error in `jupyter notebook`, but not in the Python CLI. If you change it to the following, though:
```
from cv2.cv2 import *
```
It starts working perfectly fine. Is there an easier way to fix this problem than editing the import statements manually by going into the library source code? Also, can this be fixed in `jupyter notebook` so we don't have to change the import statements at all?
**NOTE:** This is also the same case with `stable-baselines` and many other Python libraries (not only `opencv`)

~ Ayush

**Comment by Programmer103** [comment]
Huh. This is kind of weird, but the `.` imports are working again? I don't know what happened exactly, but it just randomly started working again... Can somebody explain what's happening here?

**Comment by Programmer103** [comment]
Okay - in `Jupyter Lab`, its importing `cv2` from `Anaconda` - but whenever I try `.cv2` or `cv2.cv2`, it gives the same error.

**Comment by kevin-bates** [comment]
Hi @Programmer103 - You might try asking this in [IPython](https://github.com/ipython/ipython) or [ipykernel](https://github.com/ipython/ipykernel) since this is specific to those areas.  For these kinds of things, it might help isolate issues by also adding the IPython CLI to your set of scenarios since it's behaviors should more closely resemble that of the python kernel.

**Comment by Programmer103** [comment]
Okay, thanks @kevin-bates - so should I create a new post in `IPython` and delete this one? Also, what do you mean by "adding the IPython CLI to my set of scenarios"?

**Comment by kevin-bates** [comment]
Yes, please create a new issue in IPython or ipykernel.  If the issue is reproducible using IPython CLI, then I'd post there.  If only reproducible from within a notebook cell, start with ipykernel (if that helps).  I'll go ahead and close this issue.  We can still use it for discussion and even re-open should that become necessary.
