### ISSUE TITLE
Image is not visible

### ISSUE THREAD

**Issue by nehavish006** [jupyter/notebook#5642]
I used <img src="/img/profile.jpg"
My img is not visible what shd I do

**Comment by kevin-bates** [comment]
It's tough to determine the context of this question, but I'm assuming you'd like to display an image within a notebook.

In looking into this, there are a couple of things to consider.  
1. the path to the image is relative to the running notebook, so unless your notebook directory is '`/`' (root), you'll likely need to adjust the path.
2. There are a few options (again, path may require adjustment):

From a markdown cell, either of the following should work:
`<img src="/img/profile.jpg"/>`
or
`![image](/img/profile.jpg)`

From a python code cell, this should work:
```python
from IPython.display import Image 

Image("/img/profile.jpg")
```

If your kernel is not ipykernel, you'll likely need to consult the kernel's documentation if you want this produced from a code cell.

I'm going to close this issue since it's not an issue for this repository.
