### ISSUE TITLE
Juypter notebook can't open in github

### ISSUE THREAD

**Issue by candice-lll** [jupyter/notebook#5669]
Hi!!

I upload the juypter notebook but I can't open it. It is said "Sorry, something went wrong. Reload?". I have this issue for over a month. Is my file problem or the platform problem? Thank you!!

**Comment by Zsailer** [comment]
Github's Jupyter notebook rendering is notoriously finicky. Unfortunately, the Jupyter Team has no control over Github's notebook viewer (it's close-sourced). The issue is likely a problem with Github, or your notebook file might be too big to open. 

I suggest using [NBViewer](https://nbviewer.jupyter.org/) for looking at notebooks you've uploaded to Github. That is Jupyter's supported notebook viewer.
