### ISSUE TITLE
Feature Request: If current selected kernel needs more memory, shutdown other not running kernel and release memory or add a OOM check

### ISSUE THREAD

**Issue by drewyang-datavedik** [jupyter/notebook#5707]
For example,
I have 64 GB RAM of total available. 
- A.ipynb is not running, but kernel is still alive and occupying 45GB of memory
- B.ipynb is currently selected and going to run, but it requires 30GB of memory, then shutdown the A.ipynb kernel OR add a OOM check, if it's going to be OOM, suspends the running kernel

Thanks!

**Comment by kevin-bates** [comment]
Hi Drew, thanks for opening this issue.

If we had the desired information (45 of 64 GB in use, but idle, and 30 GB desired), terminating an in-use kernel is probably something we wouldn't want to automate.  Although we do support the culling of idle kernels, that only occurs after a certain period that would indicate the user is probably not using it any longer.  This sounds more like "on-demand culling" - which seems a little risky since that implies a kernel's termination within its idle culling period.

Have you taken a look at the [`nbresuse`](https://github.com/yuvipanda/nbresuse) extensions?  This allows you to gather resource metrics from _local_ kernels and is something we'd like to generalize (across all kernel configurations) in [jupyter_server](https://github.com/jupyter/jupyter_server).  We don't currently have a way to _parameterize_ a kernel's startup, which presumably could include memory requirements, but that's something we'd like to [add in the future](https://github.com/jupyter/enhancement-proposals/pull/46) and, again, in jupyter_server.

I'm wondering if you knew the current utilization provided by nbresuse and that notebook A was no longer in use, then you'd have the information you need to safely shutdown kernel A so notebook B could be executed.  That human element seems highly desired in this scenario.

**Comment by kevin-bates** [comment]
Closing since this is not something Notebook will add due to the transition to jupyter server.  I'm still hopeful for having better resource management controls in jupyter_server though.  That said, this particular use case feels hard to express without also introducing priority to determine if B should terminate A.  If you feel that it is still warranted, please open an issue in [jupyter_server](https://github.com/jupyter/jupyter_server).  Thank you.
