### ISSUE TITLE
csharp cell magic  (%%csharp) is missing from jupyter-notebook 6.1.3

### ISSUE THREAD

**Issue by CBrauer** [jupyter/notebook#5726]
Hey,

I tried to change the kernel in the C# cell programmatically by entering:  %%csharp as the only line in a cell, and I got "UsageError: Cell magic %%csharp not found."

I then ran "%lsmagic" in the next cell and I got a list of "Available line magics".  "csharp" was not in this list.

Can we have this kernel as a default.

Charles

**Comment by kevin-bates** [comment]
Hi @CBrauer.  It sounds like you're running the python kernel and it doesn't support the %%csharp magic.  

> I then ran "%lsmagic" in the next cell and I got a list of "Available line magics". "csharp" was not in this list.

What magics are supported is purely a function of the active kernel. If you wanted the python kernel to support a magic of `%%csharp`, you'll need to open an issue in the [ipykernel](https://github.com/ipython/ipykernel) repo, although I suspect that would be unlikely.

> Can we have this kernel as a default.

If you were using the (presumably) .NET Csharp kernel, you could make it the default kernel by setting the configuration option `c.MappingKernelManager.default_kernel_name = <name of your csharp kernel>`.

Since there's really nothing to address via this repository, I'm going to close this issue.
