### ISSUE TITLE
Changing shortcut of 'run' doesn't work in edit mode

### ISSUE THREAD

**Issue by rightx2** [jupyter/notebook#5794]
I changed shortcut of `run` from `Cmd-Enter` to `Ctrl-Enter` like below:

<img width="937" alt="Screen Shot 2020-10-05 at 13 29 39" src="https://user-images.githubusercontent.com/10606994/95040523-da663500-070e-11eb-83e1-67608aafad99.png">

Problem is that it only works in read mode of the cell, not in edit mode. It makes me push esc key every time before run the cell!

**Comment by cipri-tom** [comment]
I don't understand why this shortcut has changed recently, but it is very annoying that all of a sudden it is `Cmd-Enter` instead of `Ctrl-Enter` and that it cannot be easily modified.

**Comment by kevin-bates** [comment]
I don't think the side-effect of the recent change was intentional.  Unfortunately, I'm not knowledgeable regarding front-end javascript.  Looking at the recent change: https://github.com/jupyter/notebook/pull/5120/files
would it work to restore the `'ctrl-enter'` entry while _leaving_ the `'cmdtrl-enter'` line in place.  This would mean that _either_ cmd-enter or ctrl-enter invoke a cell on mac while other platforms expect only ctrl-enter.

Would someone be willing to give this a try?  Thanks.

**Comment by rightx2** [comment]
I want to run the cell with `ctrl+enter` even in mac os.. but if I changed the key mapping with `ctrl+enter` it works only in read mode, not in edit mode......

**Comment by cipri-tom** [comment]
hi @kevin-bates ,

Thanks for merging the fix ! I've tried it on my side but cannot get it to work :( .

I am now in a new environment, using notebook 6.1.5. Although, as I understand, this fix is not part of this version.
However, I edited `keyboardmanager.js` in my notebook installation (`/miniconda3//lib/python3.8/site-packages/notebook/static/notebook/js/keyboardmanager.js` ), but it doesn't seem to be taken into account.

Adding `'ctrl-enter'  : 'jupyter-notebook:run-cell',` to the mapping does nothing. I;ve also tried lifting the existing `cmdtrl-enter` mapping, but it still works. I think this file is somehow cached but cannot figure out where. Any ideas ? (I have restarted the server, to no avail).

Thank you !
