### ISSUE TITLE
Terminal Manager doesn't seem to cull in updated docker images

### ISSUE THREAD

**Issue by dipen-epi** [jupyter/notebook#5796]
I'm using the internal configs of the notebook in a Z2JH based deployment to kill the kernels and terminals after long spells of inactivity. My notebook configuration looks like this
```
TerminalManager.cull_inactive_timeout=3600
TerminalManager.cull_interval=600
```

These conditions work great when I'm using the default docker image by jupyter/docker-stacks. When I try to build an image on top of the same, the terminals are not getting culled and I cannot see the TerminalManager initialize and run checks every cull_interval.

Are there any dependencies which might be getting affected due to a modified docker image, leading to TerminalManager not applying culling timeouts as expected?

**Comment by kevin-bates** [comment]
Hmm, given you can even create terminals means that you have the `terminado` package available.  This package is silently ignored if it can't be imported, but that's not the issue.

I suspect that this could boil down to the installed notebook version (since this functionality is relatively new `>=6.1.0`), but, again, I doubt you're running a version of notebook older than what's in the base image.

This would leave configuration and perhaps your build isn't picking up the culling config settings.  Do you also have kernel culling enabled and is it appearing 'active' in the logs relative to the updated image?  How are you enabling these config values - CLI or config file?  File configuration values are usually prefixed with `c.` (e.g., `c.TerminalManager.cull_interval=600`) while CLI values are prefixed with `--` (e.g., `--TerminalManager.cull_interval=600`).  Perhaps that's the issue?

Since this is a Hub installation, is the config meant to propagate during the spawn of the notebook server?  But, again, that should be identical across the two images you're using, although its probably something worth checking.

**Comment by dipen-epi** [comment]
Yes, I checked for the `terminado` package and it is available. The notebook version is also the same as the base image I'm using.

I have the kernel culling available as well, which works well in my updated image. I'm passing the settings to kubespawner as arguments with a `--` prefix as 

```
'--MappingKernelManager.cull_idle_timeout=3600', '--TerminalManager.cull_inactive_timeout=3600'
```

I believe that the Hub propagates the settings to the notebook config during spawning, and I can see the notebook server with the propagated args as

```
jupyterhub-singleuser
      --allow-root
      --NotebookApp.shutdown_no_activity_timeout=3900
      --MappingKernelManager.cull_idle_timeout=3600
      --MappingKernelManager.cull_interval=600
      --TerminalManager.cull_inactive_timeout=3600
      --TerminalManager.cull_interval=600
      --ip=0.0.0.0
      --port=8888
      --NotebookApp.default_url=/lab
      --debug
```

However, when I check the logs I am unable to see any TerminalManager culling checks while the MappingKernelManager checks for idle kernels periodically.

**Comment by kevin-bates** [comment]
Hmm - sounds like you've made all the right checks.  I would closely examine the delta between the base image that works and your mods - which I'm sure you've already done.  I'm not familiar with the hub spawner interactions but given other options appear to "flow" and the transitive property holds in computing, there must be something in the installation/deployment of the changes.

Are you at all reinstalling the notebook version or making changes to the base image notebook installation?

Are you able to run your image outside of Hub and see the same results?

If you want to send me your Dockerfile that applies the changes to the base image, I can be another pair of eyes.  Feel free to email me using my GH profile's email.

**Comment by dipen-epi** [comment]
Update: I was able to resolve this, turns out the modified image was being built on a notebook image which predates the addition of TerminalManager culling functionality, while the testing image was a recent one. Updated the base image for the team, and now the terminals are getting culled as expected
@kevin-bates closing this with a note of thanks for the prompt replies! :bowing_man:
