### ISSUE TITLE
error "import linear_model1 from sklearn"

### ISSUE THREAD

**Issue by DeepakKumar2525** [jupyter/notebook#5803]
![image](https://user-images.githubusercontent.com/72614075/95644546-03067a00-0ad5-11eb-8597-0b3fab464bba.png)

[
![Sklearn](https://user-images.githubusercontent.com/72614075/95644481-870c3200-0ad4-11eb-9727-5530baf3eb0f.PNG)
](url)

Please tell me how can i solve above error?

**Comment by deadln** [comment]
It looks like a little typo. Maybe you should write this:
`from sklearn import linear_model`

**Comment by DeepakKumar2525** [comment]
> It looks like a little typo. Maybe you should write this:
> `from sklearn import linear_model`

Thank you for reply but showing same error again.

**Comment by deadln** [comment]
I don't think that problem in conda, because i recently installed Miniconda and scikit-learn and it works fine. Maybe you should try reinstall scikit-learn package. Also try to import linear_model in default Python interpreter. If error will be the same then this is not an Jupyter Notebook issue and you should close this one issue

**Comment by DeepakKumar2525** [comment]
Thank You.

With Best Regards,
Deepak Kumar
