### ISSUE TITLE
Bad config encountered during initialization

### ISSUE THREAD

**Issue by tejas-sme** [jupyter/notebook#5836]
I am getting error when I run `anaconda-project run default --NotbookApp.default_url=/apps/timezones.ipynb`
 
`Bad config encountered during initialization: Error loading argument NotbookApp.default_url['/notebooks/timezones.ipynb', '/apps/timezones.ipynb'], default_url only accepts one value, got 2: ['/notebooks/timezones.ipynb', '/apps/timezones.ipynb'`]

I need to set the default_url to /apps/timezones.ipynb so that notebook opens in appmode. If I don't set, then it opens in notebook mode.
These are the versions I am using:
anaconda-project: 0.8.3
notebook: 6.1.4
appmode: 0.8.0

**Comment by Zsailer** [comment]
Thanks for opening this issue, @tejas-sme.

This looks like an issue with anaconda-project, not Jupyter Notebook. [anaconda-project](https://github.com/Anaconda-Platform/anaconda-project) hardcodes the `default_url` [here](https://github.com/Anaconda-Platform/anaconda-project/blob/3804895ffcea4f2a88747b245fb493a1c0d777bc/anaconda_project/project_commands.py#L167-L178). I would open your issue on that repo and see if they can help. 

I'm going to close this issue here, but feel free to reopen if you keep having issues.
