### ISSUE TITLE
Jupyter NoteBook Ipython

### ISSUE THREAD

**Issue by Mostafa-SHmaisani** [jupyter/notebook#5846]
Task 7
We're finally read to create our master list. Zip the audio_tour_number list to the paintings list and save it as master_list.

Hint: Make sure to convert the zipped object into a list using the list() function.

master_list = list(zip(audio_tour_number, paintings))
Task 8
Print the master_list to the terminal.

print(master_list)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-26-9a66a8f04fd1> in <module>
----> 1 print(master_list)

NameError: name 'master_list' is not defined

**Comment by kevin-bates** [comment]
This message is stating that the kernel cannot find the `master_list` variable in its set of definitions.  If the kernel was just restarted and the initialization of `master_list` occurs in a previous cell, you would get this error as if `master_list` is not defined.  Be sure to execute a cell that initializes `master_list` prior to executing the `print(master_list)` cell within the same lifecycle of the kernel.

Since this is not an issue with this repository, I'm closing for now.  Feel free to report your status as a comment on this issue as that might help others as well.
