### ISSUE TITLE
Error when trying to close jupyter server on remote machine

### ISSUE THREAD

**Issue by abahnasy** [jupyter/notebook#5858]
`^C[I 02:41:50.059 NotebookApp] interrupted
Serving notebooks from local directory: /usr/prakt/w0018/task_carla_autoencoder/notebooks
0 active kernels
The Jupyter Notebook is running at: http://localhost:8888/?token=1e8fabacb6452be484d7203c5cea1e60abd89a33b7308d21
Shutdown this notebook server (y/[n])? y
[C 02:41:51.402 NotebookApp] Shutdown confirmed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1210, in _confirm_exit
    ioloop.IOLoop.current().stop()
  File "/usr/prakt/w0018/.local/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 116, in current
    loop = ioloop.IOLoop.current(*args, **kwargs)
  File "/usr/prakt/w0018/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 263, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.

^C[C 02:44:33.884 NotebookApp] received signal 2, stopping
^C[C 02:44:34.037 NotebookApp] received signal 2, stopping
^C[C 02:44:34.485 NotebookApp] received signal 2, stopping
^C[C 02:44:34.662 NotebookApp] received signal 2, stopping
^C[C 02:44:34.852 NotebookApp] received signal 2, stopping
`
I can't close or relaunch the server? could you please help?

**Comment by kevin-bates** [comment]
I'm not sure what you mean by "remote machine" as the output presented appears as though `<ctrl-c>` (SIGINT) is being issued from the command line.  That said, I don't think that is necessarily germane.

It sure looks like the initial interrupt occurred at an odd spot such that the signal handlers/event loop are in an inconsistent state of sorts.  You might try the following...

1. Does `jupyter notebook list` return any entries?  If so, try `jupyter notebook stop`.  "list" merely reads a file that was produced on the previous startup, but I'm wondering if the interrupt came in prior to that file's creation.
2. Use `ps` to identify the notebook process ID (pid) and issue `kill pid`.  If that `kill` doesn't work, issue the same command with `-9` (e.g., `kill -9 pid`) since that sends a more forceful signal (SIGKILL vs SIGTERM).

To trim the `ps` output, pipe the output to `grep notebook` (e.g., `ps ax | grep notebook` and the pid is the first column).


_Regarding the location in the startup sequence in which the original interrupt occurred, that is extremely early.  Did things appear as though they were hung up?  In trying to reproduce issuing a SIGINT that early, it was very difficult - within seconds of issuing the command - so I'm wondering if that's a hint as why your process ended up in this state in the first place._

**Comment by abahnasy** [comment]
@kevin-bates 
by Remote machine, I mean accessing my university computer cluster through SSH and run jupyter notebooks on them.
I've gone through the above steps and killed the process. However, I encounter the problem everytime I try to launch jupyter notebook again.
I simply uninstalled and re-installed jupyter notebook and now it is working. Thank you
