### ISSUE TITLE
Jupyter notebook is not getting started right with the terminal command.

### ISSUE THREAD

**Issue by 3TInfoTinker** [jupyter/notebook#5868]
Hi,
I'm quite a beginner in both Linus/Ubuntu and Python. I'm receiving the following error as I type [ $jupyter notebook  ] at the terminal. The system provided links are working, but I want to solve this itchy error [1]. Thank you.

 To access the notebook, open this file in a browser: 
**1]        file:///home/kalganiyans/.local/share/jupyter/runtime/nbserver-2697-open.html**

**Comment by kevin-bates** [comment]
Hi @3TInfoTinker - welcome to the community!

> To access the notebook, open this file in a browser:
1] file:///home/kalganiyans/.local/share/jupyter/runtime/nbserver-2697-open.html

This is not an error message, but merely a suggestion for how to access the notebook UI should a browser not open automatically.  The suggestion is to paste the file URI scheme into your browser's address bar and it should resolve to the Notebook UI appearing and managing the files located in the current directory - just as the other links produce.

Are you seeing otherwise?

**Comment by 3TInfoTinker** [comment]
Thank you Mr.@kevin-bates, thank you for your precious time and help.
but
The real itchy thing is that (even it is not a big deal) it must work as per command, so which it is not doing.

I wanted to know that why it is not loading up "jupyter notebook" by just typing it in, instead it is giving me the links to copy and paste in browser?

And this link mentioned above is not working in browser showing the reason of inaccessibility of file "nbwerver-2697-open.html". I use the other links which i did not posted here, because they are working.

if there is any method to edit or recreate this file on its specific location? That's what I wanted to know, just to see the command line Error free.

In old times in DOS the path, config file or autoexec files were used to solve the problems. And now, I'm Zeeeero.🙊

**Comment by kevin-bates** [comment]
Thanks for the additional information.  I believe there have been previous issues opened regarding the browser not opening automatically and it might be worth searching the issues for solutions/workarounds.  Here's one that, on the surface, looks like this issue: https://github.com/jupyter/notebook/issues/5479

Unfortunately, I can't be very helpful with front-ends kinds of issues and that's why you'll see me redirecting where I can.

**Comment by 3TInfoTinker** [comment]
Mr. Kevin, I can't explain how encouraging I feel by your concern. Thank to you, I'm the one asked for help and no doubt you did just great for me. That's so nice [redirecting or referring is helping me too]. I expect your attention for the future too. Godspeed and stay blessed.
