### ISSUE TITLE
Support `%edit` in the notebook

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#59]
Now that we have a text editor in the notebook UI, we can almost make `%edit` work in the notebook.

A `%edit` command is sent as a payload with an absolute path (so, in the Qt console, it assumes you're on the same system as the kernel). The only missing bit to translate the path to a URL is knowledge of the root directory for the notebook server. If the frontend knew this, it could build the URL to edit that file, and open a new tab or an iframe to do so.

This touches again on the issue of how to deal with kernels and servers running on different hosts.

**Comment by minrk** [comment]
I don't think `%edit` will make sense with servers and kernels in separate locations, and it is appropriate to assume that they contents and kernels are on the same filesystem for something like this, and call it unsupported in other contexts.

**Comment by ellisonbg** [comment]
The hackish version is to publish output JS that opens the file in a separate panel (single pane app will help).

**Comment by blink1073** [comment]
We did something like this in the demo app: https://github.com/blink1073/jupyter_demo/blob/master/src/index.ts#L807.
Clicking on a file in the file browser opens a new editor pane with the file contents, using the Contents API.

**Comment by JamiesHQ** [comment]
What is the next step on this issue? Thanks!

**Comment by ellisonbg** [comment]
I agree with @minrk that there is no promise that kernels and notebooks will be in the same place on the filesystem. Because of this, I think it is mixing abstractions and will lead to hackish implementation and user confusion. I would prefer to close this.

The only option I can imagine that would be slightly different is to offer a MIME type that targets an action in the JupyterLab file browser. Then any kernel could send back output that can be clicked on to open a JupyterLab document. On further thought, we already have this as hyperlinks in output in JupyterLab already open the corresponding document in lab.

**Comment by gnestor** [comment]
I'm going to mark this as reference and close as it appears there is no obvious action here...
