### ISSUE TITLE
Unable to run jupyter notebook

### ISSUE THREAD

**Issue by anshyan** [jupyter/notebook#5902]
This is my first time posting and I'm new to Python as well as Jupyter. I apologize if this is not enough info below or incorrect format. I'm running on Windows 10. I'm unable to open a notebook. Here is what I receive when typing in jupyter notebook.

These are the commands which i used:
conda create -n <new_env_name> python=3.6
pip install jupyter
conda install -c anaconda ipykernel   // Trying to add the kernel
python -m ipykernel install --user --name=<new_env_name>

![Capture](https://user-images.githubusercontent.com/11961905/101576275-3b580500-39ff-11eb-9911-75f6052dbfd8.JPG)

(tf-2.2.0) C:\Users\anshu>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\anshu\anaconda3\envs\tf-2.2.0\Scripts\jupyter-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\anshu\AppData\Roaming\Python\Python36\site-packages\jupyter_core\command.py", line 285, in main
    command = _jupyter_abspath(subcommand)
  File "C:\Users\anshu\AppData\Roaming\Python\Python36\site-packages\jupyter_core\command.py", line 125, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-notebook` not found.

**Comment by Yash-Varshney-Creativities** [comment]
try typing `pip install --upgrade pip` and then `pip install --upgrade notebook`. Then try launching it with `jupyter-notebook` or `jupyter notebook` .

**Comment by Zsailer** [comment]
Hi @ashyan, thank you for opening this issue. I suggest opening your issue on the [Jupyter Discourse page](https://discourse.jupyter.org/) since you'll likely receive more timely help there. 

As @Yash-Varshney-Creativities said (thank you for the contribution!), it appears Jupyter notebook is not installed. Try:
```
pip install notebook
```
or 
```
conda install notebook
```
and retry running the notebook using the `jupyter notebook` command.

Closing this issue here. Thanks, all!
