### ISSUE TITLE
Multiple human languages in the interface.

### ISSUE THREAD

**Issue by masasin** [jupyter/notebook#5903]
**Describe the bug**
I think this is a UI bug. A bunch of different languages appear in the console and in the interface.

In the console, some of the text is in Japanese:

```
[I 01:44:21.811 LabApp] ノートブックサーバは cookie secret を /home/jnassar/.local/share/jupyter/runtime/notebook_cookie_secret に書き込みます
[I 01:44:21.967 LabApp] JupyterLab extension loaded from /home/jnassar/.local/pipx/venvs/jupyterlab/lib/python3.8/site-packages/jupyterlab
[I 01:44:21.968 LabApp] JupyterLab application directory is /home/jnassar/.local/pipx/venvs/jupyterlab/share/jupyter/lab
[I 01:44:21.969 LabApp] ローカルディレクトリからノートブックをサーブ: /tmp/fun/demo
[I 01:44:21.969 LabApp] Jupyter Notebook 6.1.5 is running at:
[I 01:44:21.969 LabApp] http://localhost:8888/?token=a1150112efde31e3341131befe89e6f98785692cb7d07b61
[I 01:44:21.969 LabApp]  or http://127.0.0.1:8888/?token=a1150112efde31e3341131befe89e6f98785692cb7d07b61
[I 01:44:21.969 LabApp] サーバを停止し全てのカーネルをシャットダウンするには Control-C を使って下さい(確認をスキップするには2回)。
[C 01:44:21.986 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/jnassar/.local/share/jupyter/runtime/nbserver-401156-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a1150112efde31e3341131befe89e6f98785692cb7d07b61
     or http://127.0.0.1:8888/?token=a1150112efde31e3341131befe89e6f98785692cb7d07b61
[W 01:44:24.282 LabApp] Could not determine jupyterlab build status without nodejs
[I 01:44:35.087 LabApp] Creating new notebook in 
[I 01:44:35.115 LabApp] Writing notebook-signing key to /home/jnassar/.local/share/jupyter/notebook_secret
[I 01:44:35.416 LabApp] Kernel started: 7b5699c4-cb3c-4745-a1bf-1ea35814f0b1, name: python3
1:44:35.416 LabApp] Kernel started: 7b5699c4-cb3c-4745-a1bf-1ea35814f0b1, name: python3

```
And when I create a new notebook, the default name is Naamloos.ipynb, which is in Dutch. The reset of the interface is in English, as expected.

**To Reproduce**
1. Type `jupyter lab` in the terminal.
2. Create a new notebook.

**Expected behavior**
Everything should be in English. If not, I'd expect everything to at least be in the same language.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 20.2.
 - Browser Firefox
 - Version 83.0

**Additional context**
I installed jupyter using `pipx`.

The languages installed on my system are (in order):

- American English (Default)
- British English
- Japanese
- French
- Dutch
- German

I know all these languages, so it's not a problem in terms of understanding, but having to switch languages constantly is not exipected, and it can be problematic for e.g. learners.

I live in Belgium right now. According to the README in the i18n folder, it checks `$LANG`, which is currently set to `be_en`. Similarly, Firefox's only language is English (United States).

**Comment by kevin-bates** [comment]
Hi @masasin - I apologize for the delayed response.

I think this may be related to the discussion in #5851 and how the fallbacks work.  For example, if multiple languages were embedded in the various envs and not all languages had entries for the same translated text pieces, then it seems as though you'd see multiple languages in use where some are back-filled due to there not being a translation for that particular text in the primary language.

What values do you have for your `LANGUAGE`, `LC_ALL`, `LC_MESSAGES`, and `LANG` environment variables?

**Comment by masasin** [comment]
`LANGUAGE` is `en_US:ja`, but I don't know why. `LANG` is `en_BE.UTF-8`. The rest are empty.

**Comment by kevin-bates** [comment]
Other than getting explicitly set in your login shell's profile files, I don't know how these would come about either.  I think the crux of your issue is due to the `LANGUAGE` value and the fact that we don't produce actual translation files for `en`.  I suspect if you set `LANGUAGE` to `en`, `en_US` or `en_BE` you will no longer see Japanese translations.

Btw, I'm envious that you know so many languages - that is really awesome!

**Comment by masasin** [comment]
I'll set them in my zshrc. Thanks!
