### ISSUE TITLE
RTL languages should have LTR notebooks by default

### ISSUE THREAD

**Issue by Gilthans** [jupyter/notebook#5921]
**Describe the bug**
When the default language is set to an RTL (right-to-left) language (such as hebrew or arabic), the notebook UI is unusable.
Since translation is only partial, english text becomes garbled, and elements that should always be LTR (such as code blocks) are reversed, while others that maybe should be RTL (such as output blocks) are not.

**To Reproduce**
1. Go to Chrome's settings.
2. Go to "Languages".
3. Set "Hebrew" as the top priority.
4. Open a new jupyter notebook.

**Expected behavior**
Either properly support RTL language (a lot of work), or use LTR.

**Screenshots**
(Taken from [this](https://github.com/ipython/ipython/issues/10980) very old ipython issue)
Here's a screenshot - there's nothing useful in Hebrew here, but you get the period on the wrong end of the sentence, and the path is reversed.
![image](https://user-images.githubusercontent.com/10693503/103295909-ab095080-49fd-11eb-885a-bfd3e563c174.png)

Again, no useful information in Hebrew, the In [ ] bullets are on the wrong side, and you get RTL only when it's not helpful. If anything, I'd want the word שלום to be right-aligned, but nothing else.
![image](https://user-images.githubusercontent.com/10693503/103295935-b2c8f500-49fd-11eb-92d3-02758532b770.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 87

**Additional context**
There's a long standing [ipython issue](https://github.com/ipython/ipython/issues/10980) about this, ever since this was implemented. Most developers I know ran into this, found that issue, and used one of the workaround. This has always been a terrible default.

Note that the RTL layout is *never* correct. No user would use it intentionally because it solves no problems and creates several.

The solution is simple:
In [notebook/static/bidi/bidi.js](https://github.com/jupyter/notebook/blob/bc28d6123117c3c733697e27e9d4bd71d7f0c46b/notebook/static/bidi/bidi.js#L15), the conditional setting of document.body.dir should be removed.

**Comment by m2-farzan** [comment]
@Gilthans I think you are using an old version of jupyter notebook. Since jupyter notebook version >= 6.1.0, notebook UI layout is *not* affected by browser language. For more information check out https://github.com/jupyter/notebook/pull/5052#issuecomment-647725947.

Note that the tree view (i.e. the first screenshot in your post) is still affected by browser language, but the notebook itself (i.e. the second screenshot) doesn't care about browser language.

P.S. I've just done the repro steps on my notebook installation (version 6.1.5), and here's what I got:

![image](https://user-images.githubusercontent.com/26688819/103305798-5677cc80-4a21-11eb-971f-d9de28f56635.png)

**Comment by Gilthans** [comment]
I indeed seem to have 6.0.3 installed...
Thanks for the fix!
I'll send a message in the ipython thread (since this is where google brings you), may be a good idea to close the issue though.
