### ISSUE TITLE
How to change the TLS version that is being used

### ISSUE THREAD

**Issue by Detonator120** [jupyter/notebook#5927]
OS - RHEL 6.9
Jupyter version - 4.4.0
Jupyter notebook - 5.4.0

I know that Jupyter Notebooks defaults to TLS v1.0. How can I change that to use the TLS v1.2 or v1.3 that web browsers require to use.
Is there a file that I can update? Or will it break other things?

**Comment by kevin-bates** [comment]
The ssl options are configurable via `NotebookApp.ssl_options`...
```
--NotebookApp.ssl_options=<key-1>=<value-1>...
    Supply SSL options for the tornado HTTPServer. See the tornado docs for
    details.
```
and adjustments to `ssl_version` are discussed in #3790.  E.g., looks like `--NotebookApp.ssl_options=ssl_version=5` would get you TLS v1.2.  However, given this option maps to a dictionary, it probably makes more sense to use the configuration file format shown in the referenced issue since the CLI format is a bit awkward.

I would also recommend upgrading your notebook version.

Closing.
