### ISSUE TITLE
No such file or directory: '/usr/local/opt/python/bin/python3.7'

### ISSUE THREAD

**Issue by EthelChen** [jupyter/notebook#5956]
Hi I've got a kernel error when I open my jupyter notebook. Seems that there's some disconnection between jupyter notebook and python. And the error is similar for python2 environment with error message
**No such file or directory: '/usr/local/opt/python/bin/python2.7'**

Did anyone have any similar problem or any suggestion of solution?

Great great great thanks!!!!

**Comment by kevin-bates** [comment]
This sounds like an issue of a previous kernelspec referencing a python installation that has since been removed.  To locate the kernelspec:
- run `jupyter kernelspec list` and locate the kernel you're invoking in the left column
- open the `kernel.json` file that should be located in the corresponding directory identified in the right column
- ensure that the first entry in the `argv` list is pointing to a valid python executable
- and update that entry to point to a valid location
- retry opening the notebook

**Comment by YanChen-Emily** [comment]
> This sounds like an issue of a previous kernelspec referencing a python installation that has since been removed. To locate the kernelspec:
> 
> * run `jupyter kernelspec list` and locate the kernel you're invoking in the left column
> * open the `kernel.json` file that should be located in the corresponding directory identified in the right column
> * ensure that the first entry in the `argv` list is pointing to a valid python executable
> * and update that entry to point to a valid location
> * retry opening the notebook

works now thank you!!

**Comment by EthelChen** [comment]
> This sounds like an issue of a previous kernelspec referencing a python installation that has since been removed. To locate the kernelspec:
> 
> * run `jupyter kernelspec list` and locate the kernel you're invoking in the left column
> * open the `kernel.json` file that should be located in the corresponding directory identified in the right column
> * ensure that the first entry in the `argv` list is pointing to a valid python executable
> * and update that entry to point to a valid location
> * retry opening the notebook

**Comment by EthelChen** [comment]
works now!! Thank you!!
