### ISSUE TITLE
Notebook says to use ServerApp rather than NotebookApp in configuration, but ServerApp does not work

### ISSUE THREAD

**Issue by callegar** [jupyter/notebook#5970]
**Describe the bug**

I am working with the jupyter_notebook_config.py that includes a customization of the `c.NotebookApp.browser` (to make jupyter use chrome in app mode). This works but causes `jupyter notebook` to complain:
```
jupyter notebook
[W 2021-02-02 01:20:28.494 LabApp] 'browser' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-02 01:20:28.494 LabApp] 'browser' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
```
(the message does actually occur twice).

However, trying to change the configuration property from `c.NotebookApp.browser` to `c.ServerApp.browser` (as I have it in the `jupyter_lab_config.py` configuration file for jupyter lab clears the complaint but does not work.

**To Reproduce**
1. Ask jupyter notebook to save its configuration file with `--generate-config`
2. Edit the configuration file, find the (commented) `c.NotebookApp.browser` property, edit it and uncomment it
3. Start jupyter notebook
4. Note that the customization works but causes a complaint.
5. Change the customized property to c.ServerApp.browser`
6. Start jupyter notebook
7. See that the complaint is gone, but the property does not work.

**Expected behavior**
If the property to use is `c.NotebookApp.browser` then do not complain about it. Otherwise if it is `c.ServerApp.browser` actually do as the property says.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (in fact kubuntu)
 - Browser google-chrome

**Comment by echuber2** [comment]
I noticed this too. It also gives a warning about some of the "NotebookApp" settings like `ip` and `port` even if I _have_ changed them to `ServerApp` already.

According to the migration proposals, it sounds like we're supposed to copy `jupyter_notebook_config.py` (or `jupyter_lab_config.py`) to `jupyter_server_config.py` for migration, because `ServerApp` settings will only be read from the server config file:

https://jupyter.org/enhancement-proposals/28-jupyter-server/jupyter-server.html

When I duplicate `jupter_notebook_config.py` to `jupyter_server_config.py` and start up in lab mode (I've still been using the classic notebook interface), it does seem to use the settings, despite the remaining complaints.

**Comment by Zsailer** [comment]
@MeeseeksDev migrate to jupyter-server/jupyter_server
