### ISSUE TITLE
Not able to open Jupyter notebook in windows 10 after successful installation of Anaconda

### ISSUE THREAD

**Issue by looking-for-better** [jupyter/notebook#6002]
Hello All,

I am not able to open Jupyter notebook on chrome. I have installed Anaconda successfully when I type jupyter notebook on command prompt/Anaconda command prompt it shows me error -"Script file 'C:\Users\KS5047911\AppData\Local\Continuum\anaconda3\Scripts\jupyter-notebook-script.py' is not present."

Do anyone have solution on this ?

**Comment by Zsailer** [comment]
Hi @looking-for-better, thanks for opening your issue here. 

This, unfortunately, isn't the best place to receive the help you'll need—this issue tracker is targeted at specific issues for the Jupyter Notebook application. Our apologies that this isn't more clear. 

This is likely an issue with Anaconda's distribution, not the Jupyter Notebook application itself.

Here are two options where you might get more directed help for your issue:
1) Repost your issue on the [Anaconda Issues](https://github.com/continuumio/anaconda-issues/issues) page. They can usually help you debug installation issues.
2) Post your question on the [Jupyter Discourse](https://discourse.jupyter.org/c/notebook/31) page. This is a community of Jupyter users. You might find someone who had the same issue and can help you debug it further.
