### ISSUE TITLE
Tab-completion doesn't work with dataframe

### ISSUE THREAD

**Issue by mona950101** [jupyter/notebook#6036]
**Describe the bug**
The auto-completion feature is not working properly with DataFrame. I tried to pin the `jedi`version as 0.17.2, the other modules work well with tab completion after that, except pandas. My current versions are:
```
Jupyter Notebook 6.2.0
IPython 7.14.0
Jedi 0.17.2
pandas 1.1.3
python 3.6
```

**To Reproduce**
Please refer this screenshot:
<img width="713" alt="Screen Shot 2021-04-09 at 12 20 38 AM" src="https://user-images.githubusercontent.com/80719086/114132141-6bd67f80-98c9-11eb-9d20-baaca9f135bb.png">

**Expected behavior**
As the above screenshot, the code should be completed from `df.col.str.matc + tab` to `df.col.str.match`, but it didn't.

Could someone please take a look? Thanks a lot!

**Comment by mona950101** [comment]
My current workaround is pinning the IPython as 6.5.0 which has disabled jedi, but that might not be an ideal one. 
I saw lots of use cases have fixed by only pinning the jedi verison <0.18.0, I'm surprised that it is not completely working for me. Appreciate that if someone could point me to the right place for debugging the issue.

**Comment by kevin-bates** [comment]
Hi @mona950101 - I'm not able to reproduce this issue.  I do find it takes a while to complete the first completion (following `df.`) and I think that's been a common complaint relative to `pandas` (probably due to the large API set it provides).  Here are the versions of the _interesting_ packages I'm running with:

```
ipykernel==5.5.3
ipython==7.22.0
jedi==0.18.0
jupyter-client==6.1.12
notebook==6.3.0
numpy==1.18.5
pandas==1.2.3

python==3.7.8
```
In looking around via google, it seems like there's been recent success with the `%config` magic to disable Jedi as described in this SO post: https://stackoverflow.com/questions/40536560/ipython-and-jupyter-autocomplete-not-working

When I use that magic, the slowness factor seems much improved (purely based on observation).

Perhaps something here might help you.

I recommend trying to stay on a more recent version of IPython and not downgrading if possible.

**Comment by mona950101** [comment]
Hi @kevin-bates , thanks for your help!
`%config Completer.use_jedi = False` works for me! 
If we have a chance to move forward to Python 3.7, I will try the latest IPython and Jedi, I guess things would be improved. Thanks again, I will close this issue.
