### ISSUE TITLE
Error from inputting an unhidden file

### ISSUE THREAD

**Issue by ShunichiroTomura** [jupyter/notebook#6074]
**Describe the bug**
An error occurs when an unhidden file is input to the function "is_file_hidden_posix(abs_path, stat_res=None)".
This might be caused by some bugs within the function

**To Reproduce**
1. As a test case, define a variable 
      -  var0 = 'oVo^iRqO\nqb|'
2. input the variable to the function "is_file_hidden_posix" and run the unit
3. an error will appear

**Expected behavior**
False is expected to be returned

**Desktop:**
 - OS: Windows10
 - Browser: Chrome
 - Version:  90.0.4430.212

**Comment by kevin-bates** [comment]
Hi @ShunichiroTomura.  This method is working as expected on POSIX systems.  Since you're running on Windows, the method that would come into play when `is_hidden()` is called is [`is_file_hidden_win()`](https://github.com/jupyter/notebook/blob/56416cbd2ddc92feba1978f21efb29da6406f40a/notebook/utils.py#L95).

The following code returns `False` on macOS (POSIX) regardless of whether or not a local file named `oVo^iRqO\nqb|` exists.
```python
from notebook.utils import is_file_hidden_posix

var0 = 'oVo^iRqO\nqb|'
is_hidden = is_file_hidden_posix(var0)
print(is_hidden)
```
Because there are several "special characters" in the name ('^', '\', '|') I suspect that could be interfering with your test (and despite the fact that it's calling the wrong version of `is_hidden()`).  You might try replacing `is_file_hidden_posix` with `is_file_hidden_win` or `is_hidden` and see how things go.

I'm closing this issue.  Should you find an issue relative to the platform-appropriate code, we can consider its reopening.

Thanks.
