### ISSUE TITLE
Error: jupyter notebook server connection error , not working, help please

### ISSUE THREAD

**Issue by besbesmany** [jupyter/notebook#6119]
my jupyter notebook and jupyterlab not working now I made new environment and the same error still exists

![1](https://user-images.githubusercontent.com/35992924/127217783-2142d0e1-a0d4-47ce-a021-b1dce14eb1ce.png)
![2](https://user-images.githubusercontent.com/35992924/127217795-e7d2e7ab-1371-441b-ba9f-2d51a1435d63.png)
![3](https://user-images.githubusercontent.com/35992924/127217807-b9701aea-fb94-4db0-8a91-bf2d79146ff9.png)

**Comment by Zsailer** [comment]
@besbesmany, thanks for the question.

This looks like a problem that's not specific to the Notebook package, though it's a bit difficult to determine from your screenshots. Try running JupyterLab in debug mode, i.e. `jupyter lab --debug`, to see if it produces any more information. 

Because this repository is watched by only a small crew of people (see this [notice](https://github.com/jupyter/notebook#notice)), I'd also suggest asking your question on the [Jupyter Discourse]() page. There are more Jupyter community members watching that channel who can help.

Thanks!

Before you repost there,

**Comment by besbesmany** [comment]
thank you sir 
I reinstall windows it is fixed now
