### ISSUE TITLE
How to open direct jupyter terminal instead of home/launcher page in jupyterlab

### ISSUE THREAD

**Issue by sachinkaushik** [jupyter/notebook#6136]
Hi Team,

I need your help. 

We have an requirement where we have to launch/home Jupyter Terminal directly instead of Home/Launcher page, when User get access to jupyter lab. Instead of clicking on Terminal at home page, we want to open/launch Terminal directly.

Can you please help me here? 

What else config required. I'm using a container file and installing jupyter in that file only and using that we launching jupyter lab.

Containerfile/Dockerfile :  

FROM quay.io/buildah/stable:v1.14.8

RUN yum install -y \
			python3-pip \
			python3 python3-wheel 

RUN pip install jupyterlab

**Comment by sachinkaushik** [comment]
Hi @kevin-bates .

Can you please help me on above query.?

**Comment by kevin-bates** [comment]
I'm sorry @sachinkaushik - but I don't know if this is possible, although I suspect it isn't.  I recommend posting a question/issue in [jupyterlab](https://github.com/jupyterlab/jupyterlab) since they would certainly know how to subvert the launcher functionality on startup. 

Also note that as of Jupyter Lab 3.0, the application uses [jupyter_server](https://github.com/jupyter-server/jupyter_server) as its server rather than notebook.  As a result, I'm going to close this issue since, based on the container build details above, you're installing the latest version of jupyterlab (which is 3.1.6) that depends on jupyter_server.
