### ISSUE TITLE
jupyter notebook syntax error

### ISSUE THREAD

**Issue by fearless0611** [jupyter/notebook#6142]
Error for syntax even though the code is correct ( Editor used - Jupyter notebook )
**code written** : first_name = "Jack"
print(first_name)

**Error shown** :

NameError Traceback (most recent call last)
in
1 # Exercise 3
----> 2 print(first_name)

NameError: name 'first_name' is not defined

**Comment by kevin-bates** [comment]
Without seeing all applicable cells, its tough to tell, but your output implies that line 1 is the comment `# Exercise 3` and line 2 is attempting to print the value of `first_name` yet the line `first_name = "Jack"` hasn't been executed and, as a result, `first_name` is not defined.

Are there cells prior to this that might define `first_name` and perhaps the kernel was restarted prior to this "print" cell?  This would explain why `first_name` has become undefined since kernel restarts reset the kernel's state.

**Comment by fearless0611** [comment]
So what you want to tell is i'll have to define a variable in every cell before i print it?

Iam unable to attach a screen shot of the error, so i'll just copy and paste the whole thing again in a more clearer way

**# Exercise 1**
first_name = "Jack"
**# Exercise 2**
last_name = "Carl"
**# Exercise 3**
print(first_name)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-ba361b11d0f1> in <module>
      1 # Exercise 3
----> 2 print(first_name)

NameError: name 'first_name' is not defined
**# Exercise 4**
print(first_name, last_name, sep =".")
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-586b038bc6d2> in <module>
      1 # Exercise 4
----> 2 print(first_name, last_name, sep =".")

NameError: name 'first_name' is not defined


I hope this is more clear, can you please help me out.

**Comment by fearless0611** [comment]
omg it worked I tried it just now, by running all the before cells in which I defined each variable of first_name and last_name
and tried to run all of them, and It worked
I am sorry for the inconvenience, and thanks to you! @kevin-bates
