### ISSUE TITLE
MacOS + Jupyter window hangs up

### ISSUE THREAD

**Issue by axmav** [jupyter/notebook#6195]
Hi, I try to simulate basic example from open ai gym _CartPole-v1_ using Jupyter Notebook.
As I run the code a window with simulation appears, performs the simulation and hangs. The notebook is dead.

If I run the same script without Jupyter it works good.
On Ubuntu also no problems.

**Code example**
```
import gym
env = gym.make("CartPole-v1")
observation = env.reset()
for _ in range(10):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)

  if done:
    observation = env.reset()
env.close()
```

**System Info**
MacOS 11.5.2 (Intel)
Python 3.9.7
jupyter core : 4.7.1
jupyter-notebook : 6.4.3
gym 0.20.0

Similar issue from 2017 (without solution): https://github.com/openai/gym/issues/741

<img width="500" alt="Screenshot 2021-09-30 at 21 15 15" src="https://user-images.githubusercontent.com/3396425/135520120-c8fa303f-8c45-4957-8a4c-af33b05eb4c5.png">

**Comment by aram-azbekian** [comment]
Hi! I have the same issue and running the notebook in Jupyter Lab didn't help me.

**Comment by kevin-bates** [comment]
I see the same behavior using python, IPython, Notebook, and Lab.  I don't know what the expected results should be, but the "hosting application" essentially blocks until it is terminated.  For the Notebook and Lab interactions, the pop-up may be hidden, in which case, I would imagine you'd see the described results.  However, even when exposed, I'm unable to do anything with the popped-up window.  Here are a couple of screenshots displaying what I see via Notebook and IPython...
![Screen Shot 2022-01-08 at 8 27 57 PM](https://user-images.githubusercontent.com/22599560/148827530-40f297a2-8ccc-428b-bb26-2e74aa11a7c4.png)
<img width="1376" alt="Screen Shot 2022-01-08 at 8 33 20 PM" src="https://user-images.githubusercontent.com/22599560/148827555-c086e6e1-02bc-4fbf-8fbf-a84b6ef98218.png">

What is the expected behavior?

I don't know what "statement of support" IPython kernel has for this sort of thing, but it seems like any resolution needs to be pursued from that angle and not in this repository.

Since this doesn't appear to be an issue in this repo - especially in light of its [current status](https://github.com/jupyter/notebook#notice) - I'm going ahead with its closure.
