### ISSUE TITLE
ReadTheDocs notebook rendering broken

### ISSUE THREAD

**Issue by matthew-brett** [jupyter/notebook#6207]
As of [a few weeks ago](https://discourse.jupyter.org/t/error-in-jupyter-readthedocs-page-rendering), when I go to, for example, this page:

https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Notebook%20Basics.html

the nbconvert rendering appears to have failed, and the page shows the JSON for the notebook instead of the rendered HTML. This is true for other pages on the site. Is there a problem with the nbconvert rendering of the doc build?

**Comment by blink1073** [comment]
What is your username on RTD @matthew-brett?

**Comment by kevin-bates** [comment]
> Are there instructions on building and deploying the docs, somewhere?

What exists is in the contributing portion of the docs: https://jupyter-notebook.readthedocs.io/en/latest/contributing.html#building-the-documentation.  

> I login via Github - so I think it's matthew-brett.

I've gone ahead and added you as an RTD maintainer.  Thanks for looking at this.   I'm curious how one goes about adjusting how the `stable` _meta-tag_ works because I don't see it.  We might find it easier to just produce a 6.4.5 release.

**Comment by matthew-brett** [comment]
Yes, of course, please feel free to remove me if you're already on the case
...  and thanks.

**Comment by kevin-bates** [comment]
Special thanks to @blink1073 for producing the 6.4.5 release!  

@matthew-brett - You should find the `stable` docs appropriately render the examples: https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/examples_index.html
