### ISSUE TITLE
IPython startup script examples needed

### ISSUE THREAD

**Issue by msukmanowsky** [jupyter/notebook#624]
The Jupyter [notebook migration documentation](http://jupyter.readthedocs.org/en/latest/migrating.html) does specify that IPython profiles are no longer supported, but that doesn't help users like myself looking to ensure notebook kernels run startup scripts normally located in the `~/.ipython/profile_<name>/ipython/startup/*` directory.

Would be helpful to get a response on this thread as well as some more in depth documentation on migrating aspects like these to Jupyter.

**Comment by minrk** [comment]
There is no migration to do regarding IPython startup files. The key point that appears to be missing is that IPython continues to have profiles, which have not changed. The migration docs are to convey the fact that that IPython profiles no longer affect Jupyter projects. That is, the Jupyter notebook config file has moved from the IPython profile to ~/.jupyter/jupyter_notebook_config.py. The IPython profile and its startup files continue to affect the IPython kernel, and have not changed.

**Comment by msukmanowsky** [comment]
Thanks @minrk! I think where my confusion is now is in how to create a new IPython-based Kernel for Jupyter that runs with a specified IPython profile.

**Comment by minrk** [comment]
If the kernel should *always* run with a specific profile, you can hardcode that in your Application code, rather than allowing it to be configurable. Otherwise, you can add the `--profile foo` to the argv in the kernelspec. This is how you would specify a profile for the existing IPython kernel.

**Comment by msukmanowsky** [comment]
To provide a concrete example to @minrk's instructions for anyone struggling with this like I was.

IPython searches for kernel specifications in one of three spots:

Unix:
- `/usr/share/jupyter/kernels`
- `/usr/local/share/jupyter/kernels`
- `~/.ipython/kernels`

Windows:
- `%PROGRAMDATA%\jupyter\kernels`

A kernel spec is nothing more than a folder with a `kernel.json` file that specifies how to launch that kernel. If I wanted to use a specific IPython profile (named `my-profile`), I could do something like:

```bash
mkdir -p ~/.ipython/kernels/my-custom-kernel
cat > ~/.ipython/kernels/my-custom-kernel/kernel.json <<EOF
{
    "display_name": "My Custom Python Kernel",
    "language": "python",
    "argv": [
        "python",
        "-m", "ipykernel",
        "--profile=my-profile",
        "-f", "{connection_file}"
    ],
    "env": {
    }
}
EOF
```

When launching a Jupyter notebook server, you'll now have the choice of launching either a `Python 2` kernel or a `My Custom Python Kernel` kernel.

**Comment by orenshk** [comment]
@minrk wrote:
> ...that that IPython profiles no longer affect Jupyter projects.

But they do. For example, adding exec lines to c.InteractiveShellApp runs them in the notebook.

**Comment by takluyver** [comment]
For Python notebooks, Jupyter is running an IPython kernel, which still uses the IPython config and startup files. Jupyter applications, like the notebook user interface, do not use the IPython config files.

**Comment by takluyver** [comment]
Closing this as I don't see anything concrete to do.

**Comment by Jeitan** [comment]
Can I request to reopen this and actually make an addition to the documentation as the original post asked?

See, I totally understand that Jupyter does not do profiles anymore. That is fine, no problem.  However, IPython *does* still use profiles (http://ipython.readthedocs.io/en/stable/config/intro.html), and I use them when working both in a standard console (not a Qtconsole) and I would like to use them in the *IPython kernel* that Jupyter runs.

I get that Jupyter doesn't use profiles for any of its own configuration, but what msukmanowsky posted above is the only place I've been able to find after **lots** of searching that tells me how to make Jupyter *tell IPython* to use a particular profile instead of just the default profile.

It would be nice if this could be documented in the Jupyter documentation, somehow. Even if not the exact example above, make it clear that in order to tell IPython to use a profile, you have to construct another kernelspec.  I don't think this is obvious.

**Comment by avishapiro** [comment]
I'll second @Jeitan 's request to reopen this because there are still dots that are hard for a novice to connect and also since _kernels are now a part of Jupyter and not Ipython_ (https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernels). Try `ipython kernelspec list` to see.

I tried to follow @msukmanowsky 's example to add something like `"--profile=my-profile"` to my kernel.json created when I created a conda env. It is located at `~/anaconda/envs/<env-name>/share/jupyter/kernels/python3`. However, when launching a Jupyter notebook server and a notebook, and selecting the desired kernel, it did not appear that the profile was activated or that any startup files in `~/.ipython/profile_<name>/ipython/startup/*` were run. I believe the _right_ way to do this currently is using ~/.jupyter/jupyter_notebook_config.py, but I couldn't get code there to run either.

What _did_ work was to use a cell magic `%run ~/.ipython/profile_default/startup/startup.ipy`.  I believe the _right_ way to do this currently is using ~/.jupyter/jupyter_notebook_config.py, but I couldn't get code there to run either.

**Comment by takluyver** [comment]
`jupyter_notebook_config.py` is run when the notebook server starts, not when a kernel starts. The kernel startup is up to IPython (for Python kernels).

**Comment by Jeitan** [comment]
Are there any plans to document this?  Even just a "fact-of" statement would almost be enough.

"If you still want to use a profile in your IPython kernel within Jupyter, you can create modified arguments with a custom kernel - see the IPython documentation for examples."

Just that, or something similar, would go a long way.  It makes it clear that it's an IPython-specific rather than Jupyter-specific issue, but would get people pointed in the right direction.

**Comment by takluyver** [comment]
Sounds reasonable. If you can see where in the docs it belongs, please do make a PR! It's not obvious to me where it would go.

**Comment by Jeitan** [comment]
Cool, if the devs are amenable to it I'll see if I can generate something that would be a good signpost without disturbing the docs too much ... though probably not until July as I'm just going on vacation!

**Comment by takluyver** [comment]
Thanks, and enjoy your vacation :-)
