### ISSUE TITLE
bug when using multiprocessing

### ISSUE THREAD

**Issue by Python-Ninja-Hebi** [jupyter/notebook#6258]
When using multiprocessing I got an bug

Example

```
from multiprocessing import Process
import time
import os

def test_it():
    print("test_it",os.getpid())
    time.sleep(10)
    
print("main",os.getpid())
p = Process(target=test_it)
p.start()
```

Bug

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxxx/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/xxxx/opt/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'test_it' on <module '__main__' (built-in)>

best regards Hebi

**Comment by kevin-bates** [comment]
Hi @Python-Ninja-Hebi, 

This appears to be related to IPython as the same issue occurs from within an IPython shell (yet works in vanilla Python).  I suggest taking a look for similar issues in https://github.com/ipython/ipython/issues and opening a new issue if a similar issue doesn't already exist.  Since this isn't related to this repository, I'm going ahead with its closure.
