### ISSUE TITLE
Bug running jupyterlab in Docker - "Bad config encountered during initialization"

### ISSUE THREAD

**Issue by morrisalp** [jupyter/notebook#6630]
When running jupyter-lab in Docker I encounter the following error:

`[C 11:15:44.783 LabApp] Bad config encountered during initialization: The 'contents_manager_class' trait of a LabApp instance expected a subclass of notebook.services.contents.manager.ContentsManager or jupyter_server.contents.services.managers.ContentsManage, not the JupytextContentsManager JupytextContentsManager.`

I've reproduced a minimal Dockerfile below - reproduce with `docker build -t testimg .` and `docker run testimg`.

It appears that this bug is due to Jupyterlab looking for the config file in the wrong location, because it is fixed when adding the flag `--config=.jupyter/nbconfig/tree.json` (`docker run --entrypoint jupyter-lab testimg --config=.jupyter/nbconfig/tree.json --allow-root`).

This is on Jupyterlab version: 2.3.2 (`docker run --entrypoint jupyter-lab testimg --version`)

----------

Dockerfile reproducing the bug:

```
FROM nvcr.io/nvidia/pytorch:22.10-py3
WORKDIR /root
RUN pip install --upgrade pip \
    && pip install jupyterlab
ENTRYPOINT jupyter-lab
```

**Comment by RRosio** [comment]
Hi @morrisalp, thank you for submitting this issue! Since this is an issue when you run JupyterLab this issue would be better addressed in the JupyterLab repository. If you would please try opening this issue in the Jupyterlab repository? It would also be good to try this with a more recent version of Jupyterlab if possible. Thank you
