### ISSUE TITLE
Notebook Raw Files

### ISSUE THREAD

**Issue by jessutanto** [jupyter/notebook#6673]
**Describe the bug**
I run a line on the Notebook, then it shows some error. Beside the error, there is a three dots option and i clicked something there, somehow it turned to a raw file. I just want it to go back as a normal ipynb interface. And this only happen for the specific file where i worked. The other ipynb files are working just fine as a normal notebook when i open them.

**Screenshots**
![Screenshot 2022-12-28 at 01 43 53](https://user-images.githubusercontent.com/64197384/209813568-09a747e1-06f3-437c-92d1-b7e6f6505c6c.png)

**Desktop:**
- OS: macOS Ventura 13
- PyCharm 2022.3 Professional Version

Please kindly advise.

**Comment by RRosio** [comment]
Hi @jessutanto this repository is for the Jupyter Notebook interface not the Jupyter notebook file format. Also, this appears to be an issue coming from PyCharm so it would be best to contact JetBrains for a solution. I'm closing this issue because there is nothing that we can do about it on our end.
