### ISSUE TITLE
If many extension, then panel board with btns is not in center but on left that made disonanse

### ISSUE THREAD

**Issue by ManPython** [jupyter/notebook#6727]
**Describe the bug**
If many extension, then panel board with btns is not in center but on left that made disonanse

**To Reproduce**

![Screenshot 2023-02-09 at 21-08-40 Home Page - Select or create a notebook](https://user-images.githubusercontent.com/25403861/217926082-0fbbcdc0-617a-43ca-bfaa-15a42c11ff5a.png)

**Expected behavior**
It should be in center, or give option for whole wide size width as screen allow.

**Screenshots**

![Screenshot 2023-02-09 at 21-09-05 x - Jupyter Notebook](https://user-images.githubusercontent.com/25403861/217926092-deeb3227-9bea-449d-9014-9c5750f5df8a.png)

**Desktop (please complete the following information):**

- OS: \[e.g. iOS\]
- Browser \ FF 109.0.1
- Version \[e.g. 22\]

**Additional context**

**Comment by ManPython** [comment]
Also take point about separation row as 1st and 2nd with icons, there are to close and looks ugly when many
https://github.com/jupyterlab/jupyterlab/issues/13957

**Comment by RRosio** [comment]
@ManPython thank you for opening this issue! As Notebook 6.5.x will be pulling it's static assets from [NbClassic](https://github.com/jupyter/nbclassic), I've copied this issue to the NbClassic repository so that this enhancement can be addressed there. [This is the new issue](https://github.com/jupyter/nbclassic/issues/217) in NbClassic.
