### ISSUE TITLE
Audit document widgets for feature parity with JupyterLab

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6783]
Default document widgets are different in JupyterLab and some builtin document widgets are missing. For example, in JupyterLab, if you click on a CSV file, you see a table view. In Notebook, you open it as a text editor and the table view is not available at all. We need to audit all document widgets in Notebook and test each to make sure they work and that they have the same default as Lab.

This bug was found by @ellisonbg during a bug bash.

**Comment by jtpio** [comment]
> if you click on a CSV file, you see a table view. In Notebook, you open it as a text editor and the table view is not available at all

Normally they should. For example with JSON files:

![image](https://user-images.githubusercontent.com/591645/226866072-3bb67980-3022-4aa5-9a42-b485586ac4db.png)


If I recall correctly CSV files used to be displayed with the table view by default in the Notebook 7 pre-releases. It might be a regression in the latest pre-releases if they don't anymore (maybe due to a JupyterLab update).

Could be worth to add them to the UI tests: #6322

**Comment by ellisonbg** [comment]
@JasonWeill did we open a separate issue for the bugs related to the image filetype? As I recall, if you open an image from the file browser in notebook 7 it is broken. Should also check vega/vega-lite, json, and other document types that ship with JupyterLab bey default.
