### ISSUE TITLE
Flash of unstyled content when loading pages

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/notebook#6790]
In Notebook 7.0.0a17, I am seeing a brief flash of unstyled content when loading pages.

![image](https://github.com/jupyter/notebook/assets/93281816/2d534d83-6587-4c25-ba5f-73425a176b51)

This was found by @ellisonbg during a bug bash.

**Comment by andrii-i** [comment]
Could you please record the video or describe the steps to reproduce the problem? @krassowski mentions that JupyterLab shows loading Jupyter logo animation until styles are fully loaded. We should check if problem has to do with that and potentially use the same solution.

**Comment by krassowski** [comment]
Specifically one would need to implement a [`SplashScreen` token](https://github.com/jupyterlab/jupyterlab/blob/eeaa6505f658f7eaaad18ea2d7f15c3c5da0b23a/packages/apputils/src/tokens.ts#L227-L231) - this is an optional token used by theme manager to update splash screen once the CSS of themes has fully loaded.

**Comment by jtpio** [comment]
For reference the splash screen was deliberately not added to RetroLab / Notebook 7 to make notebooks and other pages open like regular page (and not like an "application").

**Comment by JasonWeill** [comment]
Example of this happening in tip-of-`main` for Jupyter notebook:

https://github.com/jupyter/notebook/assets/93281816/bb24dadc-7c9e-4dad-ae89-28bcb342bca7

Screen capture with a flash of unstyled text (FOUT):

![image](https://github.com/jupyter/notebook/assets/93281816/2d534d83-6587-4c25-ba5f-73425a176b51)

**Comment by jtpio** [comment]
Given that the splash screen is optional, maybe that's something that could be fixed in JupyterLab directly.

Looking at the code the previous theme is first unloaded here:

https://github.com/jupyterlab/jupyterlab/blob/e0b4de1eb37c9dd37c11e5319ed00cb8d37b8d92/packages/apputils/src/thememanager.ts#L405-L410

And then the new theme is loaded here by calling its `load()` method to bring the new CSS: https://github.com/jupyterlab/jupyterlab/blob/e0b4de1eb37c9dd37c11e5319ed00cb8d37b8d92/packages/apputils/src/thememanager.ts#L423

In JupyterLab this is "hidden" by the splash screen so it's not visible by default. But if we disable the plugin that provides the splash screen with `jupyter labextension disable @jupyterlab/apputils-extension:splash` then we can also notice the flash of unstyled content:

https://github.com/jupyter/notebook/assets/591645/c7bff86d-80ac-4c94-8322-486bdfd44886
