### ISSUE TITLE
latexing errors are opaque

### ISSUE THREAD

**Issue by jasongrout** [jupyter/notebook#715]
(this report was related by @williamstein)

When the notebook does a conversion to pdf, it runs latex.  If there are any errors, the error message shown to the user is not very helpful and does not help pinpointing the error.  We could, for example, try to capture the error message from tex, run while ignoring tex errors so *something* is produced, or at least show the command line jupyter used to tex the file so the user can try to reproduce the problem.

**Comment by minrk** [comment]
Capturing the subprocess output and including it in the error should work. I think the Exception's message is already passed through in the handler, so I would guess that it's mainly a matter of including it in the Exception in nbconvert. Perhaps it should be in a special attribute, though, so that it's not in the standard tracebacks.

**Comment by minrk** [comment]
I opened jupyter/nbconvert#233 to capture latex stderr. With that and no other chnages here, the full latex barf will get to the user:

<img width="888" alt="screen shot 2016-02-08 at 13 32 36" src="https://cloud.githubusercontent.com/assets/151929/12885719/800ea5ee-ce68-11e5-8baf-d3dfa9b4c1b1.png">
