### ISSUE TITLE
Notifications API in Notebook 7

### ISSUE THREAD

**Issue by akx** [jupyter/notebook#7195]
### Problem

As an extension author, it would be useful if the [Notifications service](https://jupyterlab.readthedocs.io/en/latest/extension/ui_helpers.html#notifications) also worked in Notebook 7.

As far as I can tell, it does not (there's no widget that would surface the notifications).

### Proposed Solution

Show notifications as e.g. toasts in Notebook 7.

**Comment by jtpio** [comment]
Thanks @akx for opening the issue :+1: 

Indeed it does not seem to be surfaced in the UI at the moment. https://github.com/jupyter/notebook/pull/6627 discussed adding it to Notebook, but not sure about the current state.

Maybe it's just a matter of including the notification plugin from JupyterLab to enable the extension point.

**Comment by jtpio** [comment]
@akx checking with this example, it looks like notifications can be triggered by extensions in Notebook 7: https://github.com/jupyterlab/extension-examples/tree/main/notifications

[notebook-notifications.webm](https://github.com/jupyter/notebook/assets/591645/d81599ff-09b8-44ae-b5c2-b5039985fb46)

But it's true Notebook 7 does not have a notification center like in JupyterLab, since it does not provide a status bar:

![image](https://github.com/jupyter/notebook/assets/591645/2a21eec7-fddf-4903-83f4-269bf4f0a0ba)

Maybe it can be opened via the `Help` or `View` menu instead?

**Comment by jtpio** [comment]
> Maybe it can be opened via the `Help` or `View` menu instead?

Actually there is already a menu item under `View`, but it does not seem to be opening the notifications popup in Notebook 7:

[notebook-show-notifications.webm](https://github.com/jupyter/notebook/assets/591645/544a9a52-5233-4291-9918-894c4123a247)

**Comment by jtpio** [comment]
> Actually there is already a menu item under `View`, but it does not seem to be opening the notifications popup in Notebook 7:

This will likely be fixed by https://github.com/jupyterlab/jupyterlab/pull/15568.
