### ISSUE TITLE
Integration with RELATE

### ISSUE THREAD

**Issue by inducer** [jupyter/notebook#722]
I have written some online widgetry to support my classes. That system is called "RELATE", you can take a look here if interested:

https://github.com/inducer/relate

The basic "unit of teaching" there is called a "flow", and it presents a sequence of pages to the learner. What's on a page is pretty flexible--there are lots of options (multiple choice, python code, pdf submission, ...). The Python code submission experience could be better though, since every time a learner clicks "submit", a Docker container needs to be spun up, which leads to a 1-3 second delay, which is just enough to disrupt the nice "immediacy" that Python usually provides.

It would be really slick (at least IMO) if a Jupyter notebook could be offered up as one of the page types, along with some server-side logistics to spin up the containers running the kernels.

To my mind, Relate and Jupyter complement each other very nicely in a teaching setting. Relate's "run python" capability is basic, but it has a good story for authoring, data retention, access control to course content, and exam proctoring. Jupyter hits the opposite spot: It provides a great coding experience, but the classroom integration features are pretty basic.

So a first, basic question from my side would be: How friendly is the Jupyter codebase towards being embedded on the server and client sides (Relate is Django on the server side, but that can proxy for any wsgi app. Websockets I don't know so much about, but I assume that's likely solvable, too.) A simple client-side integration story would be to just let Jupyter manage a whole page (or an iframe) and hook into its "save" functionality. For what it's worth, the use case I have in mind is ~200-300 students in a classroom, all hacking away in their own notebooks. As in, I'd like the fan-out to individual little Docker containers on a zoo of backends to happen at the web worker level, but the scale is such that it'd likely be tricky to maintain a worker process per logged-in user.

I'd love to hear your thoughts on the feasibility of this. Also, if you're interested in devoting some resources to this, I'd love to chat--but that's not primarily what I'm asking about.

**Comment by Carreau** [comment]
Hi, 

Thanks, for writing all these things up. Probably out of order responses:

1) You might want to contact jupyter-education google group. People there might be also interested. 

2) The current server is extensible, you can add tornado handler, but not super easy, we are planning on having things more pluggable, we are actively working on it, but it will not be there soon. 

3) Yes you can embed, WSGI will likely not be enough for the notebook, that's why we have jupyterhub that can serve the notebook under one prefix, and other app under the other. It's based on a live http proxy that can update routing URLs without restart and without drooping websocket connexion. As far as we know there is not that  many apps capable of doing that.  [see there](https://developer.rackspace.com/blog/deploying-jupyterhub-for-education/) for detail. It can handle a few hundreds of people. 

4) another alternative, we are working on is making notebook component reusable, so you might be able to just embed the part of Jupyter you like.


You are likely to reach more people by writing to jupyter/jupyter-education google groups. I can't promise resources, that will likely be on a per-person basis if they decide to dedicate time on that. 

Various related project that might be useful to you:

- mybinder.org
- https://groups.google.com/forum/#!search/jupyter-education
- https://groups.google.com/forum/#!search/jupyter
- https://github.com/oreillymedia/thebe
- https://github.com/jupyter/nbgrader
- https://github.com/jupyter/jupyterhub

**Comment by inducer** [comment]
Sent them a message, we'll see what happens. Thanks for the pointers so far.
