### ISSUE TITLE
cannot import name 'version_info' from 'notebook'。My notebook version is 7.0.8, and suddenly my Jupyter Notebook has encountered some issues.

### ISSUE THREAD

**Issue by tsfTSF7** [jupyter/notebook#7272]
jupyter_nbextensions_configurator | error adding extension (enabled: True): The module 'jupyter_nbextensions_configurator' could not be found (cannot import name 'version_info' from 'notebook' (D:\Anaconda\Lib\site-packages\notebook\__init__.py)). Are you sure the extension is installed?

**Comment by tsfTSF7** [comment]
Does Jupyter Notebook update automatically?

**Comment by jtpio** [comment]
> cannot import name 'version_info' from 'notebook'

This should be fixed by https://github.com/jupyter/notebook/pull/7273

> Does Jupyter Notebook update automatically?

It really depends on how the `notebook` package is installed. If you install `notebook` with `pip install notebook` in a virtual environment and then don't run any update command, then it should not update automatically.

However some installations (based Linux distributions for example) might indeed do it for you when updating the system as a whole.

> jupyter_nbextensions_configurator | error adding extension (enabled: True): The module 'jupyter_nbextensions_configurator' could not be found (cannot import name 'version_info' from 'notebook' (D:\Anaconda\Lib\site-packages\notebook__init__.py)). Are you sure the extension is installed?

It looks like you were using the classic notebook before. If so you may want to have a look at the migration guide to help you decide whether you still need `jupyter_nbextensions_configurator` or not: https://jupyter-notebook.readthedocs.io/en/stable/migrate_to_notebook7.html
The migration guide provides some information for running the old classic notebook UI if desired.
