### ISSUE TITLE
All dialogs should order buttons in the same way

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#742]
In general, the "do action" button in a dialog should be the rightmost one and the "Cancel" should be the leftmost one:

![screen shot 2015-11-20 at 5 13 04 pm](https://cloud.githubusercontent.com/assets/27600/11315620/fafb6bf0-8fa9-11e5-87a2-ec4b5775b474.png)

Right now, in our dialogs we do both:

![screen shot 2015-11-20 at 5 13 40 pm](https://cloud.githubusercontent.com/assets/27600/11315628/26360294-8faa-11e5-8c8f-5eb13125462d.png)

![screen shot 2015-11-20 at 5 13 57 pm](https://cloud.githubusercontent.com/assets/27600/11315630/2a493c3e-8faa-11e5-9f94-4c21835b1e90.png)

This is dangerous as users might click buttons out of habits based on their positions.

**Comment by Jeffiy** [comment]
But windows user may prefer the "do action" button be the leftmost one.

**Comment by captainsafia** [comment]
@ellisonbg — I can take a look at this today.

@Jeffiy — thanks for bringing this excellent point up! The issue is less related to the operating system and more related to some research in UX. People generally read English from left to right, so when you have the action oriented button on the right, the user has more time to think about the decision. If the action button is one the left, you are more likely to hastily click it without bothering to find out what the "non action" button will do. There are a couple of other reasons for this to, that you can read about at [this article](http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/) if you are curious.

**Comment by ellisonbg** [comment]
Also, the main thing I am concerned about here is the consistency of things.

Thanks for looking at this Safia!

On Sat, Nov 21, 2015 at 12:09 PM, Safia Abdalla <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> — I can take a look at this
> today.
>
> @Jeffiy <https://github.com/Jeffiy> — thanks for bringing this excellent
> point up! The issue is less related to the operating system and more
> related to some research in UX. People generally read English from left to
> right, so when you have the action oriented button on the right, the user
> has more time to think about the decision. If the action button is one the
> left, you are more likely to hastily click it without bothering to find out
> what the "non action" button will do. There are a couple of other reasons
> for this to, that you can read about at this article
> <http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/>
> if you are curious.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/742#issuecomment-158678240>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Jeffiy** [comment]
@captainsafia awesome, thanks.

**Comment by Carreau** [comment]
1) That's no bug. 
2) That's changing UI in between minor releases, and will change the default selected button, so will break user habits. So no 4.1 either.
