### ISSUE TITLE
nbconvert to PDF drops columns visible in HTML

### ISSUE THREAD

**Issue by histed** [jupyter/notebook#756]
For markdown tables, if the second line (|---|---|---|  etc.) is missing, it is rendered correctly in HTML, but not in PDF.  It looks fine in the notebook in-browser, and using nbconvert --to HTML, but not in nbconvert --to PDF.

Markdown:
```
|col a|col b|one more|last|
|-|-|-|-|
|1 |a|0.02|4|


|col a|col b|one more|last|
|-|-|-|
|1 |a|0.02|4|
```

HTML image:
<img width="904" alt="screen shot 2015-11-25 at 9 29 29 am" src="https://cloud.githubusercontent.com/assets/176407/11399726/2ac2b252-9357-11e5-839d-ca11149eeeda.png">

PDF output image:
<img width="944" alt="screen shot 2015-11-25 at 9 32 31 am" src="https://cloud.githubusercontent.com/assets/176407/11399776/7eff7bb6-9357-11e5-828a-d31a75ca8b86.png">

$pandoc -v
pandoc 1.15.1.1
Compiled with texmath 0.8.4, highlighting-kate 0.6.
$ipython nbconvert --version
4.0.0

**Comment by minrk** [comment]
This is an inconsistency in how pandoc and marked handle invalid pipe-tables. It might be considered a bug in pandoc that it trims the columns (as opposed to throwing a render error, due to invalid markup), but I'm not sure you can rely on handling of invalid input to be consistent across different tools. It would probably be better to show an error, rather than silently ignoring the bug in the markdown input.

Since the two libraries responsible for this rendering are external dependencies (marked/mistune and pandoc), I don't think there's anything for us to do here.
