### ISSUE TITLE
Automatic hyperlink with trailing ')' not rendering properly

### ISSUE THREAD

**Issue by rlabbe** [jupyter/notebook#771]
I pasted https://en.wikipedia.org/wiki/Plant_(control_theory) into a markdown cell. When I execute it the link excludes the trailing ), treating it like part of the text (it is black, not underlined). If you click on the link you are taken to an error page on wikipedia due to the incorrect link.

If I try to create a link with [label](link) the same thing happens - if I click on the link the trailing paren is ignored.

**Comment by takluyver** [comment]
Since the syntax for a markdown link is `[title](url)`, it's easy to see why it goes wrong if there's a `)` inside the URL. I would guess you'll need to percent encode it to %29.

The bare URL might be workable, but we often want to write "blah blah (http://url)", and it's annoying if the link winds up including the `)` when it's not supposed to. Github's markdown renderer seems to be smart enough to do the right thing - I guess it counts brackets within the URL - but that's more complex.

If there is anything to be changed, it's presumably in whatever JS markdown engine we're using now. Other people: is that still marked?

**Comment by rlabbe** [comment]
%29 does work, but looks ugly in automatic mode (imo).

**Comment by minrk** [comment]
Closing here, since this is marked's behavior.
