### ISSUE TITLE
configuring zeromq protocol?

### ISSUE THREAD

**Issue by hhuuggoo** [jupyter/notebook#834]
We have some automated jobs structured around IPython, and occasionally there is a race condition which ends up in ZMQError, addr in use

I was thinking of configuring jobs either to use fixed ports, or to use ipc with tempfiles.  Is this possible?

Thanks!

**Comment by minrk** [comment]
In what sort of deployment? The KernelManager selects the ports, so you can use a custom KernelManager to select ports in a different way. You would just set the various port attributes on the KM:

```python
p = 5000
km.hb_port = p+1
km.shell_port = p+2
km.control_port = p+3
km.stdin_port = p+4
km.iopub_port = p+5
```

You cannot generally use a config file to specify kernel ports, since it would mean that all kernels would try to use the same ports and collide. That is, unless you are starting one kernel per IP. You can tell it to use ipc instead of tcp with:


```python
c.KernelManager.transport = 'ipc'
```

**Comment by JamiesHQ** [comment]
@hhuuggoo : We're doing a little housekeeping on our issue log and noticed this thread from 2015. Were you able to find a solution to your issue? Please let us know so we can close this one. thanks!

**Comment by hhuuggoo** [comment]
I don't remember anymore - I'm good with closing the issue though

thanks!

**Comment by JamiesHQ** [comment]
thanks @hhuuggoo !
