### ISSUE TITLE
Language specific Jupyter notebook settings

### ISSUE THREAD

**Issue by lmmx** [jupyter/notebook#849]
I'm looking to change the default settings for the code editor in a specific language, in the `custom.js` file.

I can see there are directories under `~/.ipython/` named `profile_default` and `profile_julia` - so I'd guess language-specific settings lived here.

* for whatever reason Julia is the only kernel language represented
* there's no `profile_bash` or `profile_shell`, and I was wanting to edit the custom settings just for editing shell scripts - but I can't tell if I should add these folders by hand

Jupyter doesn't seem to use `profile_*` folder names (I can't tell if they're deprecated or not), instead it has `.jupyter/custom/custom.js`... so I don't know if language-specific settings are possible now?

**Comment by takluyver** [comment]
We didn't carry across the notion of profiles to Jupyter, but they're not being deprecated for the config that remains in IPython - the things that specifically relate to executing Python code. profile_julia is there for historical reasons - that's how Julia integrated with the notebook before we developed better mechanisms.

You may be able to have language-specific settings by listening for the kernel start events and deciding based on the kernel in use. There can also be JS files associated with particular kernels, though that's primarily intended for kernel authors to customise the frontend if they need to, rather than for users to apply settings.

**Comment by lmmx** [comment]
Right, I see. Thanks for clarifying :+1:

**Comment by takluyver** [comment]
No worries. It is a bit confusing because of the way the project has developed.
