### ISSUE TITLE
dependencies pip

### ISSUE THREAD

**Issue by vascotenner** [jupyter/notebook#856]
I tried to install jupyter via pip. In that case it does not install zmq, and hence jupyter-notebook is not runnable.

**Comment by takluyver** [comment]
What version of pip do you have? We might be expressing some dependency in
a way that old versions of pip don't understand.

**Comment by vascotenner** [comment]
I have pip 1.5.4 

It might have to do with the fact that I did not install libzmq via apt-get. Nor installed header files for python. The same problem occured with pip3.

I just messed up my system with both jupyter with pip, and with pip3. I might have to solve that first (or yust install anaconda).

**Comment by Carreau** [comment]
I think you should upgrade pip. Last version is 7.1.2.

**Comment by takluyver** [comment]
1.5.4 is fairly old, but I suspect that the issue here is that you need the Python header files installed. You can get them with `sudo apt-get install python3-dev python-dev`. Libzmq shouldn't matter - if pyzmq doesn't find it on the system, it will build a bundled copy, I believe. But the Python header files are needed.

Anaconda has precompiled packages on Linux, whereas pip needs to compile things like pyzmq from source, so if you do decide to install Anaconda, you should avoid this issue.

Closing as, if that is indeed the problem, I don't think we can do anything about it.
