### ISSUE TITLE
Consider internationalizing all UI strings

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/notebook#870]
From what I could tell, notebook (and jupyterhub) are english only. Making it internationalizble (ugh! words!) would be very, very nice. Would love to have this for the Wikimedia install, since we're a heavily linguistically diverse user base. https://phabricator.wikimedia.org/T121478 is our tracking ticket for this.

**Comment by Carreau** [comment]
This was started a long time ago: https://github.com/ipython/ipython/issues/6718 though it requires a sustained effort and nobody agreed to take care of that. 

We could try to include that as part of the rewriting. @ellisonbg  might want to discuss that as with the Phosphor team. 

(closing the IPython side issue as it is more relevant here)

**Comment by jtpio** [comment]
Closing as fixed with Notebook 7, which uses the same infrastructure as JupyterLab for localization and supporting additional display languages.

For reference this is what the interface looks like in French:

![image](https://github.com/jupyter/notebook/assets/591645/6f9adf41-005f-4b3a-bdec-74a4ca87407b)
