### ISSUE TITLE
Align multiple selection style to our agreed upon style

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#892]
Sorry, I have been completely occupied with other things and won't probably get to return to development until next week. When we merged the multiple selection PR, it was my impression (perhaps false) that we would be iterating in master to align it with the design that we all agreed upon. The main thing that still needs to be changed before 4.1 is that we agreed that the edit mode border would be grey (with the green left border). This is important to me:

* We have changed the green to a slightly brighter color to match the Material Design blues used in the multiple select UI.
* The new design has "even more green" in the left border.
* Between the green 5px left border and brighter green, it is just too much for a UI element that gets shown to the user that often.

*Please* don't release 4.1 without fixing this...

**Comment by Carreau** [comment]
> When we merged the multiple selection PR, it was my impression (perhaps false) that we would be iterating in master to align it with the design that we all agreed upon.

We said that we **could** iterate on design, but as far as I am concern we did not say that we **would**. 

> The main thing that still needs to be changed before 4.1 is that we agreed that the edit mode border would be grey (with the green left border). This is important to me:

I would have **never** agreed to that. We have many place on the internet that say that cell in edit mode have the green border. Making it gray would make all these description false, and will make any statement that describe only the left border as Green wrong for 4.0. 

So no, I'll be strongly no-go in removing the green border **especially** since we've been in beta/rc for 10+days, and changing that would definitively mean reverting to a pre-beta state. 

I actually find the new green **less** agressive than the previous one. Though if you **really** want to revert the shade of green, I won't refuse. 


> Between the green 5px left border and brighter green, it is just too much for a UI element that gets shown to the user that often.

Brian, I think you are on of the expert in the notebook which is the most sensible to design, we we appreciate a lot, though in the other hand, I have seen many comment where only a 1px green border change of color is indistinguishable for many people. 
For example software carpentry, on overhead projector. We have the luxury of working with high-res monitor, of extremely good quality and are able to see changes that other don't. 

Please try to consider that this change will actually be visually helpful for many people.

**Comment by Carreau** [comment]
Example of books that speak of the [green border](http://nbviewer.ipython.org/github/ipython-books/minibook-2nd-code/blob/master/chapter1/13-nbui.ipynb#The-Notebook-modal-interface).

**Comment by rossant** [comment]
(pinged by @Carreau) 
I haven't followed the discussion, is there a before-after screenshot somewhere to get a better idea of the change?

**Comment by Carreau** [comment]
This sums up current and old state.

I including which I think is a "proposal" (IIUC), which @ellisonbg refer to as `is that we agreed that the edit mode border would be grey`, (which I don't remember agreeing upon).

<img width="934" alt="screen shot 2015-12-24 at 11 27 25" src="https://cloud.githubusercontent.com/assets/335567/11993455/622b23c8-aa31-11e5-950d-a97b87d7e05b.png">

**Comment by rossant** [comment]
Personally my vote goes to "4.1rc" without hesitation. I find the "proposal" confusing because of the two colors. What is the aspect of the selected cell in non-edit mode?

Also, I've always found the uniform border in 4.0 and below too thin, so "4.1rc" looks much clearer in this respect.

As a book author, I always expect interfaces to change quickly so I'm not surprised to see breaking changes like this, generally speaking. That being said I guess I wouldn't expect to see a breaking change (green => gray) in such a major aspect of the interface in a minor release version.

**Comment by Carreau** [comment]
With the proposed change the visual distinction command vs edit is too subtle IMHO.

![c vs e](https://cloud.githubusercontent.com/assets/335567/11993614/6f11ce14-aa33-11e5-92ae-8f915ee516cc.gif)

**Comment by rossant** [comment]
> With the proposed change the visual distinction command vs edit is too subtle IMHO.

completely agree with this, this behavior is much more confusing than in all the previous versions... your eye shouldn't need to move to the extreme left in order to perceive the change.

**Comment by ellisonbg** [comment]
OK, I am back from the holiday. @Carreau are you around tomorrow to chat about this?

In the meantime...

For the record, here is the original discussion:

https://github.com/jupyter/notebook/pull/708

Here is a sketch of the discussion:

* There was initial strong support for option D - but it had *no* styling of edit mode.
* I later added the MD Green #400+grey combination for edit mode to clarify how edit mode would be treated consistently with the new MC colors.
* Then Fernando suggested the D+modified, which seemed to be the most popular.
* All left borders were 5px.

What is implemented in master is someone different in multiple respects:

* It uses the original D, that has Material Design Blue #200 on the left border and Blue #50 fill on soft-selected cells.
* It uses the MD Green #400 used in my modification, but without the grey border.
* The left border widths are not 5px and they vary between the different states.

When I merged the PR, I knew there were minor style differences, but didn't want those to stall the more difficult behavioral testing of everything. I definitely should have clarified that my merging was conditional on us finishing the agreed upon visual design in master. But let's move forward...

1) While I like the pseudo-original D that is implemented in master (with the left MB Blue #200 border in multiple selected mode), I don't think was what we agreed upon. Do we need to change that?

2) Everyone liked the 5px left border always, I don't see any reason to not implement that. 

3) What to do about the edit mode styling? I used the MD Green #400 to match the MD Blue #400 of the command mode styling. Both of those choices were made based on the relatively small amount of area covered by those colors - they need to be relatively strong, but wouldn't work well if the area was larger. I used the grey edit border because that green would be too much to use on the entire border, and the grey is consistent with the rest of our UI. I still like that best:

<img width="966" alt="screen shot 2015-12-28 at 9 02 39 pm" src="https://cloud.githubusercontent.com/assets/27600/12029899/513bd4e6-adaa-11e5-9196-988c0aca89d9.png">

Another option would be to use a slightly more subtle MD Green like #200 for the rest of the border.

<img width="964" alt="screen shot 2015-12-28 at 8 56 36 pm" src="https://cloud.githubusercontent.com/assets/27600/12029903/5e4c3ec8-adaa-11e5-9cc0-2025b43e1ebd.png">

4) There is also a darker blue *right* border that I think looks like a bug, but maybe it is deliberate? In either case, we never agreed upon that so it should be removed:

<img width="101" alt="screen shot 2015-12-28 at 9 13 30 pm" src="https://cloud.githubusercontent.com/assets/27600/12029909/7918e53a-adaa-11e5-89ef-eae3a1ec67ec.png">

**Comment by Carreau** [comment]
1) I'm confused of the PR / issues number you link to, they don't seem relevant. And I don't understand the link either in context. 

> I used the grey edit border because that green would be too much to use on the entire border, and the grey is consistent with the rest of our UI. I still like that best:

There is no way I'l accept to change edit border to gray for 4.1. You can send PR and everything, I'll do all I can for edit border will stay green for 4.1. We went over the beta/RC cycle and more weeks with green as the border. I will be opposed to change that post rc (regardless of wether or not i like it).

We can refine and do that for a 4.2 if you really want it after a few weeks of testing it locally and discuss that longer, I have no problem. But 4.1 is post-freeze.

I'll make an exception and allow adjusting the green exceptionally.

> 4) There is also a darker blue right border that I think looks like a bug, but maybe it is deliberate? 

Likely not deliberate, 

> In either case, we never agreed upon that so it should be removed.

I might misunderstand the "should" in context, but I would avoid such strong statement which seem like an unilateral decision to me. I for example like it now that I see it. And again this is a post rc change. Though we are allowed to bring up this problem and **discuss as a team** what we think are critical bugs and we agree to fix in RC.

The **point** of a **rc** is to not change anything except **critical** bugs.

> OK, I am back from the holiday. @Carreau are you around tomorrow to chat about this?

Until January 5th it will be really hard for me to find time. I'll be literally on the road from 31st morning to 5th night (European time), plus some packing to do before. I might be able to find some time 29 Morning (PST), 30th morning (PST) at usual meeting times or earlier, but that's be hard. 

I'll likely not be in front of a computer, but you can try to ring my french Phone, if I'm available I'll jump on hangout.

**Comment by fperez** [comment]
My quick take on this, after some discussions with @ellisonbg and @Carreau:

- I personally hadn't actually noticed that the left blue borders in master weren't the same colors we had discussed in our "D modified" discussion in #708. They are similar enough that, until Brian pointed that fact out, I had to go and measure the RGB values to actually confirm they weren't the same, b/c on quick glance they looked close enough.

- Re. the green border, I personally actually *like* the current, all-around green border.  I have this week been using the notebook 'in anger' in writing long and complex notebooks, with lots of back-and-forth between command and edit mode, and I actually found the full green highlight quite useful in marking the state of being in command mode to me, without being so garish as to be annoying.   Note that I'm stating *my* opinion here as a data point from one user, not making a decision.  It's just that we need to converge quickly on a decision so we can wrap it up, so for now it will be up to our own sense of balance between the usefulness of conveying that information with the green highlight and not going overboard.

- Re the thin blue border on selected cells: it feels a bit inconsistent to me in that it's only on the right and not on the top/bottom, and thus it's different from every other visual element we already have (the other outlines are all complete).  And it's true that it was never part of our discussions in #708.  Now, it's not an end-of-the-world issue, but I agree that it's not great to have there, I just hadn't noticed it before.

So the question at this point is, do we hold a release over this or not? They are obviously UI issues and not core functionality bugs, but the reality is that we also have #893 that will require extra work, so I suggest that we go ahead and polish this up since we can, while that nasty problem gets sorted out...  

If we were literally about to pull the trigger on a release and it came down only to these issues, we might think differently about it, but given that making these changes is probably a tiny PR with:

- Removal of the little blue right-border.
- [Optionally] change the blue shades to the ones from the #708 discussion.

That's probably very doable.

We can then ask on-list about the green outline for cmd mode.  As I said, I'd be personally quite happy leaving it as-is as I like this version. But others might disagree, and if consensus is strongly in the opposite direction, I have no problem with that.

How does this sound?  I suspect that #893 will give us plenty of time to do the above before cutting an actual release anyway...

**Comment by ellisonbg** [comment]
Thanks for the summary:

* I am in favor or removing the little blue right-border in 4.1.
* I personally like the left blue border used in multiply selected cells in master (MD Blue #200) but it wasn't the option that most people preferred originally (most preferred to have the left blue border match the background which is MD Blue #50). No objection from me leaving this as is.
* I am open to the current green border (MD Green #400) in master as long as we run it by everyone (I personally prefer green left with grey on the rest)

**Comment by fperez** [comment]
BTW, Brian helped me clarify one point I was confused on: master currently does *not* implement something we had indeed agreed on during the #708 discussion, which was the left-border highlight. I got tripped by mis-measuring colors on an old screenshot and got side-tracked, the point is that when we finished up the #708 discussion, we'd agreed on implementing something that would look roughly like this:
 
![image](https://cloud.githubusercontent.com/assets/57394/12047312/49f8185a-ae7e-11e5-8229-4d1bda633722.png)

I actually do still like that original choice (which was our common consensus) better than what we do have in master right now.  I admit that I wasn't paying close enough attention to notice the difference, but looking at them side by side and going over the original #708 discussion, and considering that this was the choice that we ultimately converged on, I do think that it would make more sense to go with that option.

**Comment by Carreau** [comment]
Please Brian stop using hash-number you are cross linking PRs and issues.
You can use backticks.

As I said I'm fine with slight changing of shade, please make PRs I can test/review/merge. It will be faster to actually have a change I can see/test than trying to describe.

I already made a PR to change the green, but apparently I misunderstood which. And going back and forth trying to guess is starting to be painful.

The removal of the green border though is a no-go unless we test it for minimum 2 weeks with users.

So I'll wait for Brian PR(s) on CSS. Preferably each change separately.
Once I'm online again, I can test/+1/merge.

The other "blocking" issue seem also like overly complicated bike shedding. A PR with the changes Brian wants for 4.1 would be simpler to accept/reject, than trying to infer through the long description what is needed. Especially since AFAICT it's one harmless line.

Envoyé de mon iPhone

**Comment by Carreau** [comment]
> They are similar enough that, until Brian pointed that fact out, I had to go and measure the RGB values to actually confirm they weren't the same, b/c on quick glance they looked close enough.

Note that I used the CSS value from Brian branch, and that the RGB values measured always differ slightly from the CSS one (at least on my computer) due to Apple "Smart color adjusting" which lead to pictures/screen/css having value that don't correspond.

This is a known issue : ![](http://i.stack.imgur.com/dtHPK.png)

> we'd agreed on implementing something that would look roughly like this:

Some of the votes where for the D-modified variation because of the "gap" in between cells due to implementation using borders. The gap is no longer present as we now uses background-gradients. 

Also keeping the border on left for soft-selected cells **was considered better for visually deficient (colorblind) users [and bad overhead projectors]**, where the background only was not enough distinguishable.  We tried in BIDS which is not great but still good, and I let you guess with the Projector we use at dev meetings. 

This was also one if the reason why in multiple selection cells (marking first implementation) we had border of various width.

I'm sad this is not recorded as text somewhere, or I don't find it.

And if I read correctly the discussion even Brian was for D-original:

```
D-original: Brian mildly +
D-modified: Fernando mildly +
```

I'm fine changing if you push for it though, (slightly negative as we are post RC for a removal though), also this will force us to redo screenshots everywhere.

**Comment by ellisonbg** [comment]
LOL about the hash number using in colors ;-) Sorry about that...

On Wed, Dec 30, 2015 at 12:34 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Please Brian stop using hash-number you are cross linking PRs and issues.
> You can use backticks.
>
> As I said I'm fine with slight changing of shade, please make PRs I can
> test/review/merge. It will be faster to actually have a change I can
> see/test than trying to describe.
>
> I already made a PR to change the green, but apparently I misunderstood
> which. And going back and forth trying to guess is starting to be painful.
>
> The removal of the green border though is a no-go unless we test it for
> minimum 2 weeks with users.
>
> So I'll wait for Brian PR(s) on CSS. Preferably each change separately.
> Once I'm online again, I can test/+1/merge.
>
> The other "blocking" issue seem also like overly complicated bike
> shedding. A PR with the changes Brian wants for 4.1 would be simpler to
> accept/reject, than trying to infer through the long description what is
> needed. Especially since AFAICT it's one harmless line.
>
> Envoyé de mon iPhone
>
> > Le 30 déc. 2015 à 06:00, "Brian E. Granger" <notifications@github.com>
> a écrit :
> >
> > Thanks for the summary:
> >
> > I am in favor or removing the little blue right-border in 4.1.
> > I personally like the left blue border used in multiply selected cells
> in master (MD Blue #200) but it wasn't the option that most people
> preferred originally (most preferred to have the left blue border match the
> background which is MD Blue #50). No objection from me leaving this as is.
> > I am open to the current green border (MD Green #400) in master as long
> as we run it by everyone (I personally prefer green left with grey on the
> rest)
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/892#issuecomment-167957611>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
I think we got this in @Carreau's recent PRs.
