### ISSUE TITLE
Undo feature request

### ISSUE THREAD

**Issue by nunocalaim** [jupyter/notebook#932]
I accidentally deleted two cells consecutively, one with a lot of code and an empty one. I can only undo the last deletion, i.e. the empty one. So the content of the other is forever lost.

I thought unlimited undoing was standard nowadays, why does the notebook lack this functionality?

**Comment by Carreau** [comment]
> why does the notebook lack this functionality

Partly because unlimited undoing is a much more complex subject when the document is executable.
Which is the case with the notebook.

Example : if i do `a=1`, execute, `a=2`, execute, and undo what am I suppose to undo ? The execution ? 

Then you enter question like : Can the execution be undone ? Can it be undone reliably across languages ? What if other code is currently being ran ?.... etc, and I just scratch the surface. 

Other part : we assessed the benefit/cost ratio, and decided that with the current manpower/usage/cost/number-of-features-needed/current-architecture it was not worth implementing, at least yet.

This can of course change if there is a change in any of the above mentioned factor, especially if we get more help for code maintenance.

I'm closing as the multiple undo has already a few issues where it is discussed, but feel free to continue adding comments to this issues if you like. 

Thanks.
