### ISSUE TITLE
Feature request for improved user interface

### ISSUE THREAD

**Issue by sebnil** [jupyter/notebook#97]
Coming from Matlab, Jupyter has the potential of being a replacement but as it is right now it is a bit cumbersome to work with. For example I would like to a small window of all my notebooks and run each of them with a double click. And write algorithms in one file and plot in another. And being able to see defined variables. As it is right now I find myself writing really big notebooks instead of organizing them in different files. 

This ticket is a feature request. Keep up the good work!

**Comment by donaldbraman** [comment]
maybe checkout [yhat rodeo](https://github.com/yhat/rodeo).  Might solve some of your problems.

**Comment by sebnil** [comment]
Thank you. I will have a look at that one.

lördag 27 juni 2015 skrev Donald Braman <notifications@github.com>:

**Comment by rgbkrk** [comment]
Have you seen the Atom package Hydrogen?

![](https://camo.githubusercontent.com/df535b1882e71808e9f1cd19c66a3674628cc805/687474703a2f2f692e696d6775722e636f6d2f524650443163392e676966)

It does rich integration with Jupyter and is aiming to support much of what you're looking for, including watch expressions.

/cc @willwhitney

**Comment by rgbkrk** [comment]
Though of course, there's no support for notebooks in there (yet).

**Comment by willwhitney** [comment]
Hydrogen author here — 

Hydrogen might be a good fit for some of this. It's designed for working with bigger projects (supporting Real Projects instead of experimentation and demos) and so having algorithms and plots and whatnot in different places works well.

Watch expressions in Hydrogen: 

![hydrogen-watches-cropped](https://cloud.githubusercontent.com/assets/597829/8393637/adc5011a-1ce6-11e5-9760-d5f6c2ac7d94.gif)

As far as being able to see the defined variables, I'm working with the Jupyter team to add this (not just in Hydrogen, but everywhere) and do it in a cross-language way. Until then, the `%who` magic in Python will at least give you a list of the names of the variables you've defined.

**Comment by ellisonbg** [comment]
Thanks for posting this!

On Sat, Jun 27, 2015 at 1:12 PM, Will Whitney <notifications@github.com>
wrote:

> Hydrogen author here —
>
> Hydrogen might be a good fit for some of this. It's designed for working
> with bigger projects (supporting Real Projects instead of experimentation
> and demos) and so having algorithms and plots and whatnot in different
> places works well.
>
> Watch expressions in Hydrogen:
>
> [image: hydrogen-watches-cropped]
> <https://cloud.githubusercontent.com/assets/597829/8393637/adc5011a-1ce6-11e5-9760-d5f6c2ac7d94.gif>
>
> As far as being able to see the defined variables, I'm working with the
> Jupyter team to add this (not just in Hydrogen, but everywhere) and do it
> in a cross-language way. Until then, the %who magic in Python will at
> least give you a list of the names of the variables you've defined.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/97#issuecomment-116129969>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
