### ISSUE TITLE
 "Download as Python" for the just created empty notebook, saves the notebook as .txt

### ISSUE THREAD

**Issue by skukhtichev** [jupyter/notebook#978]
How to reproduce:
1. Create new Notebook
2. Click "Download as" -> "Python"
3. Download window saves file as .txt
Expected format: .py

**Comment by takluyver** [comment]
Does this only happen if you do it literally as soon as you create a new notebook? There might be a brief delay before it gets the language info from the kernel, but if that's the cause, you should see 'Script' instead of 'Python' in the download menu.

Otherwise, what OS and browser are you using? Can you easily try with a different browser? Our HTTP headers should say that the mimetype is `text/x-python` and suggest a filename ending in `.py`, but the browser may ignore that.

**Comment by skukhtichev** [comment]
Yes, it happens just after the creating new notebook. When I'm trying to download as .ipynb or .html everything works fine. I'm using Mac OS 10.10.5. I tried with Chrome, Safari and Firefox, and I have the same issue with all these browsers.

**Comment by takluyver** [comment]
So if you wait say 10 seconds, and the kernel has started, it will save as .py? If that's the case, I think it's working as designed, though I'm surprised it takes long enough that you can click that before it has got the file extension in place.

**Comment by willingc** [comment]
@skukhtichev Are you using Notebook version 4.1 (The version can be checked at the command line or in the Help->About menu option? 

I'm using Mac OS 10.11.3 and the same process is saving as a ``.py`` file.

**Comment by skukhtichev** [comment]
The problem occurred with 4.0.6 version. I installed 4.1.0, and "Download as python" works correct.

**Comment by takluyver** [comment]
Great, thanks for letting us know.
