### ISSUE TITLE
improved completions with type hinting

### ISSUE THREAD

**Issue by willwhitney** [jupyter/notebook#99]
The `autocomplete-plus` package for the Atom editor (recently bundled into Atom) shows how powerful [types in autocomplete](https://github.com/atom/autocomplete-plus/pull/334) can be.

![atom completions](https://cloud.githubusercontent.com/assets/69169/6793515/b505ee3a-d182-11e4-9b9f-74b2a5d77365.png)

Something similar would be a huge boon to Jupyter. Instead of just showing text matches for variables in the running kernel (already very powerful!), show what they are: a variable of type String, a function that takes two integers and returns a float, etc. 

This would be a huge step forward for interactive programming of interpreted languages, and would truly showcase the power of having a live kernel to introspect into.

**Comment by ellisonbg** [comment]
Yeah, I saw this and thought the same thing. We should look at how atom is
doing this and use that as inspiration.

On Sat, May 16, 2015 at 7:13 PM, Will Whitney <notifications@github.com>
wrote:

> The autocomplete-plus package for the Atom editor (recently bundled into
> Atom) shows how powerful types in autocomplete
> <https://github.com/atom/autocomplete-plus/pull/334> can be.
>
> [image: atom completions]
> <https://cloud.githubusercontent.com/assets/69169/6793515/b505ee3a-d182-11e4-9b9f-74b2a5d77365.png>
>
> Something similar would be a huge boon to Jupyter. Instead of just showing
> text matches for variables in the running kernel (already very powerful!),
> show what they are: a variable of type String, a function that takes two
> integers and returns a float, etc.
>
> This would be a huge step forward for interactive programming of
> interpreted languages, and would truly showcase the power of having a live
> kernel to introspect into.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/99>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by bollwyvl** [comment]
Without having dug into this, i think it's an incredibly good idea. Any updates here?

I assume there would be some list of type identifier strings that each token could provide.

If so, and they were stable across machines and versions, and we had indexing (long-missed feature), and a tree of notebooks could be opted in (jupyter nblibrary index)...

a documentation author would be able to reference the symbol type strings in cell metadata (new ui), to allow contextual "open documentation for..." with examples, etc. (New ui) This annotation could be done automatically, probably, though it could be guided so that not everyone documents "import".

This would put us almost at parity with the Mathematica documentation machinery... And encourage us to :dog: :pizza: our process for docs... Targeting rtd is great, and our docs should go up there, but it's no joke finding exactly what you need... Or impossible if you are in an environment without internet.

**Comment by willwhitney** [comment]
@bollwyvl the thread tracking this: https://github.com/jupyter/jupyter_client/issues/51

It's my fault there hasn't been more progress on this recently. I was working on it during the summer, and I've gotten completely slammed this semester. Taking a class, applying to PhDs, trying to get a paper finished, and writing my Master's thesis all in one semester will do that, I guess.

I still plan to get this shipped, but at this point I don't see myself being able to work on it until after I turn in my thesis at the end of January. If someone else wants to pick it up and finish it in the meantime, that would be very welcome.

**Comment by bollwyvl** [comment]
Thanks for the link! looks like a bruiser. I see some stuff about docs
there, which is cool.

Good luck on your thesis!

**Comment by JamiesHQ** [comment]
@willwhitney : We're doing a little housecleaning on our issue log and I noticed this thread from 2015. Has this issue been resolved to your satisfaction and can it be closed? thanks!

**Comment by willwhitney** [comment]
Go for it!

**Comment by JamiesHQ** [comment]
Thanks @willwhitney !
